### ISSUE TITLE
Node_modules path in scss  (cannot import scss file from dkfds-plugins)

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#10]
**Node_modules path in scss  (cannot import scss file from dkfds-plugins)**

**Genskab fejlen (To Reproduce)**
1. npm install dkfds  + npm install dkfds-plugins 
2. import "../node_modules/dkfds-plugins/datatables/style/dkfds-datatables-theme"; in project scss file.
3. See path errors when project build:
    - cannot find ../../../../node_modules/dkfds/src/stylesheets/core/variables.
    - cannot find ../../../../node_modules/dkfds/src/stylesheets/core/mixins.

**Quick fix**
Add two directories backward in node_modules path, so the path from directory 'style' in dkfds-plugins links to 'variables' og 'mixins' in dkfds/src/stylessheets/core

![image](https://user-images.githubusercontent.com/25169794/52553436-c526ef00-2de3-11e9-96d7-ddd7e6cd4cec.png)

**Supplerende oplysninger (Additional context)**
Angular cli project

**Comment by detfaellesdesignsystem** [comment]
Hi @laclogin,

Thank you for contacting us.

A new version of dkfds-plugins should now be available with a fix for the issue you mention.

The references to variables, mixins and breakpoints have been removed from the sass files, and you should now be sure to import the sass file from dkfds before importing your plugin theme styles.

If you need the .min.css version, a standalone version is available. 

Please see the page [https://detfaellesdesignsystem.github.io/dkfds-docs/omdesignsystemet/tiludviklere/](https://detfaellesdesignsystem.github.io/dkfds-docs/omdesignsystemet/tiludviklere/) for more info on how to import the styles.

Please let me know if you continue to experience problems.

Best regards,
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Det er super :-) Mange tak for jeres hurtige fix.
