### ISSUE TITLE
"Progress bar" ved fil-upload

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#100]
Hej,
På mange af vores selvbetjeningløsninger er det muligt at uploade store filer og det betyder selvfølgelige længere ventetid - derfor efterlyser vi en "progress bar" ( som evt. vises, hvis upload tiden tager mere end 10 sek.), så brugerne ikke er i tvivl om, at processen er i gang og at de blot skal vente.
Pt. viser vi en spinner til at indikere processen er i gang - og denne vil vi gerne erstatte med procentvisning. 

![image](https://user-images.githubusercontent.com/48348000/75674843-3e5ee180-5c86-11ea-98cd-39f07dcab71c.png)

Har I gjort jer nogle overvejelser omkring "process bar" - i så fald hvilken slags "progress-bar" anbefaler I?

Mvh.
Farzana fra ATP

![image](https://user-images.githubusercontent.com/48348000/75674109-b62c0c80-5c84-11ea-9be6-039c7db7e963.png)

**Comment by DKFDSdevelop** [comment]
Hej @FNA-atp 

Vi har ikke haft denne komponent på vores radar, så vi kan desværre ikke anbefale noget pt. Jeg opretter et issue i backloggen. 

GDS har nogle issues, der berører emnet:
https://github.com/alphagov/govuk-design-system-backlog/issues/164
https://github.com/alphagov/govuk-design-system-backlog/issues/49

Lightning Design System har to variationer, er det noget i denne dur I efterspørger?
https://www.lightningdesignsystem.com/components/progress-bar/
https://www.lightningdesignsystem.com/components/progress-ring/

Mvh
Sune
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Sune,
Vi synes, ringen passer bedst til løsningen :-)
https://www.lightningdesignsystem.com/components/progress-ring/

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Det er taget til efterretning.

---
Hej @FNA-atp

Vi har ikke haft denne komponent på vores radar, så vi kan desværre ikke anbefale noget pt. Jeg opretter et issue i backloggen.

GDS har nogle issues, der berører emnet:
alphagov/govuk-design-system-backlog#164
alphagov/govuk-design-system-backlog#49

Lightning Design System har to variationer, er det noget i denne dur I efterspørger?
https://www.lightningdesignsystem.com/components/progress-bar/
https://www.lightningdesignsystem.com/components/progress-ring/
---

Mvh
Sune
Det Fælles Designsystem
