### ISSUE TITLE
Tabel i accordion?

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#101]
Hej
Jeg er i gang med en løsning, hvor vi ønsker at skjule nogle tabeller. Deres indhold er sekundært og vil formentlig ikke være relevant for særlig mange brugere, men tabellerne skal alligevel være der. 
Mit bedste bud er at lægge de enkelte tabeller i accordions - se vedhæftede. Og jeg vil bare lige sikre mig, at det er i orden. 
Jeg er godt klar over, at der kan være udfordringer med tabeller på mobilen, men her er tale om tabeller med bare to kolonner, så jeg tror, at de bliver ok selv på mobilen. Desuden kan kolonneoverskriften 'Samlet beløb betalt efter skat' forkortes, hvis nødvendigt.
Løsningen vil i øvrigt først og fremmest blive tilgået fra desktop - i tilsvarende løsninger er det mindre end 1 % af besøgene, der kommer fra mobil. 
Håber I kan godkende mit bud :)

![Tabel i accordion](https://user-images.githubusercontent.com/54175531/76024002-a170a280-5f2a-11ea-98bf-583f25155c44.jpg)

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo ,

Tak for din henvendelse.

Vi har lavet en sag på din henvendelse og en UX'er vil vende tilbage med et svar.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by DKFDSdevelop** [comment]
Kære Kirsten @KirstenTo 

Tak for din henvendelse. Spændende løsning du er arbejder på! Det kan godt være lidt udfordrende at sætte sig helt ind i uden mere kontekst, derfor må du tage hvad du kan bruge af feedback’en der kommer nedenfor. Som udgangspunkt kan du læse mere om anbefalinger og retningslinjer på designsystem.dk. I forhold til din kommentar omkring godkendelse af løsningen, er det her Virk du skal kommunikere med. Vi i Det Fælles Designsystem giver blot retningslinjer og anbefalinger.

De følgende retningslinjer er med forbehold, da vi ikke ved:
1. Er vigtigt at vise alle årstal?
2. Kan der være scenarier hvor der er mange årstal til stede?
3. Er der behov for at sortere i tabellen - her måned og beløb?

**Ifht. punkt 1 og 2:** 
Såfremt det er mindre vigtigt at vise alle årstal og der kan være mange til stede (f.eks. 20 år tilbage),

kan i overveje at implementere en dropdown eller anden filtreringsløsning hvor man kan vælge for hvilket årstal man vil se informationer. (Se komponent for dropdown her: https://designsystem.dk/komponenter/drop-down/, samt komponent for tabel med filtrering her, under avanceret tabeller: https://designsystem.dk/komponenter/tables/)

På den måde kan i nøjes med et vise data for 1 år ad gangen, og dermed have færre mængder data der skal vises på én gang.

**Ifht. punkt 3:**
Hvis det ikke er vigtigt at sortere data i tabellen, kan i overveje at fjerne det i tabellen, da det kan forvirre brugeren mere end det gavner.  

**Brug af accordions**
Generelt anbefales det ikke, at man forsøger at skjule information for brugeren. Dog kan der være situationer, hvor det giver en bedre brugeroplevelse, og man derfor bliver nødt til at bruge accordions og lignende (Læs mere om accordions her: https://designsystem.dk/komponenter/accordions/)

Hvis I fortsat vil benytte accordions, kan i overveje at benytte komponenten med rammer på. Rammerne kan være med til, at gøre det nemmere at afkode for brugeren - særligt under månederne, da det kan være svært se om de er samme “type” data. (Accordions med rammer: https://designsystem.dk/komponenter/accordions/#tilf%C3%B8j-ramme)

Vi anbefaler at alle implementeret løsninger skal være responsive og dermed anvendelige både på mobil og desktop. Jeg tror du har ret i din anskuelse om, at det burde kunne lade sig gøre med de mængder data i overvejer at inkludere i tabellerne.

Håber det kan bruges i jeres videre arbejde.

Med venlig hilsen
Anja
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Kære Kirsten @KirstenTo 

Tak for din henvendelse. Spændende løsning du er arbejder på! Det kan godt være lidt udfordrende at sætte sig helt ind i uden mere kontekst, derfor må du tage hvad du kan bruge af feedback’en der kommer nedenfor. Som udgangspunkt kan du læse mere om anbefalinger og retningslinjer på designsystem.dk. I forhold til din kommentar omkring godkendelse af løsningen, er det her Virk du skal kommunikere med. Vi i Det Fælles Designsystem giver blot retningslinjer og anbefalinger.

De følgende retningslinjer er med forbehold, da vi ikke ved:
1. Er vigtigt at vise alle årstal?
2. Kan der være scenarier hvor der er mange årstal til stede?
3. Er der behov for at sortere i tabellen - her måned og beløb?

**Ifht. punkt 1 og 2:** 
Såfremt det er mindre vigtigt at vise alle årstal og der kan være mange til stede (f.eks. 20 år tilbage),

kan i overveje at implementere en dropdown eller anden filtreringsløsning hvor man kan vælge for hvilket årstal man vil se informationer. (Se komponent for dropdown her: https://designsystem.dk/komponenter/drop-down/, samt komponent for tabel med filtrering her, under avanceret tabeller: https://designsystem.dk/komponenter/tables/)

På den måde kan i nøjes med et vise data for 1 år ad gangen, og dermed have færre mængder data der skal vises på én gang.

**Ifht. punkt 3:**
Hvis det ikke er vigtigt at sortere data i tabellen, kan i overveje at fjerne det i tabellen, da det kan forvirre brugeren mere end det gavner.  

**Brug af accordions**
Generelt anbefales det ikke, at man forsøger at skjule information for brugeren. Dog kan der være situationer, hvor det giver en bedre brugeroplevelse, og man derfor bliver nødt til at bruge accordions og lignende (Læs mere om accordions her: https://designsystem.dk/komponenter/accordions/)

Hvis I fortsat vil benytte accordions, kan i overveje at benytte komponenten med rammer på. Rammerne kan være med til, at gøre det nemmere at afkode for brugeren - særligt under månederne, da det kan være svært se om de er samme “type” data. (Accordions med rammer: https://designsystem.dk/komponenter/accordions/#tilf%C3%B8j-ramme)

Vi anbefaler at alle implementeret løsninger skal være responsive og dermed anvendelige både på mobil og desktop. Jeg tror du har ret i din anskuelse om, at det burde kunne lade sig gøre med de mængder data i overvejer at inkludere i tabellerne.

Håber det kan bruges i jeres videre arbejde.

Med venlig hilsen
Anja
Det Fælles Designsystem
