### ISSUE TITLE
Tekststil ændrer sig i dropdown menu

### ISSUE THREAD

**Issue by jhof-nc** [detfaellesdesignsystem/dkfds-components#102]
Hej

Vi har lagt mærke til, at når man bruger dropdown menu og klikker på at åbne menu, teksterne i dropdown menu har en anden stil end resten af løsningen. Det er en lille ting, men ville være dejligt at rette. Fejlen kan reproduceres i jeres demoer (Gade / vejnavn spørgsmål): https://designsystem.dk/pages/eksempler/digital-flytning/flytning-3/

Fejlen kan reproduceres i Firefox.

**Comment by detfaellesdesignsystem** [comment]
Hej @jhof-nc ,

Tak for din henvendelse!

Vi laver en sag på det i backloggen og vender lige tilbage, når vi har haft mulighed for at kigge på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Fix implementeret i version 7.2.0
