### ISSUE TITLE
Font path in dist/css/dkfds-tippy-theme.standalone.css is wrong

### ISSUE THREAD

**Issue by 4nd3r5** [detfaellesdesignsystem/dkfds-components#104]
**Bekskriv fejlen (Describe the bug)**
In this file: dist/css/dkfds-tippy-theme.standalone.css, 
The path to the font files in dist/dkfds/fonts/IBMPlexSans are not specified correctly.
They are set to ../fonts/IBMPlexSans/, which should be ../dkfds/fonts/IBMPlexSans/ or are non relative path

**Indsæt link (Add a URL)**
https://github.com/detfaellesdesignsystem/dkfds-plugins/blob/master/dist/css/dkfds-tippy-theme.standalone.css

**Comment by detfaellesdesignsystem** [comment]
Hi @4nd3r5,

Thanks for contacting us!

I've created an issue in our backlog and we'll get back to you when we've had the opportunity to look into this issue.

Best regards,
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hi @4nd3r5,

Version 6.0.1 has been released with a fix.

It wasn't necessary with a font-face definition in the tippy theme since all themes are to be used with the core of DKFDS where the definition is, so we just removed that part.

Best regards,
Kristina Jensen
Det Fælles Designsystem
