### ISSUE TITLE
Pikaday dokumentationen er fejbehæftet

### ISSUE THREAD

**Issue by 4nd3r5** [detfaellesdesignsystem/dkfds-components#106]
**Bekskriv fejlen (Describe the bug)**
Dokumentationen af brug af pikaday er forkert

**Genskab fejlen (To Reproduce)**
I teksten for implementationen står der: 

> Implementering
> Installer dkfds-plugins fra npm og inkludér enten CSS eller SCSS filen for pluginnet i dit projekt. For mere info, se implementeringaf DKFDS.
> 
> Stien til filen du skal inkludere for Pikaday er henholdsvis [path-to-plugins-project]/dist/css/dkfds-pikaday-theme.standalone.min.css for CSS filen og ~dkfds-plugins/dist/scss/dkfds-pikaday-theme for SCSS filen.
> 
> Man skal dog stadig inkludere Pikadays egen CSS og JavaScript. Følg Pikadays egen dokumentation for implementering af pluginnet i dit projekt.

Dete er ikke korrekt at man skal inkludere Pikadays egen CSS.
Kun DKFDS CSS skal bruges ellers ser datovælgeren forkert ud.

**Indsæt link (Add a URL)**
https://designsystem.dk/kode/plugins/pikaday/

**Comment by detfaellesdesignsystem** [comment]
Hej @4nd3r5,

Tak for din henvendelse.

Vi får lige kigget på det. Kan være vi skal have opdateret vores pikaday support version. Og ellers retter vi blot teksten. :)

Vender lige tilbage.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by 4nd3r5** [comment]
Umiddelbart er det nyeste Pikaday der bruges, og det er også den vi bruger.

**Comment by detfaellesdesignsystem** [comment]
Hej @4nd3r5,

Vi har fjernet fremtidig support af tredjeparts plugins og dermed også dokumentationen dette issue handler om.

Jeg lukker derfor sagen her.

Læs mere om brug af tredjeparts plugins sammen med DKFDS her: https://designsystem.dk/kode/plugins/

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
