### ISSUE TITLE
Pikaday afklaring

### ISSUE THREAD

**Issue by 4nd3r5** [detfaellesdesignsystem/dkfds-components#107]
**Beskriv fejlen (Describe the bug)**
Det er måske ikke en fejl, men måske snarere en afklaring, som vi har brug for et svar på. Vi er begyndt at bruge jeres pikaday udvidelse, men da den ikke kan benyttes af screen readers vil vi gerne høre hvad jeres plan er?Umiddelbart ser projektet inaktivt ud, og det issue i har oprettet hos pikaday ser ikke ud til at være særlig aktivt. Det er ikke engang besvaret siden oprettelsen 13. august, 2019.(https://github.com/Pikaday/Pikaday/issues/859).
Vi overvejer lidt hvad vi gør i forhold til screen readers vi kan jo sætte en aria-hidden på knappen der åbner datepickeren f.eks. Men er lidt i tvivl om hvor brugervenligt det er for synshandicappet?

**Comment by detfaellesdesignsystem** [comment]
Hej @4nd3r5,

Tak fordi du tager dig tid til at skrive til os, så vi får fulgt op på Pikaday.

Vi kender desværre ikke til fungerende tilgængelige datepickers, og vil derfor anbefale, at man ikke gør brug af dem. Pikaday var et sjældent godt bud, men da det ikke længere lever op til kravet om tilgængelighed, kan vi ikke anbefale at anvende det. Blot for at klarificere, så er Pikaday ikke et FDS produkt, men et plugin vi pegede på som et tilgængeligt alternativ, hvilket det ikke er længere, hvorfor vi ikke kan anbefale at anvende det.

I forhold til dit spørgsmål vedr. aria-hidden; så er det problematisk at sætte aria-hidden på elementer, der kan sættes fokus på, da man stadig vil kunne tabulere sig til elementet, i dette tilfælde kalender-ikonet, hvilket bevirker at skærmlæseren læser noget underligt op eller at der mangler noget. Så det kan ikke anbefales.

I nogle tilfælde vil man som fx svagtseende muligvis stadig bruge musen til at navigere på siden, men stadig bruge skærmlæser. Man vil derfor kunne aktivere datepicker, men den ville ikke kunne læses op.

Hvis I finder et datepicker plugin som er fuldt tilgængeligt (også med en skærmlæser aktiveret) og lever op til kravet om tilgængelighed, så er det som altid tilladt at bruge det. I må gerne fortælle os, hvis I finder et tilgængeligt plugin. Uanset hvilket plugin I anvender, skal det blot matche FDS visuelle udtryk. 

Vi vil, grundet det manglende svar fra tredjepart, som du så rigtigt gør opmærksom på, og de generelle problemer vi oplever med tilgængelighed i de plugins vi peger på, overveje hvorvidt vi skal deprecate nogle eller alle, og afholde os fra at pege på og vejlede i integration plugins på FDS. Det tager vi op i FDS regi snarligt.

Desværre løser det ikke jeres problem med Pikaday plugin'et. Vi har ikke kunnet finde et tilgængeligt alternativ, og da de fællesoffentlige krav kræver overholdelse af WCAG 2.1 på AA-niveau, har vi på nuværende tidspunkt ikke noget alternativt løsningsforslag til den funktionalitet Pikaday leverer. Beklager. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
