### ISSUE TITLE
manglende afstand mellem tags

### ISSUE THREAD

**Issue by martinhoegh** [detfaellesdesignsystem/dkfds-components#11]
**Bekskriv fejlen (Describe the bug)**
Tags fungerer uhensigtsmæssigt på små skærme. Der er ingen afstand mellem elementerne

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Gå til https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tags/ med et browservindue på mindste breakpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/1236160/53227776-89abe080-367f-11e9-8928-5f76288f52f6.png)

**Sådan burde det fungere (Expected behavior)**
Der bør være afstand mellem elementerne. På breakpoint kan man evt tilføje noget a la:
.tag + .tag {
    margin-top: 5px;
}
![image](https://user-images.githubusercontent.com/1236160/53228058-5289ff00-3680-11e9-846d-b15c0cc56317.png)

**Comment by detfaellesdesignsystem** [comment]
@martinhoegh tak. Jeg har oprettet fejlen i backloggen.

**Comment by detfaellesdesignsystem** [comment]
Hej @martinhoegh,

Tak for din henvendelse.

Fikset vil være med i næste release af dkfds.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
@martinhoegh jeg lukker dette issue, da det er fikset. Mvh Sune
