### ISSUE TITLE
Plus tegn på Accordion knap i IE vises ikke

### ISSUE THREAD

**Issue by hahenetcompany** [detfaellesdesignsystem/dkfds-components#110]
**Bekskriv fejlen (Describe the bug)**
I Tilbudsportalen har vi trin der har accordionknapper.
Knapperne skal skifte til at ha et minustegn icon til et plustegn icon når de er lukkede og åbne.
I internet explorer ser det ud som at ved ankomst til trinnet, så bliver ikke plus-tegn sat på når man lukker en accordion (Det skal tilføjes at accordion-knappen er forced åbn ved ankomst af os fordi kunden gerne vil ha det). 
Der er vedhæftet billeder som viser problemet. Det ser ud som at URL til ikonen ændres når man lukker accordionknappen. Hvis jeg ændrer url til hvad det burde være så vises ikonen fint. 

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
Brug Internet explorer.
1. Gå til https://dev.tilbudsportalen.dk/tilbudsregistrering/vaerdigrundlag/index?sagsnummer=X20-AA-35-WU&subTrinId=
3. Logge ind som Fåborg-Midtfyn kommune administrator - (ERST-GDPR)
4. Gå til trin 4 (Værdigrundlag og Målsætning)
5. I botten af siden findes accordionknapper. Når man lukker dem så kommer ikke plustegn på. 

Hvis det IKKE kan reproduceres på linken, så gå til fanen "Indberet tilbud" , vælg et Tilbud der står som oprettet og tryk **gå til tilbud**, tryk sen på **Start indberetning** og gå til trin 4. værdigrundlag og målsætning. 

**Screenshots**
Tilføj om muligt et eller flere billeder der viser fejlen. (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/65391243/82025671-f26ee680-9691-11ea-97b5-ec2f6441edb9.png)
![image](https://user-images.githubusercontent.com/65391243/82025766-0dd9f180-9692-11ea-8dcd-4b3c1a570029.png)
![image](https://user-images.githubusercontent.com/65391243/82025783-13373c00-9692-11ea-9885-3d6e96d25017.png)

**Sådan burde det fungere (Expected behavior)**
Plus tegn kommer på når man lukker accordion. 

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows
 - Browser Internet explorer 
 - Version 11

**Comment by detfaellesdesignsystem** [comment]
Hej @hahenetcompany,

Det ser ud til at det er en IE fejl med rendering af baggrundsbilleder - muligvis specifikt SVGer. Jeg har ikke kunne reproducere det i vores eget miljø, men fik det frem I jeres et par gange. Men fejlen virker til kun at dukke op nogle gange, hvor andre gange virker det fint.

Vi kan prøve at ændre referencen til billedet, så det er en inline data URI i stedet for en specifik svg fil. Jeg vil lige undersøge muligheden for at få ændringen med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
