### ISSUE TITLE
Tab til skip-link og topmenu virker ikke i Safari og Firefox på MAc

### ISSUE THREAD

**Issue by ThomasNEB** [detfaellesdesignsystem/dkfds-components#111]
**Bekskriv fejlen (Describe the bug)**
Hvis jeg står i url feltet og tabber forventer jeg først at tabbe forbi skip-link og bagefter igennem top-menuen. Dette virker i Chrome, men hverken for Safari eller Firefox på Mac.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):

1. Åben Firefox/Safari
2. Gå til https://designsystem.dk/
3. Tryk Tab på keyboardet

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: iOS
 - Browser Safari/Firefox
 - Version 13.1/76.0.1 (64-bit)

**Comment by detfaellesdesignsystem** [comment]
Hej @ThomasNEB.

Tak for din henvendelse!

Jeg har oprettet en sag i vores backlog, og vil vende tilbage når vi har kigget på sagen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @ThomasNEB,

Vi har kigget på sagen, og har ikke kunne reproducere fejlen i Safari. Hvis du fortsat oplever dette problem må du meget gerne genåbne sagen.

I Firefox på mac kan man ikke tabbe til links pr. default - man skal ændre i preferencerne i firefox for at ændre dette. Se evt. https://support.mozilla.org/en-US/questions/1278793 for mere info.

Jeg lukker sagen for nu, men hvis du har yderligere spørgsmål eller fortsat oplever dette issue er du velkommen til at genåbne sagen eller oprette et nyt issue.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
