### ISSUE TITLE
radio buttons i print

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#112]
Hej FDS

Vi har nogle udfordringer ved brug af radio buttons i print. Når vi printer i Explorer og Edge kan man ikke se den valgte værdi på trods af at man har valgt en radio button. Det kan man til gengæld i Chrome og Firefox. 

Fejlen kan genskabes på jeres side her: https://designsystem.dk/komponenter/radioknap/

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Tak for henvendelsen. Jeg har oprettet en sag på det og vi vil kigge på det snarest muligt.

Jeg vender tilbage, når jeg ved nærmere om, hvornår vi kan komme med et fix.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Vi har fikset fejlen og den vil komme med i næste release.

Jeg lukker derfor sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
