### ISSUE TITLE
extracompact i tabeller

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#113]
Hej FDS

Når man benytter sig af klassen table--extracompact så er der ekstra meget plads i den sidste td i tabellen. Jeg går ud fra at dette er en fejl i stylingen?
![image](https://user-images.githubusercontent.com/54143827/85008873-dca38400-b15d-11ea-83fc-07279203e69e.png)

Mvh. Josephine - ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Tak for din henvendelse!

Jeg har oprettet en sag i backloggen og vender tilbage når vi har noget nyt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Fix er implementeret i version 7.2.0

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
