### ISSUE TITLE
"Tilbage links" + trinindikator

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#115]
Hej FDS,
Vi har en selvbetjeningløsning, hvor vi bliver nødt til at bruge trinindikatoren på venstre side. 
Der kan forekomme mange felter i et trin - og brugeren bliver derfor nødt til at scrolle ned på siden for at tage stilling til de oplysninger, der skal angives - og hvis alt er ok klikker brugeren på "Næste" knap for at komme videre til næste trin - ellers "tilbage" for at komme tilbage til forrige trin (man kan i også komme tilbage til forrige trin vha. trinindikatoren).

Vi udsætter brugeren for unødig scroll til toppen, hvis vi placerer et "tilbage link" på toppen af hvert trin, som I anbefaler.

Vil gerne høre, hvad jeres overvejelser har været ift. sådan en selvbetjeningløsning som vores og "tilbage link" på toppen af hvert trin. 
Vh.
Farzana
![image](https://user-images.githubusercontent.com/48348000/90770683-71f3fd80-e2f2-11ea-9781-98daa9e43471.png)

**Comment by FNA-atp** [comment]
Hej Sune,
Tak for hurtig tilbagemelding 👍 
Den med kvittering har jeg på min to-do liste (har spurgt om det tidligere herinde :-) )
Realiteten er, at denne løsning er ret kompleks med mange trins og hvert trin kan indeholde mange felter, som er venstre opstillet. 
Der er ikke sat budget og ressource til at forenkle hvert trin – og usabilityteste løsningen engang til.
Begge muligheder (trinindikatoren + tilbage linket) for at ”gå tilbage” er placeret på toppen af siden – og det er ærgerligt, at brugeren skal scrolle så langt op for at kunne klikke på ”gå tilbage”. Vi synes, den blå primærknap står tydeligt i bunden selvom, der er en tilbage knap/link.
![image](https://user-images.githubusercontent.com/48348000/91012826-08703980-e5e7-11ea-9647-c0fb97e171cf.png)

Vi følger dog stadig jeres anbefaling – men ville lige også ”lufte” vores bekymring – at placering for ”tilbage-link” er ikke god til trins med meget indhold  :-)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Det er noteret. Jeg laver en story på det, der skal undersøge om FDS her bør bryde med GDS. Tak for feedbacken.

Mvh
Sune
FDS

**Comment by FNA-atp** [comment]
Hej igen,
Lige en update til denne - vi er nu stødt på nedenstående problem, hvor vi på en side har både en trinindikator og brødkrumme. Hvis "tilbage" knappen også tilføjes på toppen, ville det forvirre brugeren med så mange interaktioner på samme sted/spot. Håber I kan tage denne også med i jeres overvejelser, når I får tid til at kigge på dette issue ;-)

![image](https://user-images.githubusercontent.com/48348000/122006354-04e8b180-cdb7-11eb-873e-54ddbe3bdd6e.png)

Vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Kære Farzana,

Vi anbefaler ikke at benytte brødkrumme-komponenten sammen med hverken trinindikator eller tilbage-link. Læs mere: https://designsystem.dk/komponenter/broedkrumme/
Brødkrummen og trinindikatoren har efter vores opfattelse samme funktion. 
Vi anbefaler fortsat at lægge tilbage-linket i toppen, da vi følger anbefalinger fra GDS. Vi overvejer dog at brugerteste placeringen og i samme omgang teste et tilbage-til-toppen-link. Vi vender tilbage med nyt i sagen.

Bh 
Camilla
FDS

**Comment by FNA-atp** [comment]
Hej Camilla,
Tak for svar :-) vi har en lidt unik situation med denne selvbetjening. Fordi "Overblik" siden fremgår ikke på menuen - fordi det er en separat selvbetjeningsløsning. Jeg undersøger det lige nærmere, kunne være vi kunne lave en lille "hack" i koden, så vi kan linke til siden fra topmenuen :-)

Det lyder godt med "tilbage-til-top" knappen :-)

Tak :-)
