### ISSUE TITLE
Responsiv headers tabel mangler data-title på td

### ISSUE THREAD

**Issue by DkVagabonden** [detfaellesdesignsystem/dkfds-components#12]
**Bekskriv fejlen (Describe the bug)**
Fejlen er i kode eksempel på [dokumentation siden](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tables/). Under **Responsiv** -> **Responsive headers**.
Eksempel koden mangler at få tilføjet data-title på td. 

PS. Bruger ikke javascript e.l, hvis data-title attr bliver tilføjet via javascript e.l anbefaler jeg at der gøres opmærksom på det i dokumentationen.

**Genskab fejlen (To Reproduce)**
1. Kopier eksempel koden for Responsive headers tabellen
2. Prøv at få vist koden via mobil e.l
3. Der mangler titler på alle td.

**Indsæt link (Add a URL)**
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tables/

**Screenshots**

**Sådan burde det fungere (Expected behavior)**

Tilføjet data-title til td.

```
<div class="container pt-6">
    <p class="h5">Responsive headers</p>
    <p>Add .table--responsive-headers class to table</p>
    <table class="table table--borderless table--responsive-headers">
        <thead>
        <tr>
            <th>Affaldstype</th>
            <th>Farvekode</th>
            <th>Beskrivelse</th>
            <th>Hvor ender det?</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td data-title="Affaldstype">Dagrenovation</td>
            <td data-title="Farvekode">Grøn</td>
            <td data-title="Beskrivelse">Madaffald, samt papir, pap eller plastik der ikke kan
                    genanvendes, fordi der er madrester eller andet snask
                    på.</td>
            <td data-title="Hvor ender det?">Alt det affald, du smider ud i din primære
                    skraldespand, som er dagrenovationen, bliver hentet og
                    kørt på forbrændingen. </td>
            </tr>
            <tr>
            <td data-title="Affaldstype">Bioaffald og kompost</td>
            <td data-title="Farvekode">Beige</td>
            <td data-title="Beskrivelse">Alt madaffald uden fødevareemballage.</td>
            <td data-title="Hvor ender det?">Bioaffaldet kommes i bionedbrydelige poser, som bliver
                komposteret til muld.</td>
        </tr>
        <tr>
            <td data-title="Affaldstype">Glas</td>
            <td data-title="Farvekode">Hvid</td>
            <td data-title="Beskrivelse">Alle typer glas og flasker.</td>
            <td data-title="Hvor ender det?">De hele vinflasker rengøres og genbruges af vinhuse,
                mens glasskårene bliver smeltet om til nyt glas.</td>
        </tr>
        <tr>
            <td data-title="Affaldstype">Elektronik</td>
            <td data-title="Farvekode">Orange</td>
            <td data-title="Beskrivelse">Genstande der har brugt strøm.</td>
            <td data-title="Hvor ender det?">Det elektroniske affald bliver typisk kørt til et
                demonteringsanlæg, hvor det bliver skilt ad, så de
                forskellige dele kan genanvendes separat.</td>
        </tr>
        </tbody>
    </table>
</div>

```

**Desktop - udfyld venligst følgende (please complete the following information):**
Windows 10
Chrome 72

**Smartphone - udfyld venligst følgende (please complete the following information):**
Iphone8
iOS12

**Comment by detfaellesdesignsystem** [comment]
Hej @DkVagabonden,

Tak for din henvendelse - og godt fanget!

Vi har oprettet et issue på det og får det fikset hurtigst muligt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @DkVagabonden,

Vi har nu tilføjet beskrivelse af data-title - den bliver netop tilføjet af javascript i dkfds.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by DkVagabonden** [comment]
Hej @detfaellesdesignsystem,

Super! Læste lige Implementering sektionen igennem og i mangler lige et **for** 👍 
 
"data-title attribut bør tilføjes til hver td, således at en label bliver tilføjet **for** hver celle på mindre skærme."
