### ISSUE TITLE
<ol> i accordions

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#120]
Hej FDS.
Efter version 4 kan vi ikke længere lave ol elementer i accordions og det giver os nogle udfordringer. 
de ligner ul elementer og når man tilføjer styling så opfører den sig ikke som forventet.
Er det noget I kan kigge på?
mvh. Josephine - ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Der vil være et fix med i næste release. Jeg vil lige opdatere sagen her når jeg har en nærmere bestemt dato.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Fix implementeret i version 7.2.0
