### ISSUE TITLE
Fokus skifter ikke ved brug af DKDFS.init()

### ISSUE THREAD

**Issue by cncnetcompany** [detfaellesdesignsystem/dkfds-components#121]
**Bekskriv fejlen (Describe the bug)**
At Prøvemateriale we are using the DKFDS javascript to have a fully responsible page.
Our problem is that when doing this, the focus of the page when a component gets re-rendered changes to the first component of the page, instead of staying on the last clicked button.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
https://proevebanken.lu.dnt.stil.dk/
1. Click til "Prøvematerialer" i navigations menu
2. Click til "Folkeskolens prøver"
3. Click til "Matematik".
4. Click til "Matematik FP10".
4. Se at fokus altid peger på Biologi (Den første fag af venstre menuen)

**Indsæt link (Add a URL)**
https://proevebanken.lu.dnt.stil.dk/

**Screenshots**
![image](https://user-images.githubusercontent.com/72383877/96873410-305c0c00-1475-11eb-93cd-30c7acfc7031.png)

**Sådan burde det fungere (Expected behavior)**
Beskriv om muligt, hvordan fejlen løses eller beskriv klart og præcist hvordan det burde fungere. (A clear and concise description of what you expected to happen.)
Fokus skulle blive på den sidste clicked knap.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - Browser Chrome
 - Version Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by DKFDSdevelop** [comment]
Hej @cncnetcompany,

Tak for henvendelsen!

Det lyder som et issue der kan opstå ved gentagen kald til DKFDS.init() på samme side. Hvis der er områder, som bliver opdateret med nye komponenter kan du prøve at kalde de javascript kald for de nødvendige komponenter, frem for at bruge DKFDS.init().

Information om javascript komponenterne ses under Kode siden for hver komponent.

Du må meget gerne melde tilbage om ovenstående løser problemet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cncnetcompany,

Tak for henvendelsen!

Det lyder som et issue der kan opstå ved gentagen kald til DKFDS.init() på samme side. Hvis der er områder, som bliver opdateret med nye komponenter kan du prøve at kalde de javascript kald for de nødvendige komponenter, frem for at bruge DKFDS.init().

Information om javascript komponenterne ses under Kode siden for hver komponent.

Du må meget gerne melde tilbage om ovenstående løser problemet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
