### ISSUE TITLE
Eksempel med venstremenu (med undersider uden anchor-links)

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#123]
Hej FDS,
Vi savner et eksempel på en selvbetjeningsløsning med venstremenu. Menuen må godt indeholde undersider uden anchor-links, som FDS hjemmeside bruger.
Nedenstående eksempel er godt, men vi savner at se, hvordan menuen (med undersider) opfører sig på mobil :-)
https://designsystem.dk/eksempel/sidenav-normal-level2/

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for henvendelsen!

Generelt bliver sidenavigationen ikke vist på mobil. Man bør i stedet lave en version af menuen i headeren, som kun fremgår på mindre skærme/mindre skærme, hvor der ved brug af overflow menuer vises underpunkter. Designsystem.dk er et ret godt eksempel på denne brug, da vi på desktop ikke viser underpunkter i menuen i headeren.

Eksempel på mobilmenuen med underpunkter, som også vises :
![image](https://user-images.githubusercontent.com/44367338/99246675-02fd4680-2806-11eb-819a-06c6c346bee0.png)

Screenshot af kodeksempel af de 2 menuer i headeren til henholdsvis desktop og mobil:
![image](https://user-images.githubusercontent.com/44367338/99246806-2fb15e00-2806-11eb-80be-cc4fe4b96919.png)

Sig endelig til, hvis der er spørgsmål til ovenstående.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
ja, den er blevet bygget på samme måde her - men hvis du ser på mit eksempel herunder; så har jeg 2 undersider i desktop - men 3 undersider på mobilmenu - fordi "Parent" til undersiderne skal man også kunne klikke på. 
Det kan godt skabe "forvirring" hos brugerne, , at der lige pludselig er en ekstra underside på mobil. 

Det kan godt være, det kan løses ved at man ikke skulle tilføje "collapse" funktion, når menuen er ikke lang og man ikke har så mange undersider. 
![image](https://user-images.githubusercontent.com/48348000/99255438-38a92c00-2814-11eb-8efb-86da7291a3ee.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Jeg har oprettet en sag omkring dette til vores UX'er. Vi vender lige tilbage, når vi har noget nyt i sagen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej FZA-atp

Vi har forbedret designet til vores menu på mobil, så undermenuer bliver lettere tilgængelige. Det nye design kommer med i næste release, hvor I vil kunne se designet i vores egen navigation på designsystem.dk.

Du er velkommen til at genåbne denne tråd, hvis der opstår spørgsmål efter det nye design bliver releaset.

Venlig hilsen
Mette Boldt
Det Fælles Designsystem
