### ISSUE TITLE
Understøttelse af <input type="number"

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#124]
Hej

Er der i Designsystem åbnet op for at benytte `<input type="number"`?

Jeg kan kun se eksempler som benytter `<input type="text"`

Jeg er selv i tvivl om hvorvidt det vil være hensigtsmæssig at benytte input number som et beløbsfelt.

Hvad tænker I?

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Tak for din henvendelse!

Umiddelbart nej, da sagen endnu ligger i vores backlog at vi skal lave eksempler på brug af felter til andet end tekst. Men da vi som regel ligger os op af Gov.UK Design System og USWDS (US Web Design System), så kan du tage et kig på, hvad de foreslår.

GDS skriver blandt andet at man bør undgå brug af input af typen number, da brugeren ved en fejl kan ændre værdien ved diverse genvejstaster, og når de ændrer det vil de, som bruger hjælpeteknologier ikke få besked om dette.
(https://design-system.service.gov.uk/components/text-input/#avoid-using-inputs-with-a-type-of-number)

Umiddelbart vil jeg derfor anbefale på den baggrund af bruge et almindeligt tekstfelt som GDS eksemplet her: https://design-system.service.gov.uk/components/text-input/#text-inputs-with-a-prefix
FDS har på nuværende tidspunkt dog ikke samme design med prefix, men jeg tager det op med teamet om det er noget vi skal implementere.

Sig endelig til, hvis du har yderligere spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
Hej Kristina,

tak for svar. Jeg synes også det giver mening. Beløbsfelterne er altid en særlig udfordring, da det er fristende som udvikler at tænke dem som "bare et tal".

I virkeligheden kan brugere fx copy-paste beløb med tusindtalseparator, eller paste fra PDF/Word som kan indeholde mellemrum og sommetider "skubbe" betydende cifre den ene eller anden vej.

Jeg vil foreslå at I kan tage dette op som et separat emne på et tidspunkt. 

Som et lille kuriosum (og i øvrigt urelateret til mit spørgsmål) kan jeg se at SKAT benytter number feltet til deres formular for betaling af restskat:

<img width="502" alt="Skat_dk_version_205_-_spname_notran__Frivillig_betaling_af_restskat_-_www_skat_dk_dk_skat_aspx_oid_restskat_and_TastSelv_-_Betal_skat" src="https://user-images.githubusercontent.com/6267/106248887-ed4acb00-6211-11eb-8a76-82cf6bb1c7f6.png">

Hvilket i så fald er imod anbefalingerne herfra. 

Jeg har intet med SKAT at gøre, og er i øvrigt 100% enig i dine observationer og konklusionen om at benytte alm. tekstfelt og ikke number :)
