### ISSUE TITLE
Escape på åben overflow i åben modal lukker både overflow OG modal

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#125]
Hvis man har en modal, der indeholder en overflowmenu og både modalen OG overflowmenuen er åbne, så lukker begge dele, når man trykker på Escape.

Hvordan sikrer jeg, at det kun er den senest åbnede komponent, der lukkes, når jeg trykker på Escape?

Jeg har behovet, når jeg i en modal ønsker at vise en tabel med en overflow menu for hver række.

DKFDS v7.1.1

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for din henvendelse!

Det er på nuværende tidspunkt desværre ikke muligt at gøre som du skriver. Jeg har lagt sagen i backloggen og vi vil kigge på at løse det i et af de nærmeste sprints.

Jeg giver lige besked, når jeg ved nærmere.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing 

Der vil komme et fix i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
