### ISSUE TITLE
(Hjælpe)modal åbnet fra en anden modal indsætter endnu en backdrop

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#126]
DKFDS v7.1.1

Hvis jeg åbner en modal fx med en formular til indtastning af data og jeg i denne modal har mulighed for at åbne endnu en modal med hjælp til felterne i formularen, så indsætter modal #2 endnu en

`<div class="modal-backdrop" id="modal-backdrop"></div>`

i DOM'en så der nu er to. Lukker jeg så modal #2, så bliver begge backdrops fjernet og den oprindelige baggrund, der var dækket af modal #1 kan nu tilgås.

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for din henvendelse.

Jeg mener ikke der er taget forbehold for mere end én åben modal. Jeg har lagt sagen i backloggen og vil vende tilbage, når der er nyt i sagen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by Camnie1** [comment]
Hej @cjessing 
 
Vi har valgt ikke at understøtte modaler inden i modaler, da det giver en dårlig brugeroplevelse. Brugeren kan opleve at miste fornemmelsen af, hvor de er.
Modaler skal generelt bruges med varsomhed, da det af brugeren kan opleves som forstyrrende.  
At lægge en formular inde i en modal, vil vi ikke anbefale. I stedet kunne man lave en ekstra side til den del af formularen, I påtænker at lægge i modalen.
Vi foreslår samtidig at der arbejdes med kontekstnær hjælp (i stedet for at åbne modal med hjælp) ved formularelementerne som f.eks. 
•	hjælpetekster under en label (for hjælpetekster, der er afgørende for brugernes forståelse)
•	ikon med tooltip/popover ved siden af feltet, med hjælp til brugeren (for uddybende hjælpetekster, der kan være til gavn).

Sig endelig til, hvis du har yderligere spørgsmål.

Med venlig hilsen
Camilla B. Nielsen
Det Fælles Designsystem
