### ISSUE TITLE
Mangler softwarelicens

### ISSUE THREAD

**Issue by agger-magenta** [detfaellesdesignsystem/dkfds-components#128]
**Der er ikke nogen licens for denne kode**

Kode er kun FOSS (fri/open source software), hvis der er en OSI-godkendt licens, der specificerer, hvordan den må anvendes.

I princippet fremgår det ikke, at man har ret til at genanvende, ændre eller videredistribuere koden, som den findes her, eller under hvilke betingelser.

Til et projekt med dette scope ville jeg foreslå en permissiv/2-clause BSD-licens i stil med det her, som i givet fald skulle lægges i en LICENSE-fil:

https://github.com/baskerville/bspwm/blob/master/LICENSE

**Comment by detfaellesdesignsystem** [comment]
Hej @agger-magenta,

Tak for din henvendelse.

Vi har manglende licens oppe at vende i FDS teamet i øjeblikket, men der er ikke foretaget en endelig beslutning. Jeg vil tage din kommentar med til FDS-teamet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by agger-magenta** [comment]
Tak for svaret! Linket til den foreslåede licens blev i første omgang forkert takket være lidt for mange åbne Github-tabs, men jeg har rettet det.

**Comment by detfaellesdesignsystem** [comment]
Hej @agger-magenta 

Valget faldt på MIT license. Se mere her: https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/LICENSE.md

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by agger-magenta** [comment]
Perfekt, tak!
