### ISSUE TITLE
modal-xl for datatunge modal vinduer

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#129]
Vi har haft behov for at implementere et bredere modal vindue til brug for en sagsbehandler-vendt løsning hvor data skal detailbehandles i en modal.

Jeg bed mærke i at bootstrap 3 og 4 har `modal-lg`/`modal-xl` css klasser, men DKFDS minder mere om bootstrap 2 der sjovt nok ikke havde implementeret størrelser på modalvinduer.

Har I nogle generelle holdninger til store modalvinduer?

Hvis I synes det ligger indenfor jeres rammer og anbefalinger, så kan jeg foreslå følgende implementering:

```
@media (min-width: 992px) {
    .fds-modal-xl > .modal-content {
        max-width:800px;
    }
}

@media (min-width: 1200px) {
    .fds-modal-xl > .modal-content {
        max-width:1340px;
        width: 95vw;
    }
}
```

eller lignende. (det meste er lånt fra bootstrap 4.6, men `width` er muligvis påkrævet på grund af andre regler i DKFDS i dag.

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Tak for din henvendelse!

Vi tager det lige op i FDS-teamet og vender tilbage til dig.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn, 

Vi har ikke planer om at udvide med en XL modalvindue. Som udgangspunkt skal brugen af modalvinduer begrænses og skal ikke erstatte individuelle sider i en løsning. 

Ud fra din henvendelse læser vi ,at brugeren skal interagere med indhold/behandle data i modalvinduet. Ville det være muligt at lægge indholdet på en ekstra side i løsningen i stedet?

Vi vil meget gerne se skærmshots/mock-ups af løsningen, hvis vi skal komme det nærmere :).

Med venlig hilsen
Camilla B. Nielsen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Vi lukker sagen, men du er velkommen til at åbne den igen, hvis der er yderligere spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
Tak for tilbagemelding. Jeg er helt indforstået med at denne brug af en modal ligger udenfor de anbefalede rammer af Designsystem

> Ud fra din henvendelse læser vi ,at brugeren skal interagere med indhold/behandle data i modalvinduet. Ville det være muligt at lægge indholdet på en ekstra side i løsningen i stedet?

Ja det kan man godt forestille sig. Den specifikke side er dog til brug for sagsbehandlere (uddannede brugere). Modalen giver mest mening for at bevare kontext med bagvedliggende indhold. Derfor mener jeg det er fint nok at vi bibeholder en implementering med xl-modal, men at jeres anbefaling er en separat side.

> Vi vil meget gerne se skærmshots/mock-ups af løsningen, hvis vi skal komme det nærmere :).

Vi er OK for nu, men jeg kan spørge product owner senere hvis det kommer på tale om jeg kan dele mere specifikke detaljer.
