### ISSUE TITLE
Giv select samme højde på alle form elementer, på tværs af browsere

### ISSUE THREAD

**Issue by postergaard** [detfaellesdesignsystem/dkfds-components#13]
**Navn i designsystemet (Feature name in the design system)**
Formular-elementer (text og select)

**Link til det der skal opdateres (URL to what needs to be updated)**
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Vi har en select og et text input felt, som er sidestillet, det ser fint uf i chrome, men i firefox og IE er select større end text. (se vedhæftet dokument)

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Højden (height) på select og text input elementer

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**

**Supplerende bemærkninger (Additional context)**
[browsereksempler.pdf](https://github.com/detfaellesdesignsystem/dkfds-components/files/2956348/browsereksempler.pdf)

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Tak for din henvendelse.

Vi har oprettet en sag på det, og vil vende tilbage så snart vi har kigget på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Har I enstatus på denne?

**Comment by detfaellesdesignsystem** [comment]
Den ligger i indeværende sprint, som lige er gået i gang.

**Comment by postergaard** [comment]
Super

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Vi har fikset fejlen nu. Fikset vil være med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Tak
