### ISSUE TITLE
Uanvendte dependencies bør fjernes

### ISSUE THREAD

**Issue by chce** [detfaellesdesignsystem/dkfds-components#130]
**Skyldes dit forslag et særligt behov eller et problem? Beskriv venligst. (Is your feature request related to a certain need or problem? Please describe.)**
Ved at analysere mit projekts dependencies, kan jeg se, at jeg får pakket 72kb(efter minificering og gzip) Moment-kode med ned når jeg bygger det. Det ser ud til at det kun er dkfds-components og dkfds-plugins der har dependencies til moment-biblioteket. Jeg kan dog ikke se, med en simpel søgning på repositoriet gennem Githubs søgefunktion, hvad dette bibliotek anvendes til - Der er vist ingen referencer til det i koden. Det samme gør sig vist også gældende for jeres lodash.debounce-dependency

**Beskriv det du gerne ser tilføjet til designsystemet (Describe the solution you'd like to add to the design system)**
Hvis moment og lodash.debounce ikke er nødvendige, bør de fjernes fra pakkens dependencies.
Taget fra Moment's github side: "Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library."

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
Ingen.

**Links til eksempler. (URLs with examples)**
https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/package.json
https://github.com/detfaellesdesignsystem/dkfds-plugins/blob/064440ac1bfc723bc1d220bc360de33bdb00edf0/package.json

**Comment by detfaellesdesignsystem** [comment]
Hej @chce,

Tak for din henvendelse!

Vi tager lige et kig og vil naturligvis fjerne unødvendige dependencies.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @chce,

Der er kørt en oprydning i dependencies i nyeste release af dkfds. [Version 7.3.0](https://github.com/detfaellesdesignsystem/dkfds-components/releases/tag/7.3.0) bør derved være lidt lettere.

Bemærk at dkfds-plugins ikke længere supporteres eller opdateres.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
