### ISSUE TITLE
Google Chrome melder "deprecated" kode

### ISSUE THREAD

**Issue by stil-sds** [detfaellesdesignsystem/dkfds-components#131]
Ifølge Google Chrome er følgende kode deprecated og det genererer en advarsel i Developer:
-webkit-details-marker{display:none}.details[open] 

https://chromestatus.com/feature/6730096436051968

**Comment by detfaellesdesignsystem** [comment]
Hej @stil-sds,

Tak for henvendelsen!

Der er oprettet en sag på det. Vi vender tilbage, når der er nyt i sagen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by stil-sds** [comment]
Super!

Bh

John

**Comment by detfaellesdesignsystem** [comment]
Hej John,

Vi kan desværre ikke implementere ændringen alligevel, da Safari desværre halter efter på dette punkt. Vi er derfor nødt til at have -webkit-details-marker lidt endnu.

Det ser ud til at de i Chrome muligvis trækker deprecation beskeden tilbage her:
https://bugs.chromium.org/p/chromium/issues/detail?id=1189809

Yderligere er der en sag i hos Lighthouse, der omtaler sagen her: https://github.com/GoogleChrome/lighthouse/issues/12089

Vi vil holde øje med dette issue og implementere et fix, når der er en bedre løsning på tværs af browsere.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by stil-sds** [comment]
Hej Kristina

Tak for orientering! Det er da lidt noget rod, de har gang i. Men nu ved vi, der er noget i gære :)

Bh

John
