### ISSUE TITLE
Spørgsmål til række 4 i "Kompleks header med alle rækker"

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#133]
Hej FDS,
Vi er lidt i tvivl om række 4 kan indeholde alm. menupunkter, som det er vist på billedet herunder. 

![image](https://user-images.githubusercontent.com/48348000/111292738-c96c0900-8648-11eb-804a-57e76e32f186.png)

I vores eksempel er række 4 undermenupunkter for et menupunkt i række 3.

![image](https://user-images.githubusercontent.com/48348000/111291426-79d90d80-8647-11eb-8395-f1c35b2506b3.png)

Jeres eksempel viser kun en "Overflow menu" på række 4 - er rækken kun tiltænkt til Overflow-menuer?
![image](https://user-images.githubusercontent.com/48348000/111291729-c3c1f380-8647-11eb-84e0-79b0c1376be6.png)

vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for din henvendelse!

Vi kigger lige på det og vender tilbage.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

En kort status:
Vores UX'ere vil gerne lige kigge på række 4 i headeren igen, så den kan blive nærmere specificeret og eksemplerne for headeren med række 4 lidt mere sigende.

Jeg kan desværre ikke give en tidshorisont endnu, men ryk gerne for det hvis det er presserende.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi lukker tråden her, da der ikke er komment flere kommentarer. Der blev releaset en ny header i version 10.0.0, hvor række 4 ikke længere findes.
