### ISSUE TITLE
Brug af top-og venstremneu i en selvbetjeningsløsning

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#134]
Hej FDS,
Er det "lovligt" at benytte både en top og venstremenu på en selvbetjeningsløsning (uden flow el. trinindikator) - ligesom på jeres hjemmesiden https://designsystem.dk/ :-)

![image](https://user-images.githubusercontent.com/48348000/111312534-adc02d00-865f-11eb-99db-40c4de7e11b3.png)

Vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Vi vender det lige i teamet og vender tilbage.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by Camnie1** [comment]
Hej Farzana @FNA-atp 

Kan du forklare lidt mere om i hvilke scenarie, du tænker på? 
Er det en oversigt? Hvis du har noget visuelt, vil det være en stor hjælp.

I en selvbetjeningsløsning med forløb er en trinindikation vigtig så brugeren har overblik over hvad der kommer, hvor langt man er i forløbet og giver mulighed for at gå tilbage i løsningen.

Med venlig hilsen
Camilla B. Nielsen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Camilla,
Der er tale om en selvbetjeningsløsning uden trinindikator :-) Jeg har vedhæftet et billede. 
![image](https://user-images.githubusercontent.com/48348000/111619355-c0646e80-87e5-11eb-8dbf-f81436b4305c.png)

**Comment by Camnie1** [comment]
Hej Farzana, :)

Ja, så det er mere en oversigt, hvor brugeren kan se noget data?

Jeg er også lige ved at skrive noget til issue133 - som hænger sammen med denne, kan jeg se. 
Vi ville nemlig også anbefale at ændre ekstra menuen du havde på issue133 til en sidenavigation som du har gjort her. Har du overvejet at fjerne drop-down i primær menu og lave sidenavigationen med undermenupunkter?

Primær menu skal der så bare stå Årsopgørelse

Årsopgørelse 2018
Årsopgørelse 2019 (er der en anden overskrift dækker alle 3 undermenupunkter?)
    Årsopgørelse 2019 (tænker ikke den skal være der to gange)
    Elevopgørelse 2019
    Erhvervsuddannede medarbejdere 2019
Årsopgørelse 2020
Årsopgørelse 2021

Med venlig hilsen
Camilla B. Nielsen

**Comment by FNA-atp** [comment]
Hej Camilla, 
Kan vi tale sammen over Teams, så kan jeg vise dig løsningen :-)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

For at svare på det oprindelige spørgsmål må man gerne have en navigation i header og en sidenavigation, som på designsystem.dk.

Sidenavigationen ses i det tilfælde ikke som en trinindikator, men en almindelig undermenu til det hovedområde man har valgt i headerens navigation.

Hvis man har brug for hele bredden af siden, og derved ikke kan bruge sidenavigationen kan man evt. bruge række 4 i headeren. Men som nævnt i #133 vil Camilla og Mette lige genbesøge række 4 i headeren for at se om det er noget vi reelt bør anbefale, og hvordan det i så fald bør foregå.

Hvis du har brug for mere sparring i forhold til dit konkrete eksempel, så meld endelig tilbage.

Da det oprindelige spørgsmål er besvaret og resten afventer vurderingen omkring række 4, som #133 omhandler, vil jeg derfor lukke dette issue.

Genåbn gerne, hvis der er flere spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
