### ISSUE TITLE
Menupunkter - række 4 i headeren

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#135]
Hej FDS,
Vi synes menupunkterne på række 4 i headeren trænger lidt css-tryllestøv,  så punkterne ligner mere menupunkter i stedet for alm. links :-) 
![image](https://user-images.githubusercontent.com/48348000/111996670-90390a80-8b1a-11eb-9941-d430ddb58cbf.png)

Herunder et par forslag til små ændringer på rækken:
![image](https://user-images.githubusercontent.com/48348000/111996715-97f8af00-8b1a-11eb-8cff-12097758530f.png)

Mvh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for henvendelsen - og forslaget. Som nævnt i #133 vil vores UXere lige genbesøge række 4 i headeren.

Issue #133 handler om det samme, så jeg tillader mig at lukke denne, så status kun skal gives ét sted. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by MartanErst** [comment]
Hej @FNA-atp,
Tak for henvendelsen. Du har ret. Række 4 trængte til lidt CSS tryllestøv.
Vi har haft række 4 oppe til revision, og besluttet at fremtidige versioner af Det Fælles Designsystem ikke kommer til at understøtte den nuværende række 4. 
Konkret i forhold til den nævnte problematik i issue 133, ser jeg forskellige løsningsmuligheder.
Du kan anvende drop downmenu eller sidenavigation som du selv har beskrevet. En tredje mulighed kunne være en tab-menu på siden, hvis indholdet er tæt nok relateret.

Med venlig hilsen
Martin Andersen
Det Fælles Designsystem
