### ISSUE TITLE
"Detaljer" komponent uden javascript

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#136]
Jeg bemærker at i skriver detaljer komponenten kræver javascript, se https://designsystem.dk/kode/komponenter/detaljer/

hvorfor egentlig det? 

Jeg pønser på at implementere helt ordinære  `<details>` og `<summary>` elementer i stedet for den ekstra markup I foreslår. 

Som jeg ser det forstås `<details>` og `<summary>` vist af alle moderne browsere. 

Måske er der noget jeg overser?

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Du har helt ret, details vil fungere uden javascript i de nyere browsere. Desværre har Internet Explorer 11 været en del af kravet til browserunderstøttelse, hvilket er årsagen til javascript delen for komponenten.  Vi vender lige emnet sammen med din anden henvendelse når resten er FDS teamet er tilbage fra påskeferie.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Da FDS fremadrettet ikke understøtter Internet Explorer vil js for detaljekomponenten ikke længere være nødvendig.

Vi opdaterer dokumentationen og fjerner js for detaljekomponenten ved næste major release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
