### ISSUE TITLE
Hvor finder jeg browserunderstøttelse for Designsystem komponenter?

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#137]
Hej, jeg leder efter hvilke krav designsystem har til browserunderstøttelse, men kan ikke finde noget? Hvor skal jeg kigge?

Hvad er jeres politik for at opdatere browserunderstøttelse. Hvis nu fx digitaliseringsstyrelsen opdaterer anbefalinger/krav til offentlige selvbetjeningsløsninger?

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn

Tak for din henvendelse.

Vi vender det lige i teamet og vender tilbage. Der vil dog tidligst komme svar i næste uge grundet påskeferien.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
Jeg har fundet følgende reference i dokumentationen. Der er et link fra https://designsystem.dk/krav/ 

> [Se beskrivelser af alle krav og anbefalinger i den fællesoffentlige digitale arkitektur](https://arkitektur.digst.dk/krav-og-anbefalinger-0)

Denne peger så på ["06. Understøttelse af styresystemer og browsere (Fælles aftalt)"](https://arkitektur.digst.dk/06-understoettelse-af-styresystemer-og-browsere-faelles-aftalt)

Mit problem er at der står denne formulering:


> Din løsning skal som minimum kunne anvendes på de 4 browsere og styresystemer, som dine brugere af løsningen hyppigst anvender på stationære enheder henholdsvis 3 mest anvendte browsere og styresystemer på mobile enheder. Minimumsgrænserne er valgt for at omfatte styresystemer og browsere fra de største leverandører på markedet (2019).

Men tingene har skubbet sig siden 2019. Og jeg er mere interesseret i browserversioner end i browsere.

Helt konkret, vil det hjælpe hvis I kan fortælle mig om IE11 skal understøttes i Designsystem til nyudviklede løsninger?

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Du har ret i at det er [krav 6](https://arkitektur.digst.dk/node/707), der definerer browserkravet. FDS skal dække en bred række anvendelsesområder og derved brugere, hvorfor vi så vidt muligt skal supportere flere browsere end, hvad der er nødvendigt for alle selvbetjeningsløsninger, så det kan være en individuel vurdering fra løsningens side, alt efter hvilke browsere brugere af løsningen anvender.

Vi er igang med at høre baglandet om holdningen til understøttelse af Internet Explorer. Jeg kan forstå at Virk/Erhvervsstyrelsen helt har droppet support af browseren. Vi er ved at forhøre os hos borger.dk/Digitaliseringsstyrelsen. Jeg melder lige tilbage, når jeg hører noget.

Jeg forhører mig lige i FDS-teamet om browserversionerne også, og vender tilbage. Da det også er et spørgsmål til de fælles krav kan du også rette [henvendelse om de Fælles krav hos Digitaliseringsstyrelsen]( https://arkitektur.digst.dk/node/758) direkte
Vi vil også undersøge det fra vores side af.

Når vi har noget lidt mere konkret vil vi også opdatere designsystem.dk, så informationen er nemmere at finde frem til.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
> Vi er igang med at høre baglandet om holdningen til understøttelse af Internet Explorer. Jeg kan forstå at Virk/Erhvervsstyrelsen helt har droppet support af browseren. Vi er ved at forhøre os hos borger.dk/Digitaliseringsstyrelsen. Jeg melder lige tilbage, når jeg hører noget.

Tusind tak. Du må meget gerne også sende links til disse beslutninger i det omfang de står som "nyheder" eller lignende dokumentation hos digitaliseringsstyrelsen, virk, borger, osv

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn,

Vi har hørt Virk og borger.dk, hvilke browsere de understøtter og tester i og har ud fra det lavet nedenstående liste.

Virk har følgende kilde: https://myndighedsnet.virk.dk/virk-viden/integration-og-krav/krav-til-loesninger-paa-virk/browsere
borger.dk har desværre ikke en lignende side, så jeg har ingen kilder jeg kan henvise dig til fra deres side af.

Desktop:
- Windows 
	- Chrome
	- Edge
	- Firefox
- Mac 
	- Chrome
	- Safari
	- Firefox
Mobil/Tablet:
- iOS 
	- Safari
	- Chrome
- Android 
	-  Chrome
	- Samsung browser

Ovenstående er alle seneste version af browsere. Vi vil tilføje en ny side under kode sektionen der omhandler browserunderstøttelse.

Listen over hvilke browsere og versioner man bør understøtte kan dog variere fra løsning til løsning. Så det kan være at ovenstående liste ikke dækker de enkelte løsningers behov. I så fald hører vi gerne om det.

Ovenstående liste skal ikke ses som krav eller retningslinjer, men blot oplysning. Det er stadig Krav 6: Understøttelse af styresystemer og browsere fra de fælles krav til digitale løsninger man skal efterleve.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Listen vil blive løbende opdateret på https://designsystem.dk/kode/browserunderstoettelse/
