### ISSUE TITLE
Readonly styling virker ikke i firefox

### ISSUE THREAD

**Issue by postergaard** [detfaellesdesignsystem/dkfds-components#14]
**Bekskriv fejlen (Describe the bug)**
Styling til readonly felter, slår ikke igennem i firefox

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Åben en firefox browser
2. Gå til et readonly felt

**Indsæt link (Add a URL)**
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter 

Mulig løsning
https://www.w3schools.com/cssref/sel_read-only.asp 

**Screenshots**
Her er styling
![image](https://user-images.githubusercontent.com/47414075/54200358-7b592380-44cb-11e9-9752-dba3270914f7.png)

Her virker det (chrome)
![image](https://user-images.githubusercontent.com/47414075/54200578-03d7c400-44cc-11e9-9ad8-6e2966cd0c82.png)

Her virker det ikke (FireFox)
![image](https://user-images.githubusercontent.com/47414075/54201185-4fd73880-44cd-11e9-9d78-8eda00dd00e9.png)

**Sådan burde det fungere (Expected behavior)**
Read only skal defineres specifikt for firefox ex:

input:-moz-read-only { /* For Firefox */
  /* readonly styling*/
}

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 65.0.2 (64-bit)

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Tak for din henvendelse.

Vi har oprettet en sag på det, og vil vende tilbage så snart vi har kigget på det.

I mellemtiden - kan jeg da få dig til at prøve at kigge på [https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/) i firefox, og se om read-only eksemplet heller ikke virker der? - jeg har nemlig ikke kunnet reproducere det i min ende.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Hej Kristina

Når jeg kigger på koden i browseren, kan jeg se at I her har indsat det specifikt til firefox:

![image](https://user-images.githubusercontent.com/47414075/54202863-40f28500-44d1-11e9-8ae0-b667b332070c.png)

Men det er der ikke gjort i koden: 

https://github.com/detfaellesdesignsystem/dkfds-components/blob/f842105f0d58e7c6f1caf9c4d908da8044dbf904/src/stylesheets/elements/_inputs.scss#L145 

Har lavet en pull request her: 
https://github.com/detfaellesdesignsystem/dkfds-components/pull/15

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Jeg har nu kigget nærmere på det.

Det viser sig, at hvis man vil bruge scss filerne og ikke css filerne i sit projekt, skal man selv sørge for at køre scss filen igennem autoprefixer.

Jeg har tilføjet dokumentation omkring dette under [Til udviklere](https://detfaellesdesignsystem.github.io/dkfds-docs/omdesignsystemet/tiludviklere/) på dokumentationssitet.

Sig endelig til, hvis du har spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Mange tak for hurtigt svar. Jeg lukker sagen
