### ISSUE TITLE
Radioknapper er ikke tilgægenlige

### ISSUE THREAD

**Issue by claudia9** [detfaellesdesignsystem/dkfds-components#140]
Hej,

Vi har en løsning hvor vi bruger jeres Radioknapper men vi har lige fundet ud af, at vi ikke kan navigere dem gennem tastaturer. Altså at man ikke kan tab mellem knapperne.

Se her: https://designsystem.dk/eksempel/radiobutton/

**Comment by detfaellesdesignsystem** [comment]
Hej @claudia9,

Tak for henvendelsen!

Radioknapper er lidt noget for sig - man bruger tab for at komme ind i listen, og når man har fokus på en radioknap navigerer man mellem dem med piletasterne. Det er default opførelse for radioknapper i alle browsers.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
