### ISSUE TITLE
Døde links på "Kode -> Print" siden

### ISSUE THREAD

**Issue by mesterjagels** [detfaellesdesignsystem/dkfds-components#141]
**Bekskriv fejlen (Describe the bug)**
Der er en del døde links på eksemplerne på "Print" siden

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Gå til https://designsystem.dk/kode/print/
2. Klik på diverse links under Header eller Footer

**Indsæt link (Add a URL)**
https://designsystem.dk/kode/print/

**Sådan burde det fungere (Expected behavior)**
Jeg vil gerne se nogle eksempler :)

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 89.0b4

**Comment by detfaellesdesignsystem** [comment]
Hej @mesterjagels,

Tak for at gøre opmærksom på det. Vi har fikset det nu. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
