### ISSUE TITLE
Hvordan angives fejl på trin i trinindikator?

### ISSUE THREAD

**Issue by jkruse** [detfaellesdesignsystem/dkfds-components#142]
Jeg er ved at omlægge en løsning fra den nu forældede virk.dk designmanual til FDS. I designmanualen var der et paradigme for visning af trin med fejl på, så man kunne indikere at brugeren havde forladt et trin hvor noget obligatorisk ikke var udfyldt, eller et felt var udfyldt forkert.

I FDS findes ikke et tilsvarende eksempel. Er det fordi det skal gøres umuligt at navigere væk fra trin som ikke er udfyldt korrekt og tilstrækkeligt, eller er det blot en mangel i eksemplerne?

Der er tale om en halvstor formular med rigtigt mange felter, og brugerne kan møde spørgsmål undervejs som de ønsker at udsætte udfyldelsen af, fordi de ikke lige har den oplysning til rådighed, for så at vende tilbage senere og gøre formularen færdig. Vi ville derfor se det som en serviceforringelse, hvis vi skulle gøre det umuligt at navigere væk fra trin med fejl eller mangler på.

**Comment by detfaellesdesignsystem** [comment]
Hej @jkruse,

Tak for din henvendelse.

Jeg vil lige sende den videre til vores UX'ere som lige vil tage det op. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @jkruse 

[Fejl i trinindikatoren](https://designsystem.dk/komponenter/trinindikator/#med-fejl) er kommet med i version 9.0.0.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
