### ISSUE TITLE
Hvorfor er der en "Valgt" tekst på trinindikator?

### ISSUE THREAD

**Issue by stil-sds** [detfaellesdesignsystem/dkfds-components#143]
Hej!

Hvorfor er der egentlig en "Valgt" tekst indsat på alle trinindikatorer undtagen Klikbar? Jeg går ud fra, at det er for at indikere  det aktive punkt til skærmlæsere. Men det kunne jo løses vha aria-current=step istedet eller en skjult tekst. 

Kender vi baggrunden for beslutningen?

Mvh

John

**Comment by detfaellesdesignsystem** [comment]
Hej John,

Tror "Valgt" har været den første metode til at fortælle om det aktive trin, hvorefter aria-current så er blevet tilføjet.

Pt. er aria-current defineret som page, men vil lige undersøge om vi skal ændre det til step. Da trinindikatoren er bygget på baggrund af sidenavigationen kommer det sikkert derfra.

Jeg vender det lige med Camilla og Mette, om "Valgt" skal fjernes helt.

**Comment by stil-sds** [comment]
Det lyder meget plausibelt :) Tak!

**Comment by detfaellesdesignsystem** [comment]
Hej John,

Vi fjerner Valgt teksten på trinindikator.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
