### ISSUE TITLE
Hjælp til FDS-opgradering 

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#144]
Hej FDS,
Vi har en selvbetjeningsløsning på borger.dk, som skal opgraderes til FDS. Brugeren skal igennem et flow - nogle trins for at angive et uddannelsesniveau, som Praktikplads-AUB skal bruge for at kunne udbetale et bidrag til brugerens arbejdsgiver. 
Brugeren kan svare med "Ja", "Nej" eller "ved ikke", for at gå til næste trin/spørgsmål (ingen Næste knap). Hvordan ser I dette blive løst med jeres trinindikator? og hvad med "Afbryd" knappen - hvor skal den placeres, hvis den må overhovedet være der :-)

![image](https://user-images.githubusercontent.com/48348000/118449275-48d29300-b6f3-11eb-8a1d-f31ccb962e1e.png)
![image](https://user-images.githubusercontent.com/48348000/118449451-74557d80-b6f3-11eb-93e6-b953d057d8f3.png)

Ind på "opsummering" trinnet, bliver brugeren præsenteret for et nyt (trinnet har ikke været en del af flowet før) trin"; Ændr besvarelse. Her har brugeren mulighed for at vælge et nyt uddannelsesniveau, trykke ok - og bekræfte på "opsummering" trinnet. Spørgsmålet er, hvordan kan dette trin passe ind i en trinindikator - da alle trinene skal være synlige for brugeren fra start :-)

![image](https://user-images.githubusercontent.com/48348000/118467043-bdadc900-b703-11eb-96c4-943ac49d0084.png)
![image](https://user-images.githubusercontent.com/48348000/118467199-e635c300-b703-11eb-9549-2d2420af4bf1.png)

Vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

Tak for din henvendelse.

Vi vender det lige i teamet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designystem

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana
 
Vi har udviklet en lignende løsning til krav-værktøjet til Det Fælles Designsystem, som I kan lade jer inspirere af. Jeg har sat screenshots ind her, men du kan også prøve løsningen af på hjemmesiden: https://designsystem.dk/krav-vaerktoej/anvendes-af-virksomheder/ 

<img width="1440" alt="Screenshot 2021-05-18 at 11 49 21" src="https://user-images.githubusercontent.com/44367338/118792172-b0c1de80-b897-11eb-94d8-5428f5781418.png">

<img width="1440" alt="Screenshot 2021-05-18 at 12 07 43" src="https://user-images.githubusercontent.com/44367338/118792251-c3d4ae80-b897-11eb-8a6a-68799c8ba27e.png">

Vi vil altså anbefale at anvende radioknapper til svarene samt tilbage/næste-knapper til at navigere i spørgsmålene. Afbryd-knappen kan som i krav-værktøjet implementeres med et funktionslink i øvre højre hjørne.
 
Som du kan se er alle trin ikke synlige fra start, eftersom trinnene varierer alt efter de svar, brugeren angiver.
 
Du må endelig melde tilbage, hvis du har flere spørgsmål.
 
Med venlig hilsen
Mette Boldt
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Mette,
Tusind tak for hurtigt svar.
Det er et godt eksempel, du har sendt - det kan vi godt blive inspireret af :-)
