### ISSUE TITLE
tooltip i table header på mobil

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#145]
Hej FDS,
Vi bruger ofte tooltip i table header - og når tabellen har classen "table--responsive-headers" bliver th'er ikke vist på mobileenheder. Fordi man bruger data-title="" i td  - og spørgsmålet er om der findes en smart måde at vise tooltip på både på mobil og desktop, så vi har tooltippen stående kun et sted i koden. Er det noget I har undersøgt før?
![image](https://user-images.githubusercontent.com/48348000/118481070-60217880-b713-11eb-92e4-e8d932a5f10e.png)
![image](https://user-images.githubusercontent.com/48348000/118481184-7c251a00-b713-11eb-9252-08a3fd4f1fd1.png)

Mvh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

Tak for din henvendelse.

Vi vender det lige i teamet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

I eksemplet vises to tabeller med én række hver. Vil der på noget tidspunkt være mere end én række i tabellerne?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Ja, der ville være flere rækker i tabellen - vi bruger også ofte "Avancerede tabeller" med et ikon til modal eller tooltip i t-headeren :-)

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

I jeres tilfælde vil vi anbefale at anvende et detaljeelement til tooltipbeskrivelserne på mobil. På mobil ville det altså se således ud:

<img width="324" alt="Screenshot 2021-11-18 at 14 48 00" src="https://user-images.githubusercontent.com/44367338/142427427-a9ef5e8f-0da1-46f4-beec-07dbb7702e6b.png">

<img width="320" alt="Screenshot 2021-11-18 at 14 48 09" src="https://user-images.githubusercontent.com/44367338/142427465-b4089dff-14cb-4108-a754-b4d43ff63de0.png">


Vi vil også anbefale jer at genoverveje, hvordan regnestykket kommunikeres til brugeren, da det ikke er tilgængeligt med tabelkolonner uden tilhørende labels i headeren (til x og =). I kunne fx vise rækkestykket over tabellen i stedet. Det ville se sådan ud (sørg i øvrigt for, at gangetegnet læses korrekt op af en skærmlæser):

<img width="651" alt="Screenshot 2021-11-18 at 14 47 55" src="https://user-images.githubusercontent.com/44367338/142427556-5f769dbc-22bb-4052-aa02-fc3f176dce31.png">


Bemærk i øvrigt at vi anbefaler højrestilling af tal med numerisk størrelse i tabeller, da det gør det lettere for brugeren at sammenlige tal.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Mette,
Tak for tilbagemelding :-)
1. Jeg skrev dette issue i håbet om, at I måske kunne finde en "kode" løsning på tooltips, så vi ikke gentog hele tooltip html-koden i data-title="" også. Jeg tror ikke details er løsningen her i tabelheaders. Tooltipen skal helst stå tæt på den th, den handler om. Den fungerer meget fint på mobil i andre tilfælde, når den ikke står i tabel. 

2. Vi har wcag testet tabellen - og har forklaret regnestykket i arialabels til skærmlæsere. 

3. Højrestilling af tal med numerisk størrelse i tabeller er taget til efterretning :-)

Vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Det er dejligt at høre, at I har taget god højde for skærmlæseren i jeres løsning.

Vi har desværre ikke planer om at inkludere en teknisk løsning på at vise tooltips sammen med kolonneoverskriften i responsive tabeller på mindre skærme, da vi mener, det vil forstyrre brugergrænsefladen med så mange tooltips, der reelt beskriver de samme labels flere gange.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
