### ISSUE TITLE
Fejl i trinindikators navigation

### ISSUE THREAD

**Issue by stil-sds** [detfaellesdesignsystem/dkfds-components#149]
**Bekskriv fejlen (Describe the bug)**
Når man klikker på et senere trin end det umiddelbart næste, holder trinindikatoren op med at fungere og man er tvunget til at bruge hhv "næste" eller "tilbage".

**Genskab fejlen (To Reproduce)**
1. Vælg eksempelsiden: https://designsystem.dk/pages/eksempler/AES-erstatningssag/aes-1/'
2. Vælg F12 (Chrome) og responsiv eller en vilkårlig mobilvisning
3. Vælg trin 7
4. Trinindikatoren er nu "død". Bemærk at mobilmenu også stopper med at fungere. 

**Sådan burde det fungere (Expected behavior)**
Det burde være muligt at hoppe frem og tilbage og som minimum kunne åbne trinindikatoren uanset hvad. Men det kan man ikke, hvis man gennemfører ovenstående.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - Win10
 - Chrome
 - 91.0.4472.77 

**Kommentar**
Jeg troede, det måske var noget z-index, der gik galt, men det ser ikke ud til at være tilfældet. Det ser ud som om, at trinindikatoren simpelthen taber sin funktion efter nogle klik frem i flow og tilbage igen. Jeg har kunnet genskab samme fejl i vores implementering af trinindikator med nøjagtig samme forløb.

**Comment by detfaellesdesignsystem** [comment]
Hej John,

Der var en js fejl på siden, der gjorde at intet virkede. Det var en forkert attribut (aria-controls skulle være data-aria-controls) på tjekboksene, der gav en fejl.

Fejlen er fikset og vil være med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
