### ISSUE TITLE
CSS fejl ift fieldset?

### ISSUE THREAD

**Issue by stil-sds** [detfaellesdesignsystem/dkfds-components#150]
På alle eksempler på designsystem.dk har man fjernet border på fieldsets. Men i CSSen fremtræder det tydeligt, at man har et fieldset med angivelsen:

fieldset {
    border: 1px solid #c0c0c0;
    margin: 0 2px;
    padding: 0.35em 0.625em 0.75em;
}

Længere nede i den genererede CSS optræder så følgende:
fieldset {
    position: relative;
    border: none;
    margin: 0;
    padding: 0;
}

Alt efter genering har vi altså fieldset med og uden border. Det kunne være en hjælp, hvis vi kun har én model og alternativt skal den anden have en "borderless" class. Det giver lidt forvirring i test-situationer ellers.

**Comment by DKFDSdevelop** [comment]
Hej John,

Vi har normalize.css som fundament, hvor den første fieldset styling kommer fra. Jeg er ikke meget for at ændre i den fil, da det kunne give en større hovedpine fremadrettet. Det ser dog ud til at det muligvis kan løse sig selv ved at opdatere til en nyere version af normalize, så jeg har lagt en sag på det i backloggen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej John,

Vi har normalize.css som fundament, hvor den første fieldset styling kommer fra. Jeg er ikke meget for at ændre i den fil, da det kunne give en større hovedpine fremadrettet. Det ser dog ud til at det muligvis kan løse sig selv ved at opdatere til en nyere version af normalize, så jeg har lagt en sag på det i backloggen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by stil-sds** [comment]
Tak for orientering. Det kan vi så vælge at kompensere for internt.

Venligst

John
