### ISSUE TITLE
"Back to top" knap 

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#151]
Hej FDS,
Har I overvejet at tilføje en "Back to top" knap i FDS? mange af vores selvbetjeningsløsninger indeholder tabeller, hvor virksomheder kan udsøge fx deres medarbejdere - og nogle gange kan sådan en side blive meget meget lang (måske over 300 rækker på en tabel, hvis der er sat en begrænsning). Derfor kunne det være fedt med lidt hjælp i bunden af siden, så de hurtigt komme til top-menuen igen. En anden løsning på dette kunne være sticky menu/header :-) 

Vh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Kære Farzana,

Vi overvejer som sagt at brugerteste placeringen af tilbagelinket og i samme omgang teste et tilbage-til-toppen-link. Så en sådan komponent er muligvis på vej i backloggen. Vi vender tilbage med nyt i sagen.

Bh 
Camilla
FDS

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Så er tilbage-til-top-komponenten snart klar. Den er planlagt til at være med i næste release.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
