### ISSUE TITLE
Vejledningstekst på Radioknap henviser til Checkbox

### ISSUE THREAD

**Issue by ThorkilP** [detfaellesdesignsystem/dkfds-components#153]
Vejledningsteksten for Radioknapper henviser til Checkbox.
Fejlen er nederst på siden og starter med "For at initialisere collapse funktionaliteten på en checkbox skal input[type=checkbox] have følgende:"

https://designsystem.dk/kode/komponenter/radioknap/

**Comment by detfaellesdesignsystem** [comment]
Hej @ThorkilP,

Tak for henvendelsen. Vi vil rette det hurtigst muligt!

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
