### ISSUE TITLE
Hjælp (eksempel) til JavaScript til felter med obligatorisk indhold

### ISSUE THREAD

**Issue by ThorkilP** [detfaellesdesignsystem/dkfds-components#154]
Findes der FDS JavaScript events der er hægtet op på felter (input[type=text]) der fx kan bruges til at vise/skjule tilhørende fejlbeskeder?

Der er HTML eksempler på felter med og uden fejlbesked, men jeg har ikke kunnet finde vejledning til hvordan jeg får fejlbeskeden til at gå væk når en bruger fx har udfyldt et obligatorisk felt.

Mere overordnet: Findes der FDS events til validering af hele formularer som fx kan bruges til at vise/skjule fejlopsummering?

**Comment by detfaellesdesignsystem** [comment]
Hej @ThorkilP,

Tak for din henvendes.

Nej, vi har for nuværende ingen javascript koblet på inputfelter i forbindelse med fejlbeskeder og fejlopsummering.

Man skal derfor selv tilføje koden der tilføjer og fjerner fejlbeskeder og fejlopsummering på siden.

Jeg vil vende det i teamet om det er en mulighed vi bør have i FDS.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Det er for nuværende ikke noget vi har planer om at tilbyde i FDS.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
