### ISSUE TITLE
Brug af DKFDS i en Vue app

### ISSUE THREAD

**Issue by tmksoft** [detfaellesdesignsystem/dkfds-components#156]
Jeg vil gerne benytte DKFDS i et nyt Vue baseret website (SPA). Jeg har tidligere importeret css og js filer via index.html, men jeg vil gerne prøve at bruge det som en NPM pakke i stedet for.

Problemet er at min kunde har andre farver end dem som borger.dk og virk benytter. Tidligere har jeg lavet en skabelon fil med overstyring af farver og ekstra styles, kørt sass værktøjet og importeret den resulterende css fil.

Når jeg laver en en scss skabelon fil og kører de her loadere som er i webpack (NUXT og Vue-cli) så knækker de på relative referencer  til billeder. Feks: ` '../img/logo-placeholder.png'.`

Udfra stack-tracet kan jeg se at det er fordi den benytter det katalog hvor mit eget tema ligger som udgangspunktet for at opløse relative referencer. 

Pt kan jeg kun få det til at virke hvis jeg placerer min scss skabelon fil i src/stylesheets mappen inde i node_modules sammen med eksempelvis dkfds-borgerdk.scss. 

Herefter kan jeg så få adgang til alle styles i min .vue filer ved at skrive 

`import "dkfds-dkpto/src/stylesheets/dkfds-dkpto.scss";`

i script blokken på den enkelt vue fil.

`dkfds-dkpto.scss` er navnet på min skabelon (tema) fil.

Håber I har mulighed for at komme med et forslag.

Lidt kontekst:
Den første Vue spa er bygget direkte i Vue. Her har jeg benyttet sass værktøjet til at generere en css fil som jeg så importer i SPA'ens index.html. I det nye site jeg skal til at lave vil jeg gerne benytte Nuxt og NPM i stedet for.

Mvh
Thomas

**Comment by detfaellesdesignsystem** [comment]
Hej Thomas,

Tak for din henvendelse!

Du kan overskrive path variablerne i sass så de passer bedre til din mappestruktur.

$font-path:         '~dkfds/src/fonts/IBMPlexSans/';
$image-path:        '~dkfds/src/img';
$icons-folder-path: '~dkfds/src/img/svg-icons';

Sig endelig til, hvis du fortsat oplever problemer, så kigger jeg nærmere på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by tmksoft** [comment]
Hej Kristina - tusind tak. Det var lige præcis det jeg skulle bruge. :-)

Mvh
Thomas
