### ISSUE TITLE
Detaljer komponenter inde i en Detaljer komponent viser ikke åben/luk pil korrekt

### ISSUE THREAD

**Issue by nc-csl** [detfaellesdesignsystem/dkfds-components#158]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Bekskriv fejlen (Describe the bug)**
Hvis man indsætter en Detaljer komponent inde i en anden Detaljer komponent, så vises pil i underliggende komponent ikke korrekt. Når man folder den øverste Detaljer komponent ud, så tror den underliggende også at den er foldet ud, og viser dermed en pil der peger nedad. 

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Opret Detaljer komponent og indsæt en anden Detaljer komponent i den.
2. Åben øverste Detaljer komponent.
3. Verificer at pil i underliggende Detaljer komponent peger nedad.

**Screenshots**
![image](https://user-images.githubusercontent.com/722375/140051281-ebe72014-3128-4660-834e-1cea5bddbb2f.png)

**Sådan burde det fungere (Expected behavior)**
Det er kun den Detaljer komponent som man folder ud, hvor pil skal pege nedad. Fejlen sker fordi man i DKFDS sætter "pil ned" i css på alle efterfølgende Detaljer komponenter og ikke kun den første.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by detfaellesdesignsystem** [comment]
Hej @nc-csl,

Tak for din henvendelse!

Vi opretter en sag på det og vender tilbage når der er nyt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej nc-csl

Detaljeelementer bør ikke placeres inden i hinanden, da de ikke er tiltænkt sådanne mere komplicerede navigationsstrukturer. Overvej om I kan bruge andre komponenter til jeres løsning, eller om det evt. vil give mening at dele indholdet ud på flere sider. 

Vi tilpasser dokumentationen til Detaljer til næste release, så det bliver mere tydeligt, hvordan komponenten anvendes.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
