### ISSUE TITLE
Radiobuttons og tjekbokse er ikke synlige på print

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#159]
Hej FDS,
Radiobuttons og tjekbokse er ikke synlige på print.

Her er FDS eksempel: 
https://designsystem.dk/eksempel/radiobutton-large/ 
https://designsystem.dk/eksempel/checkbox-large/
![image](https://user-images.githubusercontent.com/48348000/142997265-8a2501ec-f98b-4d79-bd95-f8e12cc7bcb3.png)

Her er et GDS eksempel, hvor radiobuttons og tjekbokse er synlige på print: 
https://design-system.service.gov.uk/components/radios/default/index.html 
https://design-system.service.gov.uk/components/checkboxes/default/index.html
![image](https://user-images.githubusercontent.com/48348000/142997293-12ed3138-6665-4c94-a5c0-69e8e1becc99.png)

Mvh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

Hvis jeg husker rigtigt var det en bevidst beslutning fra Sunes side. Man ser et flueben ved den værdi, som er valgt.

Vi vender det lige internt, om vi skal genbesøge denne.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Tak fordi du gør os opmærksomme på dette. Vi har undersøgt det nærmere og besluttet at vise tjekboksene - valgte som ikke valgte - på print, ligesom det også er standarden i andre designsystemer såsom Gov UK, USWDS, Material Design m.fl.

Rettelsen kommer med i en af de kommende releases.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
