### ISSUE TITLE
Header kontakt style

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#16]
**Lille ønske**
Kan I gøre det muligt at anvende en a-tag til kontakt "knappen" i header, uden at påvirke stylingen med de traditionelle link-understregning  ? 

**Med Button-tag:**
![image](https://user-images.githubusercontent.com/25169794/54355261-e3894000-4658-11e9-81af-3076bccf7f1b.png)

**Med a-tag:**
![image](https://user-images.githubusercontent.com/25169794/54355573-b5f0c680-4659-11e9-9879-e525e8ff55fa.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Tak for din henvendelse!

Vi har oprettet en sag på den, og vil vende tilbage når vi har kigget på den.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Vi har kigget på det og er kommet frem til følgende løsning, som kommer med i næste release:

![external-link-in-header](https://user-images.githubusercontent.com/44367338/56579561-c9843b00-65d0-11e9-9627-aa939a3d02d4.PNG)

Da det er et link, der fører brugeren væk fra siden/løsningen bør man gøre vedkommende opmærksom på dette ved at bruge et eksternt link med ikonet. Tilføj klassen function-link for at gøre linkfarven sort i headeren. For at gøre opmærksom på at der er tale om et link,s om man kan trykke på bør der være understregning.

Håber du fik svar på dit spørgsmål. Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
