### ISSUE TITLE
Vis et eksempel på en formular der viser/skjuler sektioner baseret på valg

### ISSUE THREAD

**Issue by madsh** [detfaellesdesignsystem/dkfds-components#160]
**komponenter/formular**

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Mange selvbetjeningsløsninger hos UIM gør brug af funktionalitet til at vise/skjule dele af en formular, baseret på valg i andre felter. Det er design som måske bedre kunne løses ved at anvende 'trin', men er noget som efterspørges af vores sagsbehandlere. 

Jeg foreslår at lave et simpelt 'dynamisk formular?' eksempel. Måske udbygge det nuværende kørekort eksempel under kode/formular. Hvis brugeren vælger _Ja_ til _Har du et kørekort?_ kunne formularen vise et felt til indtastning af et kørekortsnummer. 

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
Jeg har overvejet at anvende forms i accordions, men jeg tror at det kun er relevant for meget komplekse formularer.  En anden mulighed er trin-identifikatorer, men de er mest relevant hvor der er naturlig række følge i udfyldelsen.

**Comment by madsh** [comment]
Jeg har lige læst #142 som måske minder lidt om...

**Comment by detfaellesdesignsystem** [comment]
Hej madsh

Til simple formularer såsom eksemplet med angivelse af kørekortnummer, som du beskriver, kunne man med fordel bruge komponenten Radioknap med skjult indhold. Således kan du fx vise et tekstfelt så snart brugeren har angivet, at de har et kørekort. 

Du finder komponenten her: https://designsystem.dk/komponenter/radioknap/#skjult-indhold-collapse 
Og kodedokumentationen her: https://designsystem.dk/kode/komponenter/radioknap/#skjult-indhold

Hvis der er tale om hele dele af en formular, der kun vises afhængigt af brugerinput, kan I overveje en formular i flere trin, hvor trinene ikke er defineret på forhånd. Vores eget krav-værktøj er et eksempel på dette: https://designsystem.dk/krav-vaerktoej/anvendes-af-virksomheder/

Vi anbefaler ikke at anvende accordions til at angive trin i en formular.

Sig endelig til, hvis du har flere spørgsmål.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
