### ISSUE TITLE
Tooltip - fejl ved tilgængelighedsprøve - mangler stickyness

### ISSUE THREAD

**Issue by JOKBODIGST** [detfaellesdesignsystem/dkfds-components#163]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Bekskriv fejlen (Describe the bug)**
Vær klar og præcis i din beskrivelse af fejlen. (A clear and concise description of what the bug is.)

Tooltip.
Mangler stickyness, som gør at man kan aktiverer tooltip med museklik, mellemrum eller enter og derefter tabulere videre. Der er også problemer med at man kan have flere tooltips åbne samtidig. Desuden understøtter den ikke ”svævepeg”, hvilket er at man skal kunne nå at give tooltip tekst fokus ved hover inden den forsvinder.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):

Fejlen er blevet indrapporteret i forbindelse med en webtilgængelighedstest. 

**Indsæt link (Add a URL)**
Tilføj om muligt et link til fejlen. (If possible, add a URL to help identify your problem.)
N/A

**Screenshots**
Tilføj om muligt et eller flere billeder der viser fejlen. (If applicable, add screenshots to help explain your problem.)
N/A

**Sådan burde det fungere (Expected behavior)**
Beskriv om muligt, hvordan fejlen løses eller beskriv klart og præcist hvordan det burde fungere. (A clear and concise description of what you expected to happen.)

Se beskivelse af fejl.

**Desktop - udfyld venligst følgende (please complete the following information):**

**Smartphone - udfyld venligst følgende (please complete the following information):**

**Supplerende oplysninger (Additional context)**
Tilføj andre detaljer vedrørende fejlen.  (Add any other context about the problem here.)

**Comment by detfaellesdesignsystem** [comment]
Hej @JOKBODIGST 

Tak for henvendelsen.

Vi har oprettet en sag på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JOKBODIGST,

Kan du uddybe lidt i forhold til, hvad den ønskede opførelse er i forhold til de meldte udfordringer med tooltip komponenten?

Særligt med hensyn til: "Mangler stickyness, som gør at man kan aktiverer tooltip med museklik, mellemrum eller enter og derefter tabulere videre."

Bemærk at tooltip komponenten blev opdateret i version 7.4.0.

For at undgå overlap af tooltips kan man kun have én tooltip åben ad gangen. Det er lidt uklart, hvad det er I ønsker her?

Toolltip er ikke et fokusérbart element, men det jeg gætter på I ønsker er at man skal kunne markere teksten for at få den læst op. Det skal selvfølgelig kunne lade sig gøre ved klik på tooltipknappen samt fokus på tooltipknappen. Hvorvidt det kan lade sig gøre ved hover på tooltip knappen skal lige vendes internt i FDS teamet.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
WCAG 1.4.13 Indhold ved svævepegning (hover) eller fokus - Niveau AA

Når elementer modtager fokus via musen (svævemarkøren) eller tastaturet og
udløser ekstra indhold/en hovertekst, skal det ekstra indhold/hoverteksten
opfylde følgende tre krav 1) Kan afvises, 2) svævepegning mulig og 3)
blivende.

*Claus Jessing*
---------------------------------------------
M: +45 6061 0101
Email: ***@***.***
Encrypted email: ***@***.***

ᐧ

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for svar på sagen. Vi har rettet tooltip komponenten til så man kan markere tekst ved både fokus/klik på tooltipknappen samt ved hover. Tooltippet bliver derved også ved "svævepeg".

Ændringen vil komme med i næste release.

@JOKBODIGST - Med hensyn til de 2 andre meldte udfordringer er det fortsat uklart, hvad den ønskede opførelse for komponenten er:

1. "Mangler stickyness, som gør at man kan aktiverer tooltip med museklik, mellemrum eller enter og derefter tabulere videre."
1. "Der er også problemer med at man kan have flere tooltips åbne samtidig."

I må meget gerne uddybe, hvad den ønskede opførelse for komponenten er, og argumenter herfor, hvis det skal ændres.

Vi venter med release indtil de sidste 2 udeståender er afklaret.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi lukker tråden her, da der ikke er kommet flere kommentarer.

Der blev releaset en ny version af tooltip i version 10.0.0.
