### ISSUE TITLE
Radio buttons - Fejl fundet i tilgængelighedstest - JAWS kan ikke oplæse radio buttons

### ISSUE THREAD

**Issue by JOKBODIGST** [detfaellesdesignsystem/dkfds-components#164]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Bekskriv fejlen (Describe the bug)**
Vær klar og præcis i din beskrivelse af fejlen. (A clear and concise description of what the bug is.)

Radio buttons
Der er problemer med at få JAWS til at oplæse radio buttons på https://designsystem.dk/eksempel/fieldset-complex/. Syntaksen på siden fejler ikke noget, så det kan ligeså godt være en begrænsning/fejl i JAWS. I Login komponenten virker det og forskellen er at vi ikke benytter en liste (UL) i fieldset-elementet. Det skulle dog være tilladt jf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):

Fejlen er fundet i forbindelse webtilgængelighedstest udført af en tredjepart. 

**Indsæt link (Add a URL)**
Tilføj om muligt et link til fejlen. (If possible, add a URL to help identify your problem.)
N/A

**Screenshots**
Tilføj om muligt et eller flere billeder der viser fejlen. (If applicable, add screenshots to help explain your problem.)
N/A

**Sådan burde det fungere (Expected behavior)**
Beskriv om muligt, hvordan fejlen løses eller beskriv klart og præcist hvordan det burde fungere. (A clear and concise description of what you expected to happen.)

Se beskrivelse af fejlen ovenfor.

**Desktop - udfyld venligst følgende (please complete the following information):**

**Smartphone - udfyld venligst følgende (please complete the following information):**

**Supplerende oplysninger (Additional context)**
Tilføj andre detaljer vedrørende fejlen.  (Add any other context about the problem here.)

**Comment by detfaellesdesignsystem** [comment]
Hej @JOKBODIGST 

Tak for henvendelsen.

Vi har oprettet en sag på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JOKBODIGST,

Vi har forsøgt at reproducere fejlen med seneste version af JAWS, og kunne ikke helt genskabe fejlen. Modsat fx. NVDA skærmlæseren og standardopførelse i browsere, så gør JAWS brug af egne genvejstaster til at navigere i en liste af radioknapper. (A for næste radioknap, Shitft + A for forrige radioknap).

JAWS sætter sin egen form for fokus på den oplæste radioknap, hvilket vi ikke understøttede. Det har vi ændret så den røde ramme kommer på den aktuelle radioknap.

Vores eksempler er også opdateret så vi ikke længere gør brug af en ul liste - trods gyldig HTML var der ingen årsag til at have det opstillet på den måde. Denne ændring har dog ingen ændring haft på brugeroplevelsen med JAWS.

Disse ændringer kommer med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
