### ISSUE TITLE
Tilføj overordnet title til trinindikator

### ISSUE THREAD

**Issue by Emilieisabelladahl** [detfaellesdesignsystem/dkfds-components#168]
**Navn i designsystemet (Feature name in the design system)**
Trinindikatorer

**Link til det der skal opdateres (URL to what needs to be updated)**
https://designsystem.dk/pages/eksempler/strategiske-virksomhedsalliancer/virksomhedsalliancer-1/

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Vi har en løsning med en menu navigationsbar, hvor en ansøger skal lave en ansøgning til en specifik uddannelse. 
Vi vil derfor gerne have at den overordnet overskrift er navnet på uddannelsen man er ved at søge ind på.

I jeres løsning er der ikke en overordnet overskrift på trinindikator eksemplet.

Her er et skærmbillede af vores trinindikator som vi arbejder på at forbedre:
![image](https://user-images.githubusercontent.com/90379827/159697304-c468a713-364a-466a-81c7-cbc9fe4b5241.png)

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Vi vil gerne forstår hvordan vi skal tilføje en overordnet title ift. jeres opsætning:
![image](https://user-images.githubusercontent.com/90379827/159697382-a64b44a0-a783-4db7-a4f0-710030ade08c.png)

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
Tilføje en titel under streg, men under over trinindikator. 

**Supplerende bemærkninger (Additional context)**
Billeder indsat ovenstående

**Comment by detfaellesdesignsystem** [comment]
Hej Emilieisabelladahl

Som du selv er inde på, så anbefaler vi at placere formularens titel som en del af headeren - over “stregen”. 

Vi vil også anbefale, at formularen åbnes uden for den øvrige sidenavigation, så brugeren ikke forstyrres af navigationen mens formularen udfyldes. I kan lade brugeren forlade formularen igen ved at klikke til startsiden oppe i venstre hjørne samt med et decideret “Luk” funktionslink. 

I kan lade jer inspirere af, hvordan vi har implementeret vores fælles krav værktøj ved at starte værktøjet fra denne side: https://designsystem.dk/krav/  

Her er også en skitse af vores forslag:

<img width="892" alt="Screenshot 2022-03-31 at 15 09 51" src="https://user-images.githubusercontent.com/44367338/161062445-92e339dd-d11e-4b5f-964e-6f0e6df00533.png">

Sig endelig til, hvis du har yderligere spørgsmål.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
