### ISSUE TITLE
.small-text er sat til font-weight medium (500) i stedet for normal (400)

### ISSUE THREAD

**Issue by clpatp** [detfaellesdesignsystem/dkfds-components#17]
I stedet for at small tekst bliver vist diskret er den med font-weight 500 mere fremtrædende end andet tekst. 
Kan den laves om til 400 eller kan der laves flere varianter af den?

**Comment by detfaellesdesignsystem** [comment]
@clpatp der er lavet en user story. Small-text rettes til 400, da man jo altid kan anvende small-text i fed, hvis det skal fremhæves. Tak for input.

**Comment by detfaellesdesignsystem** [comment]
Hej @clpatp,

Vi har ændret font-weight på small-text nu - fikset vil være med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by clpatp** [comment]
Lækkert - tak :)
