### ISSUE TITLE
Problemer med sorterings ikoner

### ISSUE THREAD

**Issue by Flaeng** [detfaellesdesignsystem/dkfds-components#171]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Bekskriv fejlen (Describe the bug)**
dist/img/svg-icons/sort-none.svg bør navngives sort-table-none.svg da den bedre ligner sort-table-desc og sort-table-asc
dist/img/svg-icons/sort-acending.svg bør slettes da dens "partner" er overskrevet (fejl i filnavn ace(...) i stedet for asce(..))

**Genskab fejlen (To Reproduce)**
Forsøg at hent ikoner til at vise sortering på en tabel. Vi brugte tidligere sort-none, sort-ascending og sort-descending men det ser tosset ud efter vi opdateret til nyeste version af dkfds.

**Indsæt link (Add a URL)**
[Tilføj om muligt et link til fejlen. (If possible, add a URL to help identify your problem.)
](https://github.com/detfaellesdesignsystem/dkfds-components/tree/master/dist/img/svg-icons)

**Screenshots**
![image](https://user-images.githubusercontent.com/6176282/162925772-d40903b2-e420-4588-99d8-aa72c764ac12.png)
![image](https://user-images.githubusercontent.com/6176282/162926008-f8df4fb3-7850-4c62-b9ce-5106f5ae9b7e.png)

**Sådan burde det fungere (Expected behavior)**
Ikonerne-filnavne bør staves korrekt og matche på tværs af grupper 
sort-none, sort-asc og sort-desc bør ligne hinanden.
sort-table-none, sort-table-asc og sort-table-desc bør ligne hinanden.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Alle
 - Browser Alle
 - Version dkfds 7.5.3

**Smartphone - udfyld venligst følgende (please complete the following information):**
 - Device: Alle
 - OS: Alle
 - Browser Alle
 - Version dkfds 7.5.3

**Supplerende oplysninger (Additional context)**

**Comment by detfaellesdesignsystem** [comment]
Hej @Flaeng ,

Tak for din henvendelse!

Vi har ryddet op i ikonfilerne i den kommende version v8.0. Da det ville være en breaking change at fjerne ikonfiler, som løsningerne aktivt bruger, har vi ikke kunne fjerne dem før vi havde en major release på trapperne.

De korrekte ikoner ses på https://designsystem.dk/design/ikoner/ikoner-og-deres-betydning/

Resten bliver fjernet i v8, som bliver releaset inden for få uger.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by Flaeng** [comment]
Hej Kristina
Jeg får en 404 når jeg prøver at tilgå den side :/

Min kolega så desuden at der er en "Luk accordion"-ikon, men ingen "åben accordion"
https://designsystem.dk/design/ikoner/

**Comment by detfaellesdesignsystem** [comment]
Hej @Flaeng 

> Jeg får en 404 når jeg prøver at tilgå den side :/

Det kan jeg se. Du kan anvende dette link i stedet for: https://designsystem.dk/design/ikoner/#betydning

> Min kolega, @memadk, så desuden at der er en "Luk accordion"-ikon, men ingen "åben accordion" https://designsystem.dk/design/ikoner/

Godt spottet! Jeg har oprettet en sag på dette.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @Flaeng

Åben accordion-ikonet kan nu findes beskrevet her: https://designsystem.dk/design/ikoner/

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Flaeng

Vi lukker dette issue, da det lader til, at problemerne er blevet løst i vores sidste par releases. Du er velkommen til at genåbne, hvis du oplever problemer.

Venlig hilsen
Mette
Det Fælles Designsystem
