### ISSUE TITLE
Accordions: Bulk åben og luk virker ikke altid da der tilføjes for mange EventListeners

### ISSUE THREAD

**Issue by LarsOPallesen** [detfaellesdesignsystem/dkfds-components#172]
**Bekskriv fejlen (Describe the bug)**
Ved brug af Accordion-bulk-open indsættes der en EventListener pr. accordion button, dvs hvis man indsætter et ulige antal accordions, som på jeres eksempel side: http://designsystem.dk/eksempel/accordion-bulk-open, så ser alt ud til at virke fint.
Man ser kun fejlen ved et lige antal accordions, da man ved lige antal ender i samme situation som udgangspunktet, enten forbliver alle lukkede, eller alle forbliver åbne.
Der bør kun indsættes en enkelt EventListener på accordion-bulk-button.

**Genskab fejlen (To Reproduce)**
Tag jeres eksempel fra http://designsystem.dk/eksempel/accordion-bulk-open og tilføj en accordion mere.

**Indsæt link (Add a URL)**
N/A

**Screenshots**
N/A

**Sådan burde det fungere (Expected behavior)**
Ved klik på åben alle / luk alle bør alle accordions henholdsvis åbne og lukke.
Fejlen løses ved kun at tilføje en enkel EventListener på bulk knappen.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Linux Mint
 - Browser Chromium
 - Version 99.0.4844.51

**Smartphone - udfyld venligst følgende (please complete the following information):**
N/A

**Comment by detfaellesdesignsystem** [comment]
Hej @LarsOPallesen,

Tak for din henvendelse.

Fejlen er fikset i den kommende v8.0.0. Regner med at v8 kommer ud omkring midt maj.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
