### ISSUE TITLE
Gråtoner matcher ikke dokumentationen

### ISSUE THREAD

**Issue by Flaeng** [detfaellesdesignsystem/dkfds-components#174]
Ifølge dokumentationen er grå-100 og grå-200 den samme farve (F5F5F5) og grå-300 er DCDCDC
Det er den dog ikke i koden. Der er
grå-100 = F5F5F5
grå-200 = DCDCDC
grå-300 = BFBFBF

Docs:
https://designsystem.dk/design/farver/

Code:
https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/src/stylesheets/core/colors/_gray.scss

![image](https://user-images.githubusercontent.com/6176282/170043378-21c45673-5fb5-42a3-b042-700f0dc9958f.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @Flaeng 

Tak for henvendelsen!

Vi har oprettet en sag på det og vil vende tilbage, når vi har kigget nærmere på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @Flaeng 

Dokumentationen er nu opdateret.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Flaeng

Vi lukker dette issue, da problemet skulle være løst nu. Du er velkommen til at genåbne, hvis du fortsat oplever problemer.

Venlig hilsen
Mette
Det Fælles Designsystem
