### ISSUE TITLE
Knap på nyhedsbrevsside virker ikke

### ISSUE THREAD

**Issue by birkeara** [detfaellesdesignsystem/dkfds-components#175]
**Bekskriv fejlen (Describe the bug)**
Prøvede at melde mig til nyhedsbrevet, jeg kunne godt taste min e-mail ind, men jeg bliver ikke sendt videre til 'kvitteringssiden' når jeg trykker på knappen. Da jeg inspicerede siden, så det ud til at der var et problem med jeres ajax kald.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Go to (https://designsystem.dk/faellesskab/nyhedsmail/)
2. Type in e-mail adress
3. Click on 'Tilmeld'
4. Inspect code in the console
5. See ajax error

**Indsæt link (Add a URL)**
(https://designsystem.dk/faellesskab/nyhedsmail/)

**Screenshots**
[2022-05-25_13-28-29](https://user-images.githubusercontent.com/94222670/170253654-2b1d2535-1e92-41c3-a3f9-fe931dadb05d.png)

**Sådan burde det fungere (Expected behavior)**
At man kan tilmelde sig nyhedsbrevet, dvs. blive sendt videre ved hjælp af knappen.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - Windows.
 - Chrome, nyeste version.

**Comment by detfaellesdesignsystem** [comment]
Hej @clarabaidel 

Tak for henvendelsen!

Vi har oprettet en sag på det og vil vende tilbage, når vi har kigget nærmere på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @clarabaidel 

Så skulle nyhedsbrevet fungere igen.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @birkeara 

Jeg er ikke i stand til at reproducere fejlen, så jeg har brug for flere informationer:

- Under "Vælg mails" (under inputfeltet) burde der være tre tjekbokse. Disse fremgår ikke af dit skærmbillede. Er de redigeret ud af billedet eller er det sådan, din side ser ud?
- Hvornår i flowet får du fejlen?
- Anvender du script blockers i din browser?

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by birkeara** [comment]
Hej Helle,

Det er sådan min side ser ud. Jeg får den når jeg trykker på knappen.

Tror ikke jeg anvender nogle scripts i min browser. Det er bare Google Chrome på min arbejdscomputer, men jeg ved ikke om IT Sikkerhed har indstalleret et eller andet fancy. Hvis jeg er den eneste det ikke virker for, er det nok ikke så relevant.

Det hele virker på min egen personlige computer, så måske er det bare en eller anden blokering vores IT sikkerhed har sat op. 

Hilsen Clara

**Comment by detfaellesdesignsystem** [comment]
Hej @birkeara 

Jeg lukker dette issue, da det oprindelige problem blev løst og det seneste rapporterede problem ikke lød til at være en fejl i nyhedsbrevet. Du er velkommen til at genåbne, hvis du har flere spørgsmål.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
