### ISSUE TITLE
Fejl i css fil i version 8.0.0

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#177]
Hej FDS

I har introduceret en fejl i version 8.0.0 som gør, at vi ikke kan opgradere til denne version. 
Der er fejl i jeres css fil, som jeg har udpejet i billederne herunder:

![image](https://user-images.githubusercontent.com/54143827/171396175-d3d52d3e-56f2-413f-b955-c08b5d88c760.png)

![image](https://user-images.githubusercontent.com/54143827/171397017-8c69f97a-9032-4659-8fcc-7fdd9982b37d.png)

Venlig hilsen Josephine - ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 

Version 8.0.1 er blevet udgivet, som skulle løse dette problem.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Josephine

Vi lukker dette issue, da fejlen skulle være rettet i v8.0.1. Du er velkommen til at genåbne, hvis du fortsat oplever problemer.


Venlig hilsen
Mette
Det Fælles Designsystem
