### ISSUE TITLE
Readonly virker ikke i IE11

### ISSUE THREAD

**Issue by postergaard** [detfaellesdesignsystem/dkfds-components#18]
**Bekskriv fejlen (Describe the bug)*
 Styling til readonly felter, slår ikke igennem i IE11

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):

1. Åben en IE11 browser (både windows 7 og 10)
2. Gå til et readonly felt

**Indsæt link (Add a URL)**
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter

**Screenshots**
Tilføj om muligt et eller flere billeder der viser fejlen. (If applicable, add screenshots to help explain your problem.)

![image](https://user-images.githubusercontent.com/47414075/54432508-b2c50b80-4729-11e9-9ed5-83852cf51443.png)

![50A4552D](https://user-images.githubusercontent.com/47414075/54433405-0a647680-472c-11e9-89dd-c6a06b9ac297.PNG)

**Sådan burde det fungere (Expected behavior)**
Beskriv om muligt, hvordan fejlen løses eller beskriv klart og præcist hvordan det burde fungere. (A clear and concise description of what you expected to happen.)

![image](https://user-images.githubusercontent.com/47414075/54433658-b5753000-472c-11e9-8158-e92f40398f2f.png)

**Desktop - udfyld venligst følgende (please complete the following information):**
- OS: Windows 7 og 10
- Browser: IE
- Version: 11

**Comment by postergaard** [comment]
Har i en status på denne?

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Tak for din henvendelse!

Vi har oprettet en sag på det og vil vende tilbage når vi har kigget på den.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Read-only styling virker nu også i IE11. Fikset kom med i version 4.0.1.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
