### ISSUE TITLE
Fejl i aria-label for at navigere "en måned tilbage"-knappen i datovælgeren.

### ISSUE THREAD

**Issue by oleguldberg** [detfaellesdesignsystem/dkfds-components#180]
Benyt eksempelt "Datovælger": https://designsystem.dk/komponenter/datovaelger/

- Brug en skærmlæser.
- Aktiver knappen "Åben kalender".
- Naviger til knapperne for at gå tlibage hhv. et år og en måned.
- Opdag de har samme beskrivelse (aria-label) "Naviger et år tilbage".

Rettelse er i Pull Request 178: https://github.com/detfaellesdesignsystem/dkfds-components/pull/178

**Comment by detfaellesdesignsystem** [comment]
Hej @oleguldberg 

Tak for henvendelsen!

Vi har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @oleguldberg 

Fejlen er rettet i version 8.0.1 og kan ses på https://designsystem.dk/komponenter/datovaelger/.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by oleguldberg** [comment]
Tak Helle!
Jeg lukker issuet.
De bedste hilsner
Ole Guldberg
