### ISSUE TITLE
Rapport med kolonner

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#181]
Hej
Jeg arbejder på en selvbetjeningsløsning, hvor det skal være muligt at sende en rapport ind. I rapporten skal der bl.a. gives en status på nogle aktiviteter, der kan være meldt ind for flere år siden. Det er derfor et krav, at brugeren kan se en beskrivelse af aktiviteterne tæt på det indtastningsfelt, hvor de skal give statussen. Beskrivelsen fylder ofte en halv A4-side.

Jeg har vendt designet med mit frontend-team, og vi er indtil videre landet på en løsning med to kolonner, hvor beskrivelsen præsenteres i venstre kolonne, og brugeren kan indtaste sin status i højre kolonne (se vedhæftede).

Jeg er med på, at det ikke er standard-FDS, men jeg har ikke kunnet finde et design i FDS, der opfylder behovet. Kan I godkende det vedhæftede designforslag med to kolonner eller tilbyde en alternativ løsning? På forhånd tak for hjælpen :)
![Rapport med to kolonner](https://user-images.githubusercontent.com/54175531/173497506-dbfc9af2-6d74-40e7-a0bf-3672b44bb57d.jpg)

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo 

Tak for din henvendelse!

Jeres design er sendt videre til vores UX'ere og de vil vende tilbage med et svar, når de har gennemgået det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo 

Jeg har kigget lidt på jeres udfordring. Og har lavet to forskellige designforslag som i kan se på. 

Med udgangspunkt i at vi ikke helt kender den fulde løsning og behov. Generelt så anbefaler vi at man ikke anvender accordions til at skjule vigtig information som brugeren skal interagerer med. Derfor har jeg lavet et design forslag uden accordions. 

Jeg har dog også lavet et forslag med accordions hvor vi har placeret tekstområdet under jeres beskrivelses felter. Vi anbefaler at man helst holder sig til en venstrestilling komponenter. Derfor ser begge forslag således ud. 

Håber det gav svar. 
Ellers er i velkomne til at skrive igen :) 

Bedste hilsner 
Marcus 
Det Fælles Designsystem

![Github #181](https://user-images.githubusercontent.com/44367338/175525048-99ead8a0-7e33-4671-8259-194c2ae9a811.png)

**Comment by KirstenTo** [comment]
Hej Marcus

Tak for dine bud. Jeg kan sagtens se, at dit design vil virke godt for mindre tekststykker, hvor både beskrivelse og tilhørende status kan ses på skærmen samtidigt. Min oplevelse er dog en anden, når teksten snarere er på en halv A4-side, for så risikerer brugerne at skulle scrolle, når de skal sikre sig, at beskrivelse og status hænger sammen.   

I sidste uge testede vi designet med de to kolonner, og alle brugerne syntes, at det var meget intuitivt. Flere af dem sagde uopfordret, at det var rigtig godt at have beskrivelse og status ved siden af hinanden, så det kunne være på samme skærm. Jeg er helt med på, at man **helst** skal holde sig til venstrestillede komponenter, men i dette tilfælde synes jeg, at det forringer brugeroplevelsen. Så kan vi gøre en undtagelse her?

De bedste hilsner fra Kirsten

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo 

Vi kommer ikke til at sige "god for" jeres løsning ud fra et FDS perspektiv. Men kan kun vejlede og sige at vi anbefaler at man ikke har to felter ved siden af hinanden i en accordion som i jeres løsning. 

Der vil også være nogle problemer med tilgængelighed på mobilvisning, som vil være en udfordring når man har to felter ved siden af hinanden i en accordion. Samt skærmoplæsning kan være en udfordring.

Om ikke andet, så skal i gøre det som i finder bedst for jeres løsning. Vi vejleder kun i forhold til jeres forestående problem. Og hvis i har testet og finder at jeres brugere godt kan finde ud af at navigerer i denne løsning så er det rigtig fint. 

Men ja, fra FDS' perspektiv er det ikke helt optimalt. Men vi vejleder kun i henhold til FDS og ser på hvordan en løsning bedst kan anvendes af en bruger ud fra FDS komponenter.

Bedste hilsner 
Marcus 
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Jeg lukker dette issue, da vi har givet den vejledning vi kan, og da I lader til at være landet på en brugertestet løsning. Du er velkommen til at genåbne, hvis I har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
