### ISSUE TITLE
Link til ny side fra tabelrække

### ISSUE THREAD

**Issue by LLP-atp** [detfaellesdesignsystem/dkfds-components#185]
Jeg er ved redesigne en selvbetjeningsløsning, som skal opgraderes fra MobileFirst til FDS. I løsningen er der bl.a. en tabel med mange tabelrække. Nogle af tabelrækkerne skal linke til nye sider (i samme vindue), hvor man ser en (lang) detaljeret beskrivelse af fx et indbetalt bidrag. 

I vores nuværende selvbetjeningsløsning er links markeret med en chevron i en cirkel: 

![image](https://user-images.githubusercontent.com/110180975/181532734-e87361be-473d-4053-bed5-bc93834b700f.png)

Hvordan skal dette designes ift. FDS? Jeg kan se, at der tidligere har været et spørgsmål fra ATP vedr. samme issue: 
(https://github.com/detfaellesdesignsystem/dkfds-components/issues/24)

Issue 24 ender ikke med en klar konklusion, og jeg ved heller ikke, hvad status er på den brugerundersøgelse, som ATP ville foretage. Hende, der ved det, er på barsel, så jeg kan ikke spørge. 

Men jeg vil gerne høre, hvordan jeg skal lave linket i tabelrækken. Skal det fx være et tekstlink "Se bidrag"? Dette kommer til at se meget massivt ud i de tilfælde, hvor der er mange, mange rækker i tabellen, hvor der er enslydende links hele vejen ned ad en række. Jeg ville foretrække et ikon, men jeg er enig i, at en chevron nok ikke er det mest brugervenlige valg.

**Comment by detfaellesdesignsystem** [comment]
Hej @LLP-atp 

Tak for din henvendelse. Placeringen af “videre-linket” sidst i tabellen giver god mening og har også fungeret problemfrit i flere brugertests foretaget på borger.dk.

Vi anbefaler altid at bruge ikoner sammen med tekst, når pladsen tillader det. Derfor vil vi i jeres tilfælde også anbefale dette. Det er rigtigt, at der vil stå den samme tekst mange gang i lange tabeller, men det har ikke givet udfordringer i de førnævnte brugertests (vi gør det også på fx opsummeringssider, se https://designsystem.dk/pages/eksempler/opsummering/opsummering-1/?r=/eksempler/templates/%23opsummering).

Vi vil altså anbefale noget i den her retning:
![image](https://user-images.githubusercontent.com/44367338/182142274-2dd15686-ae53-47a9-97a4-2aba8b292161.png)

På nuværende tidspunkt har vi i designsystemet ikke sådan en type link, hvor ikonet sidder til højre for teksten. Jeg opretter en opgave i vores backlog, så vi kan få tilføjet komponenten.

I øvrigt vil vi anbefale, at hele tabelrækken (og altså ikke kun pilen) er klikbar og fører til den næste side. Dette er særligt vigtigt på mobil.

Sig endelig til, hvis I har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by LLP-atp** [comment]
Perfekt! Tusind tak for hjælpen :) Jeg siger videre til udviklerne, at hele rækken skal være klikbar :)

Vh Louise
