### ISSUE TITLE
Dropdown-menu - ikke WCAG kompatibel

### ISSUE THREAD

**Issue by iwisti** [detfaellesdesignsystem/dkfds-components#186]
Det er ikke muligt at tabbe igennem dropdown-menuens valgmuligheder. Når man forsøger, lukker dropdown menuen igen.

Sådan genskabes fejlen (Steps to reproduce the behavior):
1.Tab hen til dropdownmenuen.
2. Klik Enter, så menuen åbnes
3. Tab for at gå ned over valgmulighederne
4. Se at menuen i stedet lukkes igen. Dette er en fejl. Den burde i stedet tabbe ned over valgmulighederne

Link:
https://designsystem.dk/komponenter/drop-down/

Sådan burde det fungere (Expected behavior):
Det burde fungere således, at når menuen er åben, hopper Tab ned gennem menupunkterne, så disse kan vælges med Enter. 

Desktop - udfyld venligst følgende (please complete the following information):**
 - Windows 10
 - Browser: Chrome

**Comment by detfaellesdesignsystem** [comment]
Hej @iwisti 

Tak for din henvendelse!

Dropdownen er lavet ved hjælp af et select-tag, som er et standard HTML-element, der har netop den opførsel, du beskriver, hvor tryk på tab-tasten lukker menuen. Når dropdownen er åben, kan der navigeres ved hjælp af op/ned-piletasterne.

Hvis du fortsat mener, der er et problem, eller hvis du har spørgsmål, så sig endelig til.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej iwisti

Vi lukker dette issue, da vores dropdown navigeres efter den gængse best practice for dropdowns.

Du er velkommen til at genåbne issuet, hvis du har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
