### ISSUE TITLE
Hvordan informeres brugere om, at deres session snart udløber?

### ISSUE THREAD

**Issue by MarenKGkc** [detfaellesdesignsystem/dkfds-components#187]
Hvordan ville I informere en bruger om, at deres session er ved at udløbe, efter de har været inaktive i x antal minutter?

Jeg ville mene, at et modalvindue ville være en fornuftig løsning, men dette ser ikke ud til at være muligt ifølge vejledningen omhandlende modalvinduer, hvor der står "_Brugeren skal selv aktivere modalvinduet. Det må ikke aktiveres per automatik..._"

Jeg håber, at I kan hjælpe :)

Med venlig hilsen,
Maren

**Comment by detfaellesdesignsystem** [comment]
Hej @MarenKGkc 

Tak for din henvendelse!

Vi anvender selv en modal i dette eksempel, der lyder meget som det, du efterspørger: https://designsystem.dk/eksempler/patterns/session-udloeber/

Jeg vender den lige med resten af teamet, om vores modal-vejledning skal opdateres.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @MarenKGkc

Det er godt spottet! Vi uddyber vejledningsteksten til modaler, så der henvises til session udløber med begrundelse for undtagelsen. Rettelsen kan ses efter næste release.

Jeg lukker tråden her, men du er velkommen til at genåbne den, hvis du har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
