### ISSUE TITLE
Skal det lægges i en tabel?

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#188]
Hej

Jeg er i gang med en selvbetjeningsløsning, hvor brugerne skal fordele nogle puljemidler på en række år. Kan jeg lave designet på denne måde:

![image](https://user-images.githubusercontent.com/54175531/189601578-63875e04-0002-45cf-95d6-94af20d67342.png)

eller skal det lægges i en tabel? 

Løsningen er brugervenlighedstestet med vedhæftede design, og det virkede rigtig godt ;)

På forhånd tak for hjælpen
Kirsten

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Tak for dit spørgsmål. Her er nogle overvejelser om hhv. løsning med og uden tabel.

**“Simpel” løsning med felter**

Det er altid svært at vejlede uden at kende hele konteksten, men ifølge vores retningslinjer placeres labels altid over felterne frem for ved siden af, da dette er hurtigere for brugeren at scanne (dette er best practice). Vær dog opmærksom på, at [suffix](https://designsystem.dk/komponenter/felter/#prefix-og-suffix) af hensyn til tilgængeligheden ikke må være eneste indikator på, hvordan et felt skal udfyldes. Det bør altså også fremgå af fx label eller en hjælpetekst, at der er tale om beløb i kr. 

Hvis I vælger en simpel løsning med inputfelter kan I i øvrigt overveje at anvende vores [facitstreger](https://designsystem.dk/design/borders/#streger), hvis I ønsker at fremhæve summen under felterne yderligere.


**Løsning med felter i tabel**

Vi kan godt forestille os, at en tabelløsning ville fungere godt i jeres tilfælde. Når jeres løsning har testet godt, er det muligvis fordi, opstillingen gør det lettere at sammenholde tal i samme “kolonne”. Denne fordel vil en tabelopsætning også give, og muligvis endnu tydeligere. Det kunne fx se sådan ud:

<img width="438" alt="Screenshot 2022-09-13 at 12 52 43" src="https://user-images.githubusercontent.com/44367338/189885407-e0b34e07-1b63-4288-838d-9c9863fc1029.png">

Med andre ord: Hvis det er vigtigt, at årstal står ved siden af felterne, så skal det være i en tabel.

På nuværende tidspunkt har vi ingen officielle retningslinjer for felter i tabeller, men det er et tema, vi har på vores to do-liste.

Vi håber, vores overvejelser hjælper jer videre.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by KirstenTo** [comment]
Hej Mette

Mange tak for hurtigt svar - vi går med tabellen 😊

Venlig hilsen
Kirsten Tønnesen
[Adobe Systems]
Digitaliseringskonsulent  ·  Digital Udvikling
Direkte nummer 29726005
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem ***@***.***>
Sendt: 13. september 2022 13:07
Til: detfaellesdesignsystem/dkfds-components ***@***.***>
Cc: Kirsten Tønnesen - KT ***@***.***>; Author ***@***.***>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Skal det lægges i en tabel? (Issue #188)


Hej Kirsten

Tak for dit spørgsmål. Her er nogle overvejelser om hhv. løsning med og uden tabel.

“Simpel” løsning med felter

Det er altid svært at vejlede uden at kende hele konteksten, men ifølge vores retningslinjer placeres labels altid over felterne frem for ved siden af, da dette er hurtigere for brugeren at scanne (dette er best practice). Vær dog opmærksom på, at suffix<https://designsystem.dk/komponenter/felter/#prefix-og-suffix> af hensyn til tilgængeligheden ikke må være eneste indikator på, hvordan et felt skal udfyldes. Det bør altså også fremgå af fx label eller en hjælpetekst, at der er tale om beløb i kr.

Hvis I vælger en simpel løsning med inputfelter kan I i øvrigt overveje at anvende vores facitstreger<https://designsystem.dk/design/borders/#streger>, hvis I ønsker at fremhæve summen under felterne yderligere.

Løsning med felter i tabel

Vi kan godt forestille os, at en tabelløsning ville fungere godt i jeres tilfælde. Når jeres løsning har testet godt, er det muligvis fordi, opstillingen gør det lettere at sammenholde tal i samme “kolonne”. Denne fordel vil en tabelopsætning også give, og muligvis endnu tydeligere. Det kunne fx se sådan ud:

[Screenshot 2022-09-13 at 12 52 43]<https://user-images.githubusercontent.com/44367338/189885407-e0b34e07-1b63-4288-838d-9c9863fc1029.png>

Med andre ord: Hvis det er vigtigt, at årstal står ved siden af felterne, så skal det være i en tabel.

På nuværende tidspunkt har vi ingen officielle retningslinjer for felter i tabeller, men det er et tema, vi har på vores to do-liste.

Vi håber, vores overvejelser hjælper jer videre.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Vi er glade for at kunne hjælpe. Sig endelig til en anden gang, hvis I har spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
