### ISSUE TITLE
Ikonforslag - Indlejrede lister

### ISSUE THREAD

**Issue by chce** [detfaellesdesignsystem/dkfds-components#189]
**Skyldes dit forslag et særligt behov eller et problem? Beskriv venligst. (Is your feature request related to a certain need or problem? Please describe.)**
Ikonforslag

**Beskriv det du gerne ser tilføjet til designsystemet (Describe the solution you'd like to add to the design system)**
Vi ønsker et ikon til at vise at noget er en træstruktur(Dvs. en liste med indlejrede lister), på samme måde som liste-ikonet viser at noget er en simpel liste.

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
Giv en kort og præcis beskrivelse af alle de alternativer du har overvejet og hvorfor du foreslår den løsning du gør. (A clear and concise description of any alternative solutions or features you've considered, and why you've settled on that solution.)

**Links til eksempler. (URLs with examples)**
Eksempel på ikon
https://www.iconfinder.com/icons/118646/list_nested_icon

**Comment by detfaellesdesignsystem** [comment]
Hej chce

Har du mulighed for at fortælle lidt om konteksten, hvor I har brug for ikonet? Fx. hvilken slags liste her er tale om, hvor ikonet skal sættes ind, og hvilke komponenter det skal bruges sammen med. 

Det vil gøre det lettere for os at vurdere ikonet.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by chce** [comment]
Vi ønsker at anvende det i relation til et komponent hvor vi har lister med indlejrede lister, dvs. noget i retning af dette, hvor listerne kan foldes ud med klik:

- Klassifikation 1
    - Underklassifikation 1-1
    - Underklassifikation 1-2
- Klassifikation 2
    - Underklassifikation 2-1
    - Underklassifikation 2-2
- Klassifikation 3

**Comment by detfaellesdesignsystem** [comment]
Hej chce

Jeg mente mere konteksten ift., hvilken rolle ikonet skal spille. Skal det blot illustrere listen, eller er det klikbart? Er det når man klikker på ikonet, at underpunkterne foldes ud?

Det ville være en stor hjælp, hvis du kunne vise en hurtig skitse af opbygningen inkl. ikonets placering og funktionalitet - det behøver ikke være pænt eller detaljeret :)

Venlig hilsen
Mette
Det fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi lukker tråden her, da der ikke er kommet yderligere kommentarer.
