### ISSUE TITLE
Badges og farver

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#19]
Hej dkfds,

Vi vil gerne bruge badges til at vise status på en borger selvbetjening (fx, ny, kladde, sendt).

Hvilke farver anbefaler I, vi skal bruge?
 
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/badges/

M.v.h.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Vi har ikke tænkt badges til sådanne statusbeskeder. Har du mulighed for at sende en mockup af det i arbejder på? Send det evt. til FDS@erst.dk, hvis det ikke er klar til deling endnu. Så bliver det lettere at foreslå noget konkret.

I skal altid anvende farver som er specificeret i designsystemet. Er der behov for nye farver, så skal vi have dem ind i systemet.

**Comment by FNA-atp** [comment]
Hej,
Tak for svar :-) en mail med billeder er sendt til FDS@erst.dk.

m.v.h.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej 

Det var så lidt. Fint at gøre det således, nu vi ikke har en dedikeret statuskomponent.

![image](https://user-images.githubusercontent.com/44367338/55148979-96719780-5149-11e9-97bd-f1b03398b337.png)

Jeg lukker issuet :)

Mvh
Sune
