### ISSUE TITLE
Brug af ikoner i cards?

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#190]
Hej
Jeg arbejder på en selvbetjening, hvor jeg har overtaget nedenstående cards, som vises på en overbliksside. Langt de fleste brugere vil kun se ét card ad gangen:
![image](https://user-images.githubusercontent.com/54175531/190148458-65830ba5-0cb2-472d-85f4-4b8f1197ec18.png)

Vedr. det første/det røde card:
En af udviklerne har gjort mig opmærksom på, at der ikke findes et rundt ikon med et udråbstegn i FDS, medmindre vi drejer i-ikonet 180 grader - er det ok, eller kan vi bruge det trekantede advarselsikon, selvom der er anvendt rød som beskedfarve i cardet?

På forhånd tak for hjælpen :)
Kirsten

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo 

Tak for din henvendelse!

Helt generelt så gælder der, at hvis der ikke findes et passende ikon i [oversigten](https://designsystem.dk/design/ikoner/#betydning), så henviser vi til [Material Icons](https://material.io/tools/icons/?style=outline) og [Material Design Icons](https://materialdesignicons.com/), hvor der er flere muligheder. 

Vi har dog, som du selv nævner, allerede et ikon for advarsel. Det bruges ganske rigtigt sammen med den gule farve, mens rød bruges ved fejl og fejlbeskeder (der findes et tilsvarende fejl-ikon, som bruges sammen med den røde farve).

Skal den røde besked i kortet her betragtes som en advarsel, en fejl eller noget helt andet (fx en status)?

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by KirstenTo** [comment]
Hej Helle

Tak for hurtigt svar.

Tanken er, at det røde kort er en kraftig reminder – brugerne skal lægge mærke til, at der er en vigtig handling, de skal foretage.

Personligt ville jeg have brugt gul + advarselstrekant i stedet for det røde card, og så brugt blå til det gule card, men jeg vil ikke ændre det oprindelige design, hvis der ikke er grund til det.

Jeg kan se, at der i Material Icons findes en Alert, der er rund og med udråbstegn, men jeg er stadig usikker på, om det er ok at bruge den og den røde farve til advarslen?

Venlig hilsen
Kirsten Tønnesen
[Adobe Systems]
Digitaliseringskonsulent  ·  Digital Udvikling
Direkte nummer 29726005
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem ***@***.***>
Sendt: 15. september 2022 13:00
Til: detfaellesdesignsystem/dkfds-components ***@***.***>
Cc: Kirsten Tønnesen - KT ***@***.***>; Mention ***@***.***>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Brug af ikoner i cards? (Issue #190)


Hej @KirstenTo<https://github.com/KirstenTo>

Tak for din henvendelse!

Helt generelt så gælder der, at hvis der ikke findes et passende ikon i oversigten<https://designsystem.dk/design/ikoner/#betydning>, så henviser vi til Material Icons<https://material.io/tools/icons/?style=outline> og Material Design Icons<https://materialdesignicons.com/>, hvor der er flere muligheder.

Vi har dog, som du selv nævner, allerede et ikon for advarsel. Det bruges ganske rigtigt sammen med den gule farve, mens rød bruges ved fejl og fejlbeskeder (der findes et tilsvarende fejl-ikon, som bruges sammen med den røde farve).

Skal den røde besked i kortet her betragtes som en advarsel, en fejl eller noget helt andet (fx en status)?

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Den røde farve som signalfarve og tilhørende ikon anvendes til deciderede fejl, hvilket der ikke er tale om her. 

Jeg synes, du har fat i noget helt rigtigt, når du foreslår at anvendes advarselsfarve (gul) + advarselsikon i stedet for rød. Det midterste card vil jeg anbefale at holde helt simpelt i hvid eller evt. lys grå, da en farve ikke vil signalere noget særligt her. Det er "neutralt".

Du siger, du ikke vil ændre det oprindelige design, hvis der ikke er grund til det. Men jeg mener, der er god grund til det.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by KirstenTo** [comment]
Hej Mette

Mange tak for hjælpen 😊

Jeg har ændret det røde card til et gult med en advarselstrekant.

Mht. det midterste card testede jeg med en lys grå og den lyseblå, men det grå card fik ikke den ønskede reaktion.
Brugerne troede ikke, at de skulle/kunne gøre noget, når det hele var gråt, så derfor har jeg valgt den blå info-farve til cardet.

***@***.***

Venlig hilsen
Kirsten Tønnesen
***@***.***
Digitaliseringskonsulent  ·  Digital Udvikling
Direkte nummer 29726005
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem ***@***.***>
Sendt: 19. september 2022 13:17
Til: detfaellesdesignsystem/dkfds-components ***@***.***>
Cc: Kirsten Tønnesen - KT ***@***.***>; Mention ***@***.***>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Brug af ikoner i cards? (Issue #190)


Hej Kirsten

Den røde farve som signalfarve og tilhørende ikon anvendes til deciderede fejl, hvilket der ikke er tale om her.

Jeg synes, du har fat i noget helt rigtigt, når du foreslår at anvendes advarselsfarve (gul) + advarselsikon i stedet for rød. Det midterste card vil jeg anbefale at holde helt simpelt i hvid eller evt. lys grå, da en farve ikke vil signalere noget særligt her. Det er "neutralt".

Du siger, du ikke vil ændre det oprindelige design, hvis der ikke er grund til det. Men jeg mener, der er god grund til det.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Det lyder som en god løsning, I har fundet. Tusind tak for at dele jeres efaringer med den grå farve med os!

Jeg lukker issuet her, men du er velkommen til at genåbne, hvis I har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
