### ISSUE TITLE
Brødtekst vs. hjælpetekst ifm. spørgsmål

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#191]
Hej 

Ifm. en ny selvbetjeningsløsning til faglige udvalg er der opstået et behov for at tilføje en uddybende tekst til nogle af spørgsmålene. Jeg tænker disse som en brødtekst, som brugerne skal læse og vil derfor gerne bruge sort brødtekst (#1A1A1A), men min frontend-afdeling siger, at de skal skrives som hjælpetekst (#747474). 

Jeg synes, at hjælpeteksten kan bruges, når der er tale om en meget kort, nice-to hjælp (maks. én linje) som på siden https://designsystem.dk/pages/eksempler/digital-flytning/flytning-3/?r=/eksempler/selvbetjeningsloesninger/%23digital-flytning
men når der er flere linjer. som uddyber spørgsmålet og gerne skal læses, virker den for diskret. 

Jeg har for nyligt været med til at teste en anden kommende selvbetjeningsløsning, hvor der bruges hjælpetekster, og der var flere eksempler på, at brugerne ikke læste de grå tekster, selvom de faktisk havde brug for informationen. Da denne løsning blev testet, var de uddybende tekster skrevet som brødtekst, og det virkede til gengæld fint.

Her er et skærmprint fra løsningen, hvor jeg gerne vil bruge sort brødtekst i stedet for den viste grå hjælpetekst:
![image](https://user-images.githubusercontent.com/54175531/190859415-daac4a3f-159f-4464-b8f4-a5bfb82091dc.png)

På forhånd tak for hjælpen
Kirsten

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

I Det Fælles Designsystem er hjælpeteksterne simpelthen grå, hvilket hjælper til at visualisere hierarkiet mellem label og hjælpetekst.

Når jeg ser jeres eksempel, vil jeg mere være bekymret for, om brugerne springer over hjælpeteksterne netop fordi de er meget lange. Dele af hjælpeteksterne lader til at gentage feltets label i en vis grad, hvilket kan medføre, at informationen virker mindre relevant for brugeren. Jeg vil derfor kraftigt opfordre jer til at overveje, om ikke hjælpeteksterne kan forkortes, uden at vigtig information går tabt. Her er et umiddelbart forslag:

<img width="653" alt="Screenshot 2022-09-19 at 12 33 20" src="https://user-images.githubusercontent.com/44367338/190999614-54a82a3d-c659-4434-9e40-e3540b02cd8d.png">

Jeg har i eksemplet ikke inkluderet detaljeelementet, da jeg ikke er sikker på, hvad den gør i dette tilfælde. Detaljeelementet bruges typisk ikke på den måde mellem labels og felter, så I må meget gerne vise, hvad man ser, når de foldes ud.  

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by KirstenTo** [comment]
Hej Mette

Mange tak for dit svar 😊

Vil det være muligt at booke dig til et Teams-møde nu på torsdag den 6. oktober kl. 14?

Mine kolleger og jeg har en del spørgsmål til dit svar, og det er nok mere effektivt at mødes end at maile frem og tilbage 😊

Venlig hilsen
Kirsten Tønnesen
[Adobe Systems]
Digitaliseringskonsulent  ·  Digital Udvikling
Direkte nummer 29726005
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem ***@***.***>
Sendt: 19. september 2022 12:38
Til: detfaellesdesignsystem/dkfds-components ***@***.***>
Cc: Kirsten Tønnesen - KT ***@***.***>; Author ***@***.***>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Brødtekst vs. hjælpetekst ifm. spørgsmål (Issue #191)


Hej Kirsten

I Det Fælles Designsystem er hjælpeteksterne simpelthen grå, hvilket hjælper til at visualisere hierarkiet mellem label og hjælpetekst.

Når jeg ser jeres eksempel, vil jeg mere være bekymret for, om brugerne springer over hjælpeteksterne netop fordi de er meget lange. Dele af hjælpeteksterne lader til at gentage feltets label i en vis grad, hvilket kan medføre, at informationen virker mindre relevant for brugeren. Jeg vil derfor kraftigt opfordre jer til at overveje, om ikke hjælpeteksterne kan forkortes, uden at vigtig information går tabt. Her er et umiddelbart forslag:

[Billede fjernet af afsender. Screenshot 2022-09-19 at 12 33 20]<https://user-images.githubusercontent.com/44367338/190999614-54a82a3d-c659-4434-9e40-e3540b02cd8d.png>

Jeg har i eksemplet ikke inkluderet detaljeelementet, da jeg ikke er sikker på, hvad den gør i dette tilfælde. Detaljeelementet bruges typisk ikke på den måde mellem labels og felter, så I må meget gerne vise, hvad man ser, når de foldes ud.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Det kan vi godt finde ud af, jeg har et hul i kalenderen på det tidspunkt.

Vil du være sød at sende en mail til FDS@erst.dk? Så har vi din email og kan sende en mødeindkaldelse retur.

Venlig hilsen
Mette
Det Fælles Designsystem
