### ISSUE TITLE
Review af navigation

### ISSUE THREAD

**Issue by LLP-atp** [detfaellesdesignsystem/dkfds-components#193]
Hej med jer

Jeg arbejder på nogle ændringer i en selvbetjeningsløsning, hvor vi forventer, der kommer en lovændring. Rent konkret betyder det, at en ordning (kaldet xxxxx) fremadrettet vil blive opkrævet gennem en anden ordning (kaldet yyyyy). Data er anonymiseret, da loven ikke er fremsat endnu. 

Lovændringen vil betyde ændringer for xxxxx selvbetjeningsløsning, hvor man fremadrettet skal over i yyyyy selvbetjeningsløsning for at se data for xxxxx. Samtidig vil der komme et arkiv i xxxxx selvbetjeningsløsning, hvor man kan se historiske data. 

Jeg vil gerne sparre med jer ift. navigation i xxxxx selvbetjeningsløsning på Virk. Jeg kunne godt tænke mig at lave en samlet menu i xxxxx selvbetjeningsløsning, som indeholder en overflowmenu. I overflowmenuen kan man tilgå arkivsiden. Når jeg klikker på menuen 'Opkrævning og betaling af xxxxxxxx', vil jeg gerne have, at man ser en side med tre cards. De tre cards har følgende funktion:

- **Card 1:** Link til yyyyy selvbetjeningsløsning, hvor man fremadrettet skal håndtere nogle ting vedr. xxxxx. Årsagen til, hvorfor man skal over i en ny selvbetjeningsløsning, er kort forklaret. Linket åbner i en ny fane, og hvis man har adgang til yyyyy selvbetjeningsløsning, bliver man automatisk logget ind her. 
- **Card 2:** Link til arkivside i den samme selvbetjeningsløsning, som man befinder sig i. Det er den arkivside, der også kan tilgås fra overflowmenuen. 
- **Card 3:** Link til yyyy selvbetjeningsløsning, hvor man fremadrettet skal tilmelde sig automatisk betaling af xxxxx. Kort forklaring om hvorfor. Linket åbner i en ny fane, og hvis man har adgang til yyyyy selvbetjeningsløsning, bliver man automatisk logget ind her. 

Her er en anonymiseret mockup af, hvordan det vil se ud: 

![image](https://user-images.githubusercontent.com/110180975/191925318-a0f21e64-cf49-4514-8ba5-30b912f52d50.png)

Jeg har bevidst valgt at style links som linjer og ikke knapper, så jeg kan benytte ikonet for links ud af løsningen. Jeg har gjort det konsekvent for alle tre links, da en knap i det midterste card vil trække for meget opmærksomhed, og det giver en mere ensartet styling. 

Må jeg gerne gøre det på denne måde? Jeg anser ikke de to cards, som henviser til den anden selvbetjeningsløsning, som primær navigation. Formålet er kort at oplyse om, hvorfor man skal et andet sted hen og sørge for, at brugeren nemt kan komme derhen. Derfor vil jeg gerne undgå, at de skal ligge i deres egen menu, da det vil give mange menuer, som egentlig bare har til formål at oplyse brugerne om, at de skal et nyt sted hen. Derfor vil vi gerne samle det hele i samme menu med visning af de tre cards på siden, da alle tre cards vedrører samme overordnede emne.

**Comment by LLP-atp** [comment]
Hej igen

Det er, om man gerne må lave den form for fordelingsside, jeg har lavet, hvor jeg samler tre områder på én side og bruger cards til den videre navigation. Men det lyder det til, at der ingen problemer er i, så det er jo bare godt :)

**Comment by detfaellesdesignsystem** [comment]
Hej igen

Umiddelbart ser vi ingen problemer i den form for navigation, du viser. Jeg lukker derfor issuet her, men du er velkommen til at genåbne det, hvis du har flere spørgsmål.

Venlig hilsen
Mette
Det Fælles Designsystem
