### ISSUE TITLE
Fejl i package.json - incorrect main specified in package.json

### ISSUE THREAD

**Issue by kaety** [detfaellesdesignsystem/dkfds-components#194]
**Bekskriv fejlen (Describe the bug)**
Jeg prøver at importere dkfds npm pakken med nyeste vue3 og vitejs. Jeg får en fejl vid vites typecheck af package.json.

Det er række 9 i package.json som er problematisk.
`  "jsnext:main": "src/js/start.js",`
start.js ser ud til at være en gammel fil som ikke længere eksisterer. Tilretter eller fjerner jeg rækken så kan jeg godt importere dkfds og projektet bygges med succes.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. ```npm init vue@latest``` (skaber vue eksempel projekt)
2. ```cd projektnavn``` + ```npm install```
3. ```npm install dkfds```
4. tilføj ```import * as DKFDS from "dkfds";``` og ```DKFDS.init()``` til App.vue
5. npm run build
6. See error
```
[commonjs--resolver] Failed to resolve entry for package "dkfds". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "dkfds". The package may have incorrect main/module/exports specified in its package.json
```

**Sådan burde det fungere (Expected behavior)**
Burde bygge uden fejl

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows
 - DKFDS version 8.0.1 
 - NPM version 8.15.0
 - Node version 16.17.0

**Comment by detfaellesdesignsystem** [comment]
Hej @kaety 

Tak for din henvendelse!

Du har helt ret i, at der er tale om en gammel fil, som ikke længere eksisterer. Jeg har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by Minibrams** [comment]
Bliver det fikset inden alt for længe? Alternativt kan I åbne op for PRs, så laver jeg med glæde et fix 👍 

Indtil da, til dem der falder over samme fejl, har jeg forket `dkfds-components` på [Minibrams/dkfds-components](https://github.com/Minibrams/dkfds-components). Pakken inkl. fix til ovenstående kan installeres med:

```bash
npm install --save @minibrams/dkfds
```

**Comment by detfaellesdesignsystem** [comment]
Hej @Minibrams 

Linjen bliver fjernet ved næste release.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
