### ISSUE TITLE
Delt cookie-consent?

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [detfaellesdesignsystem/dkfds-components#196]
Hej DKFDS

Ved I om det er muligt for en selvbetjeningsløsning, at dele cookie-consent med borger.dk og virk.dk?

Alternativet er jo at brugerne to gange (på borger.dk/virk.dk og den selvbetjeningsløsning de ender på) skal forholde sig til cookies, selvom de jo bør opleve rejsen til en selvbetjeningsløsning som ubrudt.

På forhånd tak!

Mvh.
Anders

**Comment by detfaellesdesignsystem** [comment]
Hej @AndersWinther-Dahl 

Tak for din henvendelse!

Jeg tænker, at det først og fremmest er et spørgsmål om, hvad cookiereglerne tillader. Prøv at se om du kan finde et svar på https://erhvervsstyrelsen.dk/cookieregler eller https://www.borger.dk/Om-borger-dk/Jura-cookies-og-tilgaengelighed/Cookies, ellers kan du prøve at kontakte Erhvervsstyrelsen, da det er dem, der vejleder om denne lov.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by AndersWinther-Dahl** [comment]
Hej Helle
Muligvis vi taler forbi hinanden, og måske I ikke er de rigtige at spørge. Jeg kan bare ikke komme i tanke om andre, der binder borger.dk og virk.dk sammen.

Mit spørgsmål er om det er teknisk muligt at dele _consent_ på tværs af domæner?

Jeg har tidligere anvendt https://cookieinformation.com/, der er en service der gør det nemt at lave _cookie-consent_ på sine løsninger. De tilbyder nemlig at flere domæner og subdomæner kan dele samme _consent_.
Det smarte er, at brugeren ikke skal spørges for _consent_ flere gange, men at man kan bruge samme svar på alle domænerne.

Det ville jo også være oplagt i dette tilfælde, hvor borgeren eller virksomheden allerede har givet sit _consent_ på borger.dk eller virk.dk.

Håber det står mere klart nu :-)

Mvh.
Anders

**Comment by simmelhack** [comment]
Hej Anders

Kan du sende dit spørgmål til Virk Myndighedsteam  ***@***.******@***.***> fra din arbejdsmail, så lover jeg du får et svar.

Gode hilsner
Charlotte


Charlotte Simmelhack
Teamleder

ERHVERVSSTYRELSEN
Administration og digitalisering

Dahlerups Pakhus
Langelinie Allé 17
2100 København Ø
Telefon: +45 35291000
Direkte: +45 35291937
E-mail: ***@***.***
www.erhvervsstyrelsen.dk

ERHVERVSMINISTERIET

Erhvervsstyrelsen er ansvarlig for behandlingen af de personoplysninger, vi modtager om dig. Læs mere om formål og lovgrundlag for databehandlingen på erhvervsstyrelsen.dk<https://erhvervsstyrelsen.dk/privatlivspolitik>.
Hvis du sender følsomme oplysninger, opfordrer vi til, at du bruger din digitale postkasse på Virk<https://hjaelp.virk.dk/digital-post>.



Fra: Anders Winther-Dahl ***@***.***>
Sendt: 12. oktober 2022 12:45
Til: detfaellesdesignsystem/dkfds-components ***@***.***>
Cc: Subscribed ***@***.***>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Delt cookie-consent? (Issue #196)


Hej Helle
Muligvis vi taler forbi hinanden, og måske I ikke er de rigtige at spørge. Jeg kan bare ikke komme i tanke om andre, der binder borger.dk og virk.dk sammen.

Mit spørgsmål er om det er teknisk muligt at dele consent på tværs af domæner?

Jeg har tidligere anvendt https://cookieinformation.com/, der er en service der gør det nemt at lave cookie-consent på sine løsninger. De tilbyder nemlig at flere domæner og subdomæner kan dele samme consent.
Det smarte er, at brugeren ikke skal spørges for consent flere gange, men at man kan bruge samme svar på alle domænerne.

Det ville jo også være oplagt i dette tilfælde, hvor borgeren eller virksomheden allerede har givet sit consent på borger.dk eller virk.dk.

Håber det står mere klart nu :-)

Mvh.
Anders

**Comment by AndersWinther-Dahl** [comment]
Det gør jeg. GitHub skjuler åbenbart email-adresser, men jeg antager det er denne:

![image](https://user-images.githubusercontent.com/10073411/195342840-eaa36b3f-51e0-4f63-a702-dfbe6ccfa9e2.png)
