### ISSUE TITLE
DKFDS.datePicker.setLanguage does not exist

### ISSUE THREAD

**Issue by martynasmartynas** [detfaellesdesignsystem/dkfds-components#198]
As per instructions [here](https://designsystem.dk/kode/komponenter/datovaelger/), I am trying to setup different languages for date input component, but it says that setLanguage does not exist. 

Can you help me to make multilingual datePicker?

**Comment by detfaellesdesignsystem** [comment]
Hello @martynasmartynas 

Thank you for writing!

Are you using the latest version of DKFDS? If yes, please check whether the function "setLanguage" is in your "dkfds.js" file (try searching for "setLanguage") and we will take it from there.

Best regards
Helle Juhl
Det Fælles Designsystem

**Comment by martynasmartynas** [comment]
Yes, that worked. Sorry about that :)
