### ISSUE TITLE
Opdatering/migrering fra @import til @use i .scss-filer

### ISSUE THREAD

**Issue by chce** [detfaellesdesignsystem/dkfds-components#199]
[Brug denne type issues, når der ikke er tale om fejl, men om opdateringer og forbedringer af eksisterende kode/beskrivelser/eksempelvisninger. (Use this issue type for updates and improvements to the code/descriptions/examples that are not bugs.)] 

**Navn i designsystemet (Feature name in the design system)**
Styling

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Når man skal definere et tema i DKFDS, hvis man gerne vil bruge styling specifikt for f.eks. accordions i et isoleret komponent, eller hvis man vil bruge nogle af de funktioner, som I har i core-mappen, er man nødt til at importere hele SCSS-biblioteket i filen med den snart-deprecatede @import-syntaks. Det gør det svært at splitte koden og kun anvende lige præcis det man har brug for i f.eks. en Shadow DOM eller et CSS-modul.

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
At koden opdateres til at anvende @use eller @forward i stedet, hvilket er hvad Sass-holdet foreslår som alternativ til @import.
Sass-holdet har udviklet et værktøj til at migrere, som kan lave meget af arbejdet:
https://sass-lang.com/documentation/cli/migrator
Derudover skal man løse de cirkulære afhængigheder.
**Jeg laver gerne et pull request her på Github med en kørsel af sass-migrator + løsning af cirkulære afhængigheder og evt. andre problemer, men rettelsen kommer til at påvirke størstedelen af .scss-filerne**

**Supplerende bemærkninger (Additional context)**
https://sass-lang.com/documentation/at-rules/import
"The Sass team discourages the continued use of the @import rule. Sass will [gradually phase it out](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline) over the next few years, and eventually remove it from the language entirely. Prefer the [@use rule](https://sass-lang.com/documentation/at-rules/use) instead. (Note that only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.)"

**Comment by detfaellesdesignsystem** [comment]
Hej @chce 

Tak for henvendelsen!

Vi har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @chce 

Koden er opdateret i version 10.0.0, hvor <code>@import</code> ikke længere anvendes.

Med venlig hilsen
Det Fælles Designsystem
