### ISSUE TITLE
Mangler fokus ramme på faneblade/tabs

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#20]
**Mangler visuel fokus**
Screenreader har fokus og læser tabs korrekt op, men vi mangler visuel fokus-ramme på faneblade/tabs. 

![image](https://user-images.githubusercontent.com/25169794/54594438-f624c000-4a30-11e9-8985-d4c1e903d206.png)

Fokus virker fint i header menuen, men ikke på faneblade 
![image](https://user-images.githubusercontent.com/25169794/54594618-4f8cef00-4a31-11e9-902b-2f6b7c8962cf.png)

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Gå til 'https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tabnav/?s=virkdk'
2. Tabulering over faneblade 

Med venlig hilsen 
Laura Beck
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Vi har fikset fejlen. Fikset vil være med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
