### ISSUE TITLE
Datovælger nævner forkert dato ved brug af skærmlæser 

### ISSUE THREAD

**Issue by meier-andersen** [detfaellesdesignsystem/dkfds-components#201]
**Bekskriv fejlen (Describe the bug)**
Når man benytter Datovælger komponenten med en skærmlæser nævnes den forkerte ugedag. 

**Genskab fejlen (To Reproduce)**
- Installer en skærmlæser, f.eks. NVDA eller JAWS 
- Tilgå Datovælger komponenten https://designsystem.dk/eksempel/date-picker/
- Åben datovælgeren med skærmlæseren 
- Skift imellem datoerne

Forventet: 
- Ugedagen der læses op matcher den givne dag 

Observeret: 
- Ugedagen er 1 dag foran. 
- - fredag den 11. november oplæses "Lørdag den 11 November 2022" 
- - mandag den 14. november oplæstes "Tirsdag den 14. November 2022"

![image](https://user-images.githubusercontent.com/34266014/201641405-6b5dff1f-c3d7-4071-a3c0-2dd5641465e9.png)

![image](https://user-images.githubusercontent.com/34266014/201641541-cc2c80dd-3068-449f-9f33-173e59b2395c.png)

**Indsæt link (Add a URL)**
https://designsystem.dk/eksempel/date-picker/

**Screenshots**
![image](https://user-images.githubusercontent.com/34266014/201641405-6b5dff1f-c3d7-4071-a3c0-2dd5641465e9.png)

![image](https://user-images.githubusercontent.com/34266014/201641541-cc2c80dd-3068-449f-9f33-173e59b2395c.png)

**Sådan burde det fungere (Expected behavior)**
Beskriv om muligt, hvordan fejlen løses eller beskriv klart og præcist hvordan det burde fungere. (A clear and concise description of what you expected to happen.)

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows 10 Enterprise 
 - Browser Chrome + JAWS, Firefox + NVDA 
 - Version DKFDS 8.0.1 + DKFDS 8.2.0

**Comment by detfaellesdesignsystem** [comment]
Hej @meier-andersen 

Fejlen er blevet løst i version 9.0.0.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
