### ISSUE TITLE
Disabled checkbox giver kontrast alerts

### ISSUE THREAD

**Issue by MiracleAndreasHolm** [detfaellesdesignsystem/dkfds-components#202]
**Bekskriv fejlen (Describe the bug)**
Hej FDS.
Vi ved Optagelse.dk bruger selvfølgelig jeres checkboxe: https://designsystem.dk/komponenter/tjekboks/
Når disse er disabled bliver teksten grå, hvilket resulterer i at kontrasten falder. Dette giver fejl når vi tester vores tilgængelighed.
Man kan endda i jeres dokumentation (https://designsystem.dk/eksempel/checkbox-large/) se problemstillingen.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Go to https://designsystem.dk/eksempel/checkbox-large/
2. Tjekboks 4's tekst er grå og hvilket under brug af feks. "Wave" giver contrast errors.

**Indsæt link (Add a URL)**
https://designsystem.dk/eksempel/checkbox-large/

**Screenshots**
![image](https://user-images.githubusercontent.com/88316760/205072920-c612b0bc-c88d-4c2f-bb3c-9a7403b225af.png)

**Sådan burde det fungere (Expected behavior)**
- Hvordan man ellers skal symboliserer det, ved jeg desværre ikke, jeg ved blot at den lave kontrast giver errors.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - Browser: Ligegyldigt hvilken browser der bruges.

**Smartphone - udfyld venligst følgende (please complete the following information):**
- Fejlen opleves på alle smartphones.

**Supplerende oplysninger (Additional context)**
- Intet at tilføje.

**Comment by detfaellesdesignsystem** [comment]
Hej @MiracleAndreasHolm 

Tak for din henvendelse!

Når et element er inaktivt, fx disabled, så [bortfalder de normale kontrastkrav i WCAG-kriterie 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#inactive-controls). Jeg vil derfor mene, at der i dette tilfælde er tale om en fejl i Wave-værktøjet.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by MiracleAndreasHolm** [comment]
Hej @HEF-NC,
Mange tak for dit svar og din tilhørende dokumentation.
Det er information jeg deler ud til vores teams.

Mvh. Andreas Holm
