### ISSUE TITLE
Låste punkter i venstremenu ser til forveksling ud som ikke låst

### ISSUE THREAD

**Issue by morthanh** [detfaellesdesignsystem/dkfds-components#204]
**Navn i designsystemet (Feature name in the design system)**
Venstremenu/trinindikator

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Når man benytter låste punkter i venstremenu sammen med ikke låste så er farveforskellen ikke stor nok til at man tydligt kan se forskel på om menupunktet er låst eller ej. Man kan som bruger selvfølgelig se det når musen hover over punktet, men det burde ikke være nødvendigt for at vide om punktet er låst eller ej. Det bør kunne ses med det samme. 

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Har forsøgt med at benytte border i venstre side (samme måde som der gøres for at vise det aktive menupunkt) men med en grå farve istedet. Den farve som bruges til fonten er dog for kraftig i min optik, så har prøvet mig frem til #c2c2c2 i stedet. Se neders for eksempel

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
Alternativt kunne baggrundens farve ændres, men det vil måske være for fremhævende. 

**Supplerende bemærkninger (Additional context)**
Eksempel på venstremenu hvor nederste punkt er disabled
![image](https://user-images.githubusercontent.com/2750357/211309915-684caeed-0250-496e-8e5f-c73bbac6115b.png)

Forslag til styling på disabled menupunkt
![image](https://user-images.githubusercontent.com/2750357/211307669-bbdf6459-9c35-4683-9571-9a138f14e76e.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @morthanh 

Tak for henvendelsen!

Vi har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @morthanh 

Problemet er løst i version 10.0.0.

Med venlig hilsen
Det Fælles Designsystem
