### ISSUE TITLE
Skærmlæsere fejler på alerts

### ISSUE THREAD

**Issue by stil-sds** [detfaellesdesignsystem/dkfds-components#205]
Hej,

Vi har registreret at skærmlæsere ikke læser alerts - hverken i vores egen implementering eller på designsystem.dk. Det er en central fejl for os, da vi anvender alerts til at guide / informere ansøgere i deres ansøgningsproces.

Det burde virke fuldkommen som alle andre komponenter / indhold, men skærmlæseren springer over alert og så vidt jeg kan se, kan man heller ikke tabbe sig ind i indholdet.

Det virker med Adgang for alle, men når vi tester med fx Apples tilgængelighedsværktøj læses indholdet i en alert ikke op. Det samme gælder for Windows egen skærmlæser. 

Kan I bekræfte vores observationer ? 

På forhånd tak

John, STIL.

**Comment by detfaellesdesignsystem** [comment]
Hej @stil-sds 

Tak for henvendelsen!

Er det [beskeder](https://designsystem.dk/komponenter/beskeder/) eller [toastbeskeder](https://designsystem.dk/komponenter/toastbesked/), I anvender?

Har I evt. et billede fra jeres løsning, der viser det indhold, I gerne vil kunne tabbe til?

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by stil-sds** [comment]
Hej! Tak for respons. Fejlen var vores egen manglende forståelse for en skærmlæser. Jeg lukker sagen med det samme.
Bh
John
