### ISSUE TITLE
Tabel med både udfoldelige rækker og valgbare rækker

### ISSUE THREAD

**Issue by LLP-atp** [detfaellesdesignsystem/dkfds-components#206]
Hej med jer

Jeg har designet en tabel, der både har udfoldelige rækker og valgbare rækker på en side i en selvbetjeningsløsning, der ikke er publiceret endnu. Men jeg er i tvivl om, hvor jeg skal placere hhv. +ikonerne, der angiver, at man kan folde rækkerne ud, og hvor jeg skal placere checkboxes. I FDS lægges der jo op til, at de hver for sig altid placeres i venstre side, men jeg kan ikke finde eksempler på, hvor de skal placeres, når man benytter begge to samtidig. Derfor har jeg lige nu designet det sådan her:

![image](https://user-images.githubusercontent.com/110180975/212681134-e2cca462-09ab-4b92-a109-d29e81133d1a.png)

Men bør checkboxes ligge i første kolonne til venstre efterfulgt af +tegnet? Evt. med en tydelig separator mellem de to? Altså sådan her:

![image](https://user-images.githubusercontent.com/110180975/212682052-b7c00c56-01f9-416f-806e-603f281df3f6.png)

Når rækken er foldet ud, ser det ud på denne måde i første designeksempel:

![image](https://user-images.githubusercontent.com/110180975/212682238-367320a0-2289-4507-8c92-42b9f4ee5d52.png)

Og sådan her i andet designeksempel:

![image](https://user-images.githubusercontent.com/110180975/212683257-d3629ea5-bc54-43cf-87b7-fd0d52af5b14.png)

Må jeg lave det på én af to ovenstående måder?

På forhånd tak!

Vh Louise

**Comment by detfaellesdesignsystem** [comment]
Hej @LLP-atp 

Tak for din henvendelse!

Vi tager et kig på dine forslag og vender tilbage snart.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @LLP-atp 

Så har vi fået vendt jeres forslag. Vi har ingen retningslinjer for jeres specifikke scenarie, men af jeres to forslag, så synes vi bedst om den sidste løsning, hvor både plusikoner og tjekbokse ligger i venstre side.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
