### ISSUE TITLE
Single-selectable accordions virker ikke

### ISSUE THREAD

**Issue by jkruse** [detfaellesdesignsystem/dkfds-components#207]
Hvis man laver en accordion uden klassen "accordion-multiselectable", så burde resultatet være at når man åbner én sektion, så lukker en eventuel anden åben sektion, og komponenten indeholder kode der skal gøre netop det, men koden indeholder en fejl i denne linje:

https://github.com/detfaellesdesignsystem/dkfds-components/blob/6751b0d9ded0f66e68db5ce4f609a958dc5754fb/src/js/components/accordion.js#L159

Specifikt skulle `currentButtton.getAttribute('aria-expanded' === true)` nok have været `currentButtton.getAttribute('aria-expanded') === 'true'`. Og så kan man diskutere om der er tre t'er i "button".

**Comment by detfaellesdesignsystem** [comment]
Hej @jkruse 

Tak for din henvendelse!

I den kommende release (version 9.0.0) ændres accordions til udelukkende at være multi-selectable, hvor de fejlbehæftede kodelinjer vil være fjernet.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Version 9.0.0 er nu blevet releaset og koden for accordions er blevet opdateret.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
