### ISSUE TITLE
Responsive Modal - style on small devices

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#21]
**Responsive Modal - style on small devices**

Har I mulighed for at tilføje en styling på den responsive modal, således at header eller content ikke bliver gemt bag luk knappen ?

Link: https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/modals/

**Screenshots**
![image](https://user-images.githubusercontent.com/25169794/54687002-d79af380-4b1a-11e9-9273-df1091ed09f8.png)

 **Midlertidigt fix** 
Som et hurtigt fix har vi anvendt [hjælpeklasserne](https://detfaellesdesignsystem.github.io/dkfds-docs/design/utility/) ` pr-9 pr-lg-0` på` class="modal__title"`, indtil vi hører nærmere fra jer. 

Med venlig hilsen 
Laura Beck 
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin ,

Vi har indført et fix, som vil være med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
