### ISSUE TITLE
Modal "hide" funktion checker ikke om backdrop eksisterer inden den fjernes

### ISSUE THREAD

**Issue by hanshvidberg** [detfaellesdesignsystem/dkfds-components#210]
Som aftager af DKFDS kan det ske at åbne/lukke-funktionaliteten af modals bliver styret udefra, og der kan godt opstå en konflikt med 'keyup' event-handleren som lukker modalen på escape, uden man kan gøre noget ved det. Hvis man efter at modalen er blevet lukket med escape, har brug for at kalde Modal.hide() programmatisk, så checker funktionen ikke om backdrop allerede er fjernet, og dermed er resultatet en hård js fejl i browseren.

Kunne løses med et enkelt `if ($backdrop)` inden det bliver forsøgt fjernet fra DOM'en.

https://github.com/detfaellesdesignsystem/dkfds-components/blob/edf45da31b93deddf6ec32d501729847456ade02/src/js/components/modal.js#L40-L41

**Comment by detfaellesdesignsystem** [comment]
Hej @hanshvidberg 

Tak for din henvendelse!

Vi har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
