### ISSUE TITLE
Migrering fra dkfds-plugins

### ISSUE THREAD

**Issue by jokk-itu** [detfaellesdesignsystem/dkfds-components#211]
Jeg har søgt efter noget information omkring migrering væk fra jeres 'dkfds-plugins' da det er udgået.
Jeg har ikke kunne findet noget, og derfor vil jeg høre om i ligger inde med viden der kan hjælpe.

**Hvor har jeg søgt?**
I issues i dette repository og dkfds-plugins, samt i [designsystem.dk](https://designsystem.dk/kode/plugins/).

**Hvor opstår behovet?**
Da dkfds-plugins er udgået ses der ind i mulighederne i at flytte væk fra det og udelukkende bruge 'dfkds-components'.

**Hvad har været overvejet?**
At hive .scss filerne fra dkfds-plugins over i eget projekt.
Dette er ikke muligt da der ikke er en LICENSE fil i dkfds-plugins.

**Comment by jokk-itu** [comment]
Hej Helle.
Mange tak for hurtigt svar!

Ja vi bruger lige præcis eksterne plugins.
De .scss filer vi bruger, er til pikaday, micromodal og datatables.

Det er netop årsagen til at dkfds-plugins er udgået og rigtig nok ikke kompatibel med en nyere version af dkfds-components,
at vi gerne vil væk fra dkfds-plugins.

For at komme væk fra det, var min første tanke at kopiere .scss filerne over i eget projekt og herefter tilpasse dem så det virker til dkfds-components.
Bortset fra at dkfds-plugins ikke har en licens.

Netop derfor vil jeg gerne høre jer om i har et råd til at komme væk fra dkfds-plugins.

**Comment by detfaellesdesignsystem** [comment]
Hej @jokk-itu 

Den umiddelbare anbefaling, når det gælder filerne i dkfds-plugins, er desværre helt at stoppe med at bruge dem og enten finde andre løsninger eller være forberedt på, at der ligger et arbejde i at style og kontrollere de plugins, man skal bruge.

Til erstatning for pikaday og micromodal vil jeg foreslå, at I tager et kig på designsystemets [datovælger](https://designsystem.dk/komponenter/datovaelger/) og [modaler](https://designsystem.dk/komponenter/modal/).

Vi har desværre ikke nogen datatables, så her er I selv nødt til at tilpasse designet på det plugin, I benytter. Tag evt. et kig på den styling vi har anvendt til vores [paginering](https://designsystem.dk/komponenter/paginering/), [tabeller](https://designsystem.dk/komponenter/tables/), [inputfelter](https://designsystem.dk/komponenter/inputfelter/) og [dropdowns](https://designsystem.dk/komponenter/dropdown/) for inspiration.

Hvis I har nogen ønsker, forbedringsforslag eller udfordringer med designsystemets komponenter, så skriv endelig igen.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by jokk-itu** [comment]
Tusind tak Helle.
Det vil vi se videre på.
