### ISSUE TITLE
Klikbar tlf. nr. på mobil

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#212]
Hej FDS,
Vi vil gerne bruge `<a href="tel:+4570123200">+45 70 12 32 00</a>` på vores kontaktsider, så det bliver brugervenligt på mobil - så man kan ringe ved at trykke på nummeret. 

Har I forslag til styling af nummeret, så det ikke ligner et link på desktop. 

![image](https://github.com/detfaellesdesignsystem/dkfds-components/assets/48348000/10b352cb-cfbf-49b2-a54f-bef026ecff06)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Tak for jeres henvendelse!

Vores UX'ere vil tage et kig på jeres problemstilling og vende tilbage i løbet af de kommende dage.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp

Vi vil som udgangspunkt foreslå, at man evt. kan tilføje et ikon til telefonnummeret - a la funktionslink komponentet - for at synliggøre funktionen mere, hvis man er i tvivl om, hvorvidt brugeren forstår, at linket kan klikkes for at ringe til et nummer.

Ellers vil vi blot anbefale at fastholde telefonnummeret som linkform.

Med venlig hilsen
Det Fælles Designsystem
