### ISSUE TITLE
Knapper med ikon står ikke på linje med knapper uden ikon

### ISSUE THREAD

**Issue by morthanh** [detfaellesdesignsystem/dkfds-components#215]
**Bekskriv fejlen (Describe the bug)**
Når to knapper er placeret ved siden af hinanden og en af knapperne har et ikon, så er knapperne ikke placeret i samme højde.
Det ser ud til at højden på ikonet er synderen. Højden styres af .icon-svg og er sat til 2.4rem. Sættes den til 1.2rem passer placeringen af knappen igen, men selvfølgelig så bliver ikonet samtidigt mindre. 

**Genskab fejlen (To Reproduce)**
Følgende giver 2 knapper hvor den første knap er en primær 'Gem' knap uden ikon. 
Den anden knap er en sekundær 'Tilføj' knap med et '+' ikon. 
```
<div class="col-12">
        <button type="submit" class="button button-primary">Gem</button>

        <button class="button button-secondary">
            <svg class="icon-svg" aria-hidden="true">
                <use xlink:href="#add"></use>
            </svg>
            Tilføj maskine
        </button>
</div>
```

**Screenshots**
![image](https://github.com/detfaellesdesignsystem/dkfds-components/assets/2750357/2e22166c-4e10-45a2-a59d-f8bb576b4c4f)

**Sådan burde det fungere (Expected behavior)**
Forventet resultet må forventes at være at knapperne er placeret i samme højde uanset om der er et ikon i en af knapperne eller ej

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 114.0.1823.67 64-bit
 - DKFDS: 9.0.1

**Comment by detfaellesdesignsystem** [comment]
Hej morthanh

Tak for din besked. 
Dette vil teamet se nærmere på. 

Vi giver en opdatering på dette issue når der er noget nyt. 

Med venlig hilsen 
Marcus 
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @morthanh 

Fejlen er løst i næste release.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @morthanh 

Version 9.0.2 er netop releaset med rettelsen.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
