### ISSUE TITLE
Datalist til inputs

### ISSUE THREAD

**Issue by EmilBahnsen** [detfaellesdesignsystem/dkfds-components#219]
HTML-komponenten \<datalist\> tilføjer standard valgmuligheder til inputfelter, men er ikke repræsenteret specielt konsistent med resten af FDS's design:
<img width="347" alt="Screenshot 2023-09-01 at 10 08 50" src="https://github.com/detfaellesdesignsystem/dkfds-components/assets/103197299/45de280e-14a0-43f5-84a7-3b927920c6b8">

Tilsvarende plain HTML:
<img width="279" alt="Screenshot 2023-09-01 at 10 09 08" src="https://github.com/detfaellesdesignsystem/dkfds-components/assets/103197299/ba2cd8d5-fd20-4aff-89b5-2bbb3128bee1">

Umiddelbart skal der tilføjes:
* En knap til at vise standard valgmuligheder
* En liste i stil med resten af FDS (dynamisk filtreret som man skriver)
* Et design der indikerer muligheden for fritekst, så den ikke forveksles med en dropdown

Alternativt kan knappen til visning af muligheder unlades, så den i højere grad skiller sig ud fra en alm. dropdown.

**Comment by detfaellesdesignsystem** [comment]
Hej Emil

Tak for din henvendelse.

Det Fælles Designsystem indeholder på nuværende tidspunkt ingen retningslinjer eller design for brugen af datalists, da dette afhænger meget af brugerens browser. Vi har derfor ikke undersøgt datalists grundigt, men vi er bekymrede for tilgængeligheden særligt på mobil. Derfor kan vi umiddelbart ikke anbefale at anvende datalists. Overvej, om I i stedet kan anvende fx et almindeligt inputfelt, radioknapper eller dropdown.

Venlig hilsen
Mette
Det Fælles Designsystem
