### ISSUE TITLE
Udskift querySelector med getElementById i dropdown.js

### ISSUE THREAD

**Issue by chce** [detfaellesdesignsystem/dkfds-components#220]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Bekskriv fejlen (Describe the bug)**
https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/src/js/components/dropdown.js
Linje 146:
      let targetEl = currentOverflowMenuEL.querySelector('#'+triggerEl.getAttribute(TARGET).replace('#', ''));

Denne funktion vil fejle på et gyldigt ID, hvis det gyldige ID indeholder kolon jf. HTML Living Standard https://html.spec.whatwg.org/multipage/dom.html#global-attributes:the-id-attribute-2
querySelector anvender kolon til at differentiere pseudoelementer, og funktionen vil fejle med beskeden: DOMException: "Failed to execute 'querySelector' on 'Document': '#of:r4:' is not a valid selector.". 

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
Se fejlbeskrivelse

**Sådan burde det fungere (Expected behavior)**
Man kan i stedet bruge document.getElementById, som korrekt vil finde elementet.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Alle
 - Browser [e.g. chrome, safari]: Alle
 - Version [e.g. 22]: Nyeste

**Supplerende oplysninger (Additional context)**
https://bugzilla.mozilla.org/show_bug.cgi?id=883044

**Comment by detfaellesdesignsystem** [comment]
Hej @chce 

Tak for din henvendelse!

Vi har oprettet en sag på det.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @chce 

Fejlen er løst i version 9.1.0.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem
