### ISSUE TITLE
Side med mange Ja/nej radio-knapper

### ISSUE THREAD

**Issue by dk-teknologisk-mrth** [detfaellesdesignsystem/dkfds-components#221]
**Beskriv dit behov for hjælp. (Describe your need for help.)**
Jeg vil gerne høre jeres mening om sider med mange simple ja/nej input.

I anbefaler at radio-knapper er vertikale pga læseretning, men i mit tilfælde har jeg en løsning hvor der skal være 9 ja/nej spørgmål på samme side. Se billedet herunder. Hvis radio-knapperne skal placeres vertikalt så bliver det en unødvendig lang side. Og for meget scrolling fraråder i vist også. 

Man kunne spare plads ved at bruge checkbox, men jeg har et krav om at de ikke må være præ-udfyldt, og en checkbox er, per design, altid udfyldt. Derfor benytter jeg radio-knapper hvor hverken ja eller nej er valgt når siden vises. 

Har i et bedre forslag til hvordan en side med mange ja/nej spørgmål kunne struktureres?

![image](https://github.com/detfaellesdesignsystem/dkfds-components/assets/129733594/6e65caf7-ec28-4de9-b8b4-38b944aa42fa)
(kun 4 spørgsmål er vist her men der er 5 mere...)

Ekstra detalje; på en side der ligner den fra billedet blot med andre rettigheder er der vist 3 radio-knapper per spørgsmål (ja/nej/ved ikke) som blot ville gøre siden endnu længere hvis den skulle vises med radio-knapper placeret vertikalt.

**Comment by detfaellesdesignsystem** [comment]
Hej @dk-teknologisk-mrth 

Tak for din henvendelse!

Vi tager et kig på din problemstilling i FDS-teamet og vender tilbage i løbet af de kommende dage.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @dk-teknologisk-mrth 

Vi forstår godt din problemstilling med radioknapperne. Dog anbefaler vi, at man lister valgmulighederne vertikalt og ikke horisontalt – det giver brugeren en nemmere og lettere måde at overskue en side på. Vi er med på, at sider evt. kan blive meget lange i nogle tilfælde, men det er bedre end at have korte sider med meget tætpakket information. 

Vores anbefaling er derfor at liste radioknap-valgmulighederne vertikalt.

Med venlig hilsen
Det Fælles Designsystem
