### ISSUE TITLE
Velkommen pop-op

### ISSUE THREAD

**Issue by Emilieisabelladahl** [detfaellesdesignsystem/dkfds-components#224]
Vi vil gerne udvide vores hjemmeside, så når en bruger logger på siden, modtager de en god introduktion. 
Dette kunne evt. være en pop-op som siger "Velkommen Anne", samt en beskrivelse af hvad man kan på hjemmesiden efter login. 
Derefter kan man have mulighed for at framelde sig, så denne pop-op ikke vises igen. 

Dette er blot et forslag, men vil gerne have jeres forslag til et brugervenligt og universelt "velkommen" design, som guider og hjælper brugeren mest muligt. Hvad er jeres forslag?

Dette kan evt. tilføjes som "Pattern" i det fælles design system.

**Comment by detfaellesdesignsystem** [comment]
Hej @Emilieisabelladahl 

Tak for din henvendelse!

Vi tager et kig på dit forslag og vender tilbage i løbet af de kommende dage.

Med venlig hilsen
Helle Juhl
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @Emilieisabelladahl 

Vi har drøftet dit forslag og mener umiddelbart, at sådan et pattern er lidt for specifikt til større løsninger, som det lyder som om jeres er, til at gøre sig gældende for generelle selvbetjeningsløsninger. Derfor vil vi ikke gå videre med ideen om et pattern i Det Fælles Designsystem.

Det udelukker dog selvfølgelig ikke, at det kan være en god idé i netop jeres tilfælde. Men vi kan desværre ikke give andre råd, end at I endelig må brugerteste den løsning, I kommer frem til, så I er sikre på, at introflowet bliver læst og giver værdi for brugerne. Og så I kan evt. lade jer inspirere af de mange introflows, der findes i særligt mobile apps. Vi kan også foreslå jer at tage et kig på Digital Posts introflow.

Venlig hilsen
Mette
Det Fælles Designsystem
