### ISSUE TITLE
Z-index for wooSelect-dropdown is lower than the topmenu

### ISSUE THREAD

**Issue by atoftegaard** [detfaellesdesignsystem/dkfds-components#23]
As the title says, the wooSelect-dropdown seems misplaced. See attached screenshot.

![image](https://user-images.githubusercontent.com/6214674/54824363-0051f300-4cab-11e9-946d-f204b372db4c.png)

**Comment by detfaellesdesignsystem** [comment]
Hi @atoftegaard,

Thank you for contacting us!

We've fixed the bug. The fix will be in next release.

Best regards
Kristina Jensen
Det Fælles Designsystem
