### ISSUE TITLE
Forsimpling af forældet html: `<footer>` i stedet for `<footer><div class=footer>`

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#232]
Som et levn fra gamle dage, beskrives footer komponenten med følgende HTML selv i nyeste version af Designsystem:

```
<footer>
    <div class="footer">
        <div class="container">
```

(eksempel ovenfor fra https://designsystem.dk/kode/komponenter/footer/)

Denne dybe nesting er irriterende, og fylder unødigt og burde ikke længere være nødvendig. Tilbage i dagene, dengang da Internet explorer 8 og lavere var dominerende, så var det nødvendigt med et fallback da disse browsere ikke forstod `<footer>` elementet.

Men så kom IE9 i 2011, og siden da har der ikke været problemer. Og i nyeste versioner af Designsystem er IE ikke understøttet.

Hvis en opdatering af HTML kommer på tale igen (er sket før mange gange i Designsystems levetid), så vil det være passende at kalde det en breaking change og lave en ny major release.

Bonusforslag: Man kunne lave et mindre `designsystem-legacy-9.1.scss` script som kunne benyttes af folk som ville opgradere til v10 , men som kunne rendere gammel html 

Jeg er interesseret i at høre projektgruppens planer for forsimplinger i HTML og eventuelle tanker omkring hvordan man hjælper brugere med at migrere.

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn

Tak for din henvendelse.

Du har ret i, at html-koden til footer-komponenten kan optimeres. Vi har lagt en opgave i backloggen til dette.

I teamet arbejder vi løbende på at forbedre designsystemet, bl.a. i form af kodens kvalitet, og vi har allerede fået flere forslag, som vi arbejder videre med i øjeblikket. Ved hver release gør vi vores bedste for at beskrive hver enkelt ændring så godt som muligt i vores release notes. Her markerer vi også, hvad der er breaking changes. 

Venlig hilsen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
det giver vist ikke mening at holde dette issue åbent indtil opgaven i backloggen implementeres? Jeg lukker dennne, men I er naturligvis velkomne til at linke til relevant offentlig tilgængelig info her.
