### ISSUE TITLE
Søgefelt 'x' kan ikke benyttes med tastatur

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#237]
søgefeltet fra https://designsystem.dk/komponenter/search/ har desværre den uhensigtsmæssighed at krydset til at cleare indhold i søgefeltet ikke kan tilgås med tastatur. 

jeg kan se fejlen var der i v9.x og at den stadig findes i v10.x

Er det noget I kan overveje at fixe?

<img width="316" alt="Søgefelt___Det_Fælles_Designsystem" src="https://github.com/detfaellesdesignsystem/dkfds-components/assets/6267/4186527a-0350-4fa9-9420-fc3f14db3477">

**Testet på:**
 - OS: macOS 14.5 (sonoma)
 - Browser  chrome 126.0

**Også testet på:**
 - OS: Windows 11, build 22631
 - Browser  edge 126.0

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn 

Tak for at gøre os opmærksomme på problemet. Det lader til at være et kryds, som nogle browsere sætter ind. Det er ikke en del af designsystemet som sådan.

Vi har lagt en opgave i vores backlog, så vi kan undersøge, om/hvad vi kan gøre ved det.

Venlig hilsen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
Har fundet lidt mere information. I har helt ret i at det er min browser der indsætter. 

Man kan se elementet fx i Chrome Devtools hvis man vælger indstillingen **"Elements > Show user agent shadow DOM"**

Elementet ser sådan her ud i shadow DOM:

```html
<input class="form-input input-char-27" id="search-input" name="q" type="search" required="" aria-label="Søg">
#shadow-root
<div id="text-field-container" pseudo="-webkit-textfield-decoration-container" style="unicode-bidi: normal;">
<div id="editing-view-port">
  <div>asdf</div>
</div>
<div pseudo="-webkit-search-cancel-button" id="search-clear" style="">
</div>
</div>
```

Dvs elementet er `::-webkit-search-cancel-button". 

Jeg fandt mere information her https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button

Workaround man kan fjerne elementet med en css regel sådan her:

```css
input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none;
}
```

Men det løser naturligvis stadig ikke problemet med at kunne tastatur-navigere til elementet. Håber denne info kan hjælpe jer

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn 

Tak for de yderligere informationer. Vi fjerner browserkrydset i en af de kommende releases.

Venlig hilsen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
fixet i release 10.0.2 https://github.com/detfaellesdesignsystem/dkfds-components/releases/tag/10.0.2

Desværre er der ikke et link her til den commit der fixer fejlen. 

Link til commit: 5ca9245827f42cb5980ce2e79a396266af5bd7cb
