### ISSUE TITLE
Klassen "table-lines" savnes

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#240]
Hej Dkfds,
I har fjernet klassen "table-lines" i version 9.00 - men kommer der en anden klasse, der erstatter den? vi savner nemlig klassen i nogle af vores tabeller, hvor det er hensigtsmæssigt ikke at vise border-right i tabellen.
![image](https://github.com/user-attachments/assets/ac55fe38-d2a3-4814-bb74-1b41c45778e2)

mvh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Tak for jeres henvendelse. Vi er kede af at høre, at I savner klassen.

Kan I dele et par (evt. anonymiserede) screenshots af, hvilke tabeldesigns I har brugt klassen til? Så vil vi lige undersøge det nærmere.

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Mette,
Her er et eksempel: 
![image](https://github.com/user-attachments/assets/945ba8c0-46de-49cc-9f71-15bc7c69c000)

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana
 
Tak for eksemplet.
 
Kan jeres behov løses med den styling, I får med klassen table--borderless?
 
Det vil give en tabel, der ser sådan ud: https://designsystem.dk/eksempel/table--borderless/
 
Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Mette,
tak - nej, table-borderless kan ikke bruges, da vi også har sortering på table-headers. Er det besværligt at tilføje klassen igen? giver det jer problemer? hvis ja, så laver vi bare klassen i vores kode :-)

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Klassen table--borderless burde kunne fungere sammen med sortering på tabelkolonnerne. Hvilke problemer oplever I, når I forsøger det?

Venlig hilsen
Mette
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Mette,
Der er tale om to forskellige tabeller. I vores løsning har vi testet den tabel, som jeg har sendt billede af - og sådan vil vores forretning have tabellen skal se ud. 

![image](https://github.com/user-attachments/assets/31c51e2b-cbf5-4638-b218-19ab544e9255)

mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Tak for uddybningen. 

Hvis det er nødvendigt i jeres design, at tabellen er visuelt afgrænset med borders, vil vi umiddelbart anbefale jer at anvende standardtabellen, da den minder mest om jeres tabel: https://designsystem.dk/eksempel/table/

Hvis det er vigtigt for jeres løsning, at der ikke er lodrette streger, så kan I selvfølgelig tilføje den gamle klasse selv. Vi valgte at fjerne klassen, da den ikke har været teknisk vedligeholdt og dokumenteret, samt at der er flere andre tabelvarianter til rådighed.

Venlig hilsen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej,
Tak for svar :-) 
Vi laver bare vores egen klasse, så undgår vi mange diskussioner om, hvorfor det (at afgrænse tabellen med borders) ikke kan lade sig gøre længere.

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Vi lukker tråden her. Du er velkommen til at genåbne, hvis det bliver relevant.

Venlig hilsen
Det Fælles Designsystem
