### ISSUE TITLE
Ikonet file-upload mangler fra all-svg-icons.svg

### ISSUE THREAD

**Issue by chce** [detfaellesdesignsystem/dkfds-components#243]
[Indmeld kun 1 fejl pr. issue og tjek gerne om fejlen allerede er indmeldt. (Only one bug per issue and make sure to check if the issue already exists)]

**Beskriv fejlen (Describe the bug)**
Ikonet file-upload (src/img/svg-icons/file-upload.svg) findes ikke i all-svg-icons-filen (src/img/all-svg-icons.svg)

**Genskab fejlen (To Reproduce)**
Se beskrivelse

**Indsæt link (Add a URL)**
https://github.com/detfaellesdesignsystem/dkfds-components/blob/6a9c02fc39ad1117383892ee7b74c6af670df20e/src/img/all-svg-icons.svg

https://github.com/detfaellesdesignsystem/dkfds-components/blob/6a9c02fc39ad1117383892ee7b74c6af670df20e/src/img/svg-icons/file-upload.svg

**Screenshots**
Ikke relevant

**Sådan burde det fungere (Expected behavior)**
file-upload burde være tilgængelig i all-svg-icons.svg

**Desktop - udfyld venligst følgende (please complete the following information):**
Ikke relevant

**Smartphone - udfyld venligst følgende (please complete the following information):**
Ikke relevant

**Supplerende oplysninger (Additional context)**
Ikke relevant

**Comment by detfaellesdesignsystem** [comment]
Hej @chce 

Fejl er fikset i 10.0.2. Vi lukker derfor tråden her, men du er velkommen til at genåbne, hvis du oplever problemer med rettelsen.

Venlig hilsen
Det Fælles Designsystem
