### ISSUE TITLE
scss variabler bliver ikke benyttet i f.eks header

### ISSUE THREAD

**Issue by tmountford** [detfaellesdesignsystem/dkfds-components#245]
**Bekskriv fejlen**
Jeg er i gang med at opgradere fra designsystem 9 til 10 og er ved at følge migreringsguiden.
Jeg vil gerne overskrive højde og bredde på vores header logo og har fundet disse variable: 

```
$header-portal-logo:                        'logo-header-placeholder.png' !default;
$header-portal-logo-width:                  200px !default;
$header-portal-logo-height:                 60px !default;
```

Jeg kan godt erstatte $header-portal-logo men de to andre gør ikke nogen forskel. Jeg har da kigget ned i koden for header-komponenten og set, at variable ikke bliver brugt.

```
.logo {
            background-image: url(vars.$image-path + vars.$header-portal-logo);
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center left;
            display: inline-block;
            height: 24px; <--
            width: 100%; <--

            @include mixins.media-breakpoint-up(vars.$nav-responsive-breakpoint) {
                max-width: 30%;
            }

            span {
                display: none;
            }
        }
```

**Sådan burde det fungere (Expected behavior)**
Jeg vil forvente at jeg kan overstyre $header-portal-logo-width og $header-portal-logo-height variable og at disse vil slå igennem på mit header-logo. 

**Supplerende oplysninger (Additional context)**
Jeg har ikke tjekket andre variable, men måske der findes flere eksempler.

**Comment by detfaellesdesignsystem** [comment]
Hej @tmountford 

Tak for din henvendelse!

Vi har oprettet en sag på det.

Med venlig hilsen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
fixet i release 10.0.2 https://github.com/detfaellesdesignsystem/dkfds-components/releases/tag/10.0.2

Desværre er der ikke et link her til den commit der fixer fejlen.

Link til commit: 91e850ba884c42bf5b5ebd10850baa31ed3df404

**Comment by detfaellesdesignsystem** [comment]
Hej @tmountford

Som @jesperronn skriver, er denne fejl fixet i 10.0.2. Vi lukker derfor tråden her, men du er velkommen til at genåbne, hvis du oplever problemer med rettelsen.

Venlig hilsen
Det Fælles Designsystem
