### ISSUE TITLE
Mit Sygefravær Login

### ISSUE THREAD

**Issue by 314ga** [detfaellesdesignsystem/dkfds-components#248]
**Bekskriv fejlen (Describe the bug)**
After Logging into "Mit Sygefravær" with MitID page is redirected to the same "Welcome to Mit Sygefravær" with the same Log in buttons. Pressing logging button again only refreshes the page.

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Go to https://mitsygefravaer.dk/
2. Click on Log in to Mit Sygefravær
3. Authenticate with MitID
4. Redirect to the "Welcome to Mit Sygefravær"

**Indsæt link (Add a URL)**
[Tilføj om muligt et link til fejlen. (If possible, add a URL to help identify your problem.)](https://mitsygefravaer.dk/)

**Screenshots**
![image](https://github.com/user-attachments/assets/c042cb5d-99dd-4155-b1b0-463ba80af0a9)

**Sådan burde det fungere (Expected behavior)**
Access page after successful login

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows 10
 - Tried Browsers: Chrome, Edge, Mozila
 - Version: newest versions

**Supplerende oplysninger (Additional context)**
Tilføj andre detaljer vedrørende fejlen.  (Add any other context about the problem here.)

**Comment by detfaellesdesignsystem** [comment]
Hello @314ga,
 
The team working on Det Fælles Designsystem is only in charge of the development of the design system itself. We are not responsible for the individual sites/online forms built with the design system.
 
If you are having technical issues with a specific online service, we kindly ask you to contact the authority in charge of that service.
 
Best,
Det Fælles Designsystem
