### ISSUE TITLE
Faneblade visning på mobil

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#25]
Hej DFS,
Ville det ikke være pænere, hvis [fanebladene](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/cards/) stod ved siden af hinanden på mobilen - istedet for at stå under hinanden (selvfølgelig med forebehold at man højst har 2-3 faneblade, som kan vises pænt på det mindste mobilskærm).

Vi har løst problemet på en af vores "gamle" løsninger således:
![image](https://user-images.githubusercontent.com/48348000/55548796-9a1a9680-56d4-11e9-8f16-43287acbf8f4.png)
--------------------
![image](https://user-images.githubusercontent.com/48348000/55549483-41e49400-56d6-11e9-805e-d64c2c6012cf.png)

Vi har nedenstående DFS-løsning på en ny selvbetjening:
![image](https://user-images.githubusercontent.com/48348000/55548907-dd750500-56d4-11e9-854b-6ba629409295.png)

Er det noget I kan kigge på - eller skal vi selv lave et fix i koden for at få fanebladene til at se pænt ud på mobil. 

M.v.h.

Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Tak for input. Det bliver tidligst fra næste sprint at vi får lejlighed til at kigge på det, men jeg opretter det som en user story at vi skal genbesøge fanebladskomponenten. Vi kan godt se at der er noget ved komponenten, der ikke er optimalt, men vi er heller ikke vilde med den horisontale model du foreslår.

Kig evt til hvordan govUK laver fanebladene om til en indholdsfortegnelse med anchor-links og viser indholdet nedenfor. Så man scroller sig igennem det uanset. Det kunne være en måde at gøre det på.
https://design-system.service.gov.uk/components/tabs/

Uden at skulle blande mig utidigt, så er fanebladskomponenten generelt en vi anbefaler man forsøger at undgå at bruge, så måske i med fordel kan undersøge om faneblade vitterligt er den bedste måde at dele indholdet op på. 

Vi kigger på fanebladskomponenten og vender tilbage hurtigst muligt :)

Mvh
Sune
FDS-team

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Så er det nyt.

Vi kommer med en helt ny faneblads komponent i næste release - som vil være 5.0.0.

Den tidligere komponent havde en del mangler, så vi har nu taget højde for de forskellige skærmstørrelser og vi leverer javascript logikken samtidigt - den del har tidligere manglet.

Jeg lukker sagen her for nu.

Med venlig hilsen
Kristina Jensen
