### ISSUE TITLE
Ved opdateringer bør ALLE ændringer i html formatet betragtes som BREAKING changes

### ISSUE THREAD

**Issue by jesperronn** [detfaellesdesignsystem/dkfds-components#253]
I går udkom en ny release af DKFDS nu i version v10.1.0. 

Desværre breaker nogle ting for os da vi benytter pagineringskomponenten som har fået opdateret HTML. 

Vi havde ret stor fornøjelse med opgradering fra v9 => v10.0 for nylig, men det kunne være rart hvis I ville følge "semantic versioning" i jeres releases. Dvs hvis noget kan riisikere at breake så lav en major release. (jeg kan ikke forestille mig man løber tør for tal)

Sådan en release med ændringer i HTML formatet vil gøre at nogle brugere (som fx en af vores løsninger) skal ha opdateret HTML formatet ved disse ændringer.

Kan man forestille sig en side hvor I beskriver jeres release politik (helst semantic versioning, tak). 

Derudover synes jeg at det virker godt hvis der er en migreringsguide ved hver release især hvis det giver anledning til at man muligvis skal ændre noget. 

Det kunne være HTML men også Sass variabel navne, filnavne (hvis man kun sourcer nogle af filerne) eller lign

**Comment by detfaellesdesignsystem** [comment]
Hej @jesperronn 
 
Ved minor releases kan der være changes, hvor det er nødvendigt at opdatere ens HTML for at få ændringerne med, men ens eksisterende kode bør ikke holde op med at fungere. Hvis du efter en patch eller minor release oplever, at din eksisterende kode ikke længere virker, må du meget gerne kontakte os med flere detaljer.
 
Du kan læse mere om vores forskellige typer af releases under [Versionering og release-proces](
https://designsystem.dk/faellesskab/releases/#versionering-og-release-proces).
Hvis noget kræver, at man som udvikler skal ind og foretage ændringer i sin kode, markerer vi det med 'change' i release notes.
 
Med venlig hilsen
Det Fælles Designsystem

**Comment by jesperronn** [comment]
Tak for svar, jeg er ikke enig i proces-beskrivelsen, men det er jeres politik i komponenten og den er nu tydeligt forklaret.

Jeg lukker issuet
