### ISSUE TITLE
Print - style og utilities 

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#26]
**Pkt. 1) Print visning**
Er det meningen af print skal vises som en mobilskærm ? Således at login oplysninger er skjult i menu knappen, eller at tabellerne bliver printet som mobil visning ?  (se nedenstående billede)
Vi ønsker helst at style print vises som desktop visning, men hvad synes I hos dkfds ?

![image](https://user-images.githubusercontent.com/25169794/55553483-9ab92a00-56e0-11e9-8a9a-32ab3c37182d.png)
![image](https://user-images.githubusercontent.com/25169794/55553489-9f7dde00-56e0-11e9-932e-bade675b0710.png)

**Pkt. 2) Utilities for toggling `display` in print**  
Vi savner at kunne toogle elementer til print. Har I mulighed for at tilføje nedenstående print utilities til dkfds ? 

// Utilities for toggling `display` in print

```
@media print {
  .d-print-none         { display: none !important; }
  .d-print-inline       { display: inline !important; }
  .d-print-inline-block { display: inline-block !important; }
  .d-print-block        { display: block !important; }
  .d-print-table        { display: table !important; }
  .d-print-table-row    { display: table-row !important; }
  .d-print-table-cell   { display: table-cell !important; }
  .d-print-flex         { display: flex !important; }
  .d-print-inline-flex  { display: inline-flex !important; }
}
```

**Eksempel på en ønskede anvendelse**
Vores forretning ønsker som standard at, vise login-oplysninger + SE-nr/CVR-nr. på print. 

![image](https://user-images.githubusercontent.com/25169794/55552662-414ffb80-56de-11e9-80e1-a17a8cda1005.png)

![image](https://user-images.githubusercontent.com/25169794/55552897-069a9300-56df-11e9-86a4-fc2b24d8e0cb.png)

**Henvisning**
https://getbootstrap.com/docs/4.3/utilities/display/#display-in-print

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin ,

Tak for din henvendelse!

Vi har allerede en sag liggende i vores backlog om at vi skal genbesøge print css i dkfds.

Jeg kan ikke love at vi kan nå det inden næste release, men vil sørge for at klasserne du nævner i pkt. 2 kommer med.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin ,

Print klasserne er nu release med seneste version (4.0.1)

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Mange tak for hjælpen. 

Er npm 4.0.1 også klar ?  
Når jeg installere 4.0.1, får jeg fejlen: `npm ERR! notarget No matching version found for dkfds@^4.0.1 `

Med venlig hilsen 
Laura Beck 
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin ,

Ja, [4.0.1](https://www.npmjs.com/package/dkfds) kom ud i går eftermiddag. 

Jeg har lige forsøgt at opdatere dkfds versionen i et lokalt projekt jeg har liggende til test - det fungerede fint. Prøv evt. igen?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Hej Kristina, 

Jeg prøvede i går eftermiddags og i morges at opdatere til 4.0.1, og jeg fik den samme fejl. 

Hvis jeg køre en `npm install --save dkfds@latest`  får jeg version 4.0.0

Med venlig hilsen
Laura Beck
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Jeg kan simpelthen ikke reproducere den fejl du melder. Jeg er på nippet til at sige det er en projektspecifik fejl.

- Hvad står der af version i din package.json?
- Kan din package-lock,json være korrupt?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Hej Kristina, 
I dag lykkedes det at installere 4.0.1  
I går prøvede jeg prøvede at, slette package-lock og node-modules mappen, men fik den samme fejl. Det gjorde min kollega også med hans projekt. Mystisk. 

Men alt er vel nu, og tak for hjælpen. 

Med venlig hilsen
Laura Beck
ATP

**Comment by detfaellesdesignsystem** [comment]
@laclogin 
Hej Laura
Jeg lukker dette issue. Sig endelig til hvis det skal genåbnes.
Mvh
Sune
FDS
