### ISSUE TITLE
Disable close af micromodal

### ISSUE THREAD

**Issue by 4nd3r5** [detfaellesdesignsystem/dkfds-components#27]
**Beskriv fejlen**
Micromodal kan ikke blokeres for lukning, hverken for klik i luk, klik i baggrund eller tryk på escape. Dette er også et åbent issue hos micromodal: 
https://github.com/ghosh/micromodal/issues/105

Man kan omgå lukning af modal gennem klik i baggrund og klik på lukknap med at ændre i markuppen, men det nytter ikke noget da man stadig kan trykke escape. (https://github.com/ghosh/micromodal/issues/132)

Det er uhensigtsmæssigt at indføre en modal der ikke har muligheden for at blokere for lukning, der er mange use cases hvor det er et behov.

Man kan måske godt argumentere for at det er to forskellige brugsscenarier, men der er i ihvertfald et behov for en lignende komponent der kan agere som en dialog.

**Comment by detfaellesdesignsystem** [comment]
Hej @4nd3r5 ,

Tak for din henvendelse!

Vi har oprettet en sag på det, og vil kigge nærmere på om vi kan/skal tilpasse det nuværende modalvindue, eller om en evt. tredjeparts løsning kan anbefales.

Hvis du finder et tredjepartsbibliotek, som opfylder kravene, vil vi meget gerne høre om det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Opdatering:
FDS understøtter ikke micromodals siden før v7.0.0. FDS har i stedet lavet en modal komponent fra bunden som fra v8.0.0 vil understøtte blokering af lukning, således at brugeren er tvunget til at foretage et valg. Version 8.0.0 bliver releaset inden for få uger.
