### ISSUE TITLE
"Spørgsmåltegn" ikon -tooltip

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#29]
Hej,
I  bruger ikonet "Spørgsmåltegn" på siden tooltip: https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tooltip/
![image](https://user-images.githubusercontent.com/48348000/56204167-169f6480-6047-11e9-9fee-9d74d67ff5bb.png)

Anbefaler I, at spørgsmåltegnet er bedst at bruge med tooltip - eller kan "i" ikonet også bruges?

![image](https://user-images.githubusercontent.com/48348000/56203993-b27ca080-6046-11e9-8e41-852f6511bd54.png)
https://detfaellesdesignsystem.github.io/dkfds-docs/design/ikoner/

 Mvh.
Farzana fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Du kan sagtens bruge info ikonet, men det kommer selvfølgelig an på sammenhængen.

Vi vil overveje at oplyse, hvilke ikoner vi anbefaler man holder sig til i forhold til tooltip.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Tak for det :-)
Vi har tidligere i usabilitytests fået følgende resultater;
-  Ikonet "i" bliver på en måde overset - og brugerne var i tvivl om ikonet havde en funktion. 
- Vi oplevede, at brugerne havde det nemmere at "forstå" "Spørgsmåltegnet" og dets formål.  

God påske

Mvh.
Farzana
