### ISSUE TITLE
Styling af select options

### ISSUE THREAD

**Issue by christianlandbo** [detfaellesdesignsystem/dkfds-components#3]
Har I planer om at levere styles til select options? Pt. ser det ikke godt ud ift. sådan som form-select er stylet.

**Comment by detfaellesdesignsystem** [comment]
Hej Christian,

Tak for din henvendelse!

Vi har på nuværende tidspunkt ingen planer om at levere styles til select options. Man ville ikke komme langt, da det er meget begrænset, hvad man kan style, når det kommer til select options.

For bedste oplevelse på tværs af alle browsers og enheder (Smartphone, tablet etc.) har vi valgt at bruge native elementer i designsystemet.

En løsning kunne dog være at bruge et tredjeparts bibliotek i din løsning, som eventuelt kunne tilføjes som en udvidelse i designsystemet. Se [https://detfaellesdesignsystem.github.io/dkfds-docs/udvidelser/ ](https://detfaellesdesignsystem.github.io/dkfds-docs/udvidelser/) .

Du er velkommen til at vende tilbage, hvis du finder et passende bibliotek.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by christianlandbo** [comment]
Hej Kristina

Vi kigger på hvad vi kan gøre for at få dem lidt pænere og vælger nok at vise native på mindre skærme.
Det er hovedsageligt IE, hvor det ser ret skidt ud pt.

Tak for hurtigt svar. 

/Chr

**Comment by detfaellesdesignsystem** [comment]
Hej Christian,

Det har du da helt ret i. Der skal selvfølgelig ikke være to ikoner. Vi opretter en sag på det med det samme.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
