### ISSUE TITLE
dato-input felt i en tabel

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#30]
Hej dkfds,
Vi har situation, hvor brugeren skal indtaste en dato i en tabel-række.  Datepickeren i dkfds har ekstra labels (dag, måned, år), hvilket gør at dato-input fylder mere i højden end de resterende input felter i tabel-rækken. 
Vi har forsøgt at lave løsning uden tabel, hvor input er venstre opstillet efter dkfds formular struktur. Men vi har flere selvbetjeningsløsninger som også har samme behov for dato-input i tabelrækker, og der skal brugeren have mulighed for at arbejde med mange rækker. 

Hvad er dkfds holdning til dette behov ?  
Må vi bruge et samlet datofelt til tabeller ? 

Nedenstående eksempel vises med kun 2 rækker - men vi har en lignende løsning, hvor brugeren kan tilføje mange rækker.
Vi har brugt class="align-bottom" fra Vertical alignment -Bootstrap i tabellen. 

![image](https://user-images.githubusercontent.com/48348000/56206595-0b4f3780-604d-11e9-984d-37ab978d8702.png)
 

Vi har taget udgangspunkt i dkfds nedenstående eksempel:
 
![image](https://user-images.githubusercontent.com/48348000/56206574-02f6fc80-604d-11e9-8c16-ad4899195b41.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for henvendelsen!

Vi har oprettet en sag på det, og vil vende tilbage lige så snart vi har kigget på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp
Som altid er der flere måder at gribe tingene an på og uanset hvad i vælger vil jeg opfordre Jer til at brugerteste Jeres løsning, og som altid vil jeg meget gerne høre hvad i finder ud af. De tre felter til dato-input er lavet fordi govuk har fundet frem til, at det er den mest optimale måde, at bede brugerne om at indtaste datoer på, hvorfor vi også anbefaler dette. 

Jeg har lavet en måde hvorved de tre felter bibeholdes og i genbruger datovælger mønstret, hvor der bruges hjælpetekst til at vise hvad der skal i det enkelte felt. Det er den model, der vil være mest i tråd med FDS datovælgermønstret.
![Dato i tabel med hjælpetekst-kolonner](https://user-images.githubusercontent.com/44367338/57613600-956cbc00-7577-11e9-80e1-0efd8ee10150.jpg)

Så har jeg lavet en version, hvor i kan anvende et funktionslink til at vise datoen, her kan i så vælge om datoen indtastes via en modal, eller om rækken i tabellen foldes ud eller en tredje mere hensigtsmæssig måde.
![Dato i tabel med funktionslink](https://user-images.githubusercontent.com/44367338/57613616-9ef62400-7577-11e9-9378-17e550e5d2c7.jpg)

Og slutteligt er det muligt at bruge et felt som du omtaler. Jeg så gerne at i brugertestede første forslag inden i vælger denne. Og vælger i denne skal i tillade brugeren alle mulige måder at indtaste på (12-12-2012, 12122012, 12.12.2012, 12/12/2012, 12 12 2012, m.fl. lidt client side js kan rette det til det format serveren accepterer). 
![Dato i tabel med et felt](https://user-images.githubusercontent.com/44367338/57613627-a4ec0500-7577-11e9-9e66-166204be5396.jpg)

Af de tre tror jeg den første er nemmest at betjene, men som sagt ville det være rart med en brugertest.

Mvh
Sune
FDS-team

**Comment by detfaellesdesignsystem** [comment]
@FNA-atp har I besluttet noget her og har brugertestet det?

**Comment by FNA-atp** [comment]
Hej Sune,
Tak for dine forslag - vi har brugertestet nedenstående dato-input felt på vores kommende "ferieplanlæggeren".  Vi kommer til at bruge den fremover i fx. tabeller for at spare plads.

![image](https://user-images.githubusercontent.com/48348000/63942718-9108d800-ca6e-11e9-86e6-abc5cf801a55.png)

**Comment by detfaellesdesignsystem** [comment]
@FNA-atp ok og tak for din tilbagemelding. Har i brugertestresultater for forskellige måder at angive datoer på i tabeller? Ellers vil vi ved lejlighed brugerteste forskellige muligheder for datoangivelse i tabeller og komme med vores anbefaling derefter. 

Mvh
Sune
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Sune,
I må meget gerne brugerteste de andre muligheder - det har vi nemlig ikke gjort :-)

Mvh.
Farzana
