### ISSUE TITLE
"Skift virksomhed" på headeren

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#32]
Hej dkfds,
Vi har et nyt ønske til headeren.

Pt. opgraderer vi nogle af vores selvbetjeningløsninger til dkfds. I den forbindelse har vi fundet ud af, at vi mangler en "Skift virksomhed" funktionalitet på headeren.
Store virksomheder med flere SE-nummer tilknyttet til CVR-nummeret, kan nemt skifte "virksomhed"(vælge et andet SE-nr) og se data for den valgte virksomhed på selvbetjening - uden at loggelogge ud og ind igen med NemLog-in. 

Når der klikkes på "Skift virksomhed" åbnes der en ny side (på samme vindue), hvor man kan vælge et andet SE-nr. 

**Sådan ser headeren ud nu (i den gamle løsning):** 

![image](https://user-images.githubusercontent.com/48348000/56806338-ef594c00-682b-11e9-820d-fb16a9f3fa5e.png)

**Her er et forslag (mockup vi har lavet for lang tid siden):** 

![image](https://user-images.githubusercontent.com/48348000/56806374-0ac45700-682c-11e9-8976-75a5531aa74a.png)

**Sådan ser den nye dkfds header ud:**

![image](https://user-images.githubusercontent.com/48348000/56806995-d6519a80-682d-11e9-9f68-bde2f49def86.png)
 
 Vil vil meget gerne høre om, I har et forslag til placeringen/designet af "Skift virksomhed".

Glæder mig til at høre fra jer :-)

Vh.
Farzana
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Jeg kan godt huske den løsning fra for lang tid siden :) Grunden til at den blev afvist er at Virk toppen er forbeholdt Log af og NemLog-in oplysninger og for at skifte NemLog-in bruger skal man logge af og på igen. Så altså i toppen af siden skal log af og NemLog-in oplysningerne være. 

Vi har forsøgt at lave en header, der tilgodeser en masse udfaldsrum, så jeg skulle mene at i har flere muligheder, evt. også flere muligheder end jeg foreslår her. Dernæst så skal mine forslag ses i lyset af, at jeg ingenlunde kender til Jeres løsning eller kan gennemskue hvordan løsningen virker, så jeg er hæmmet af manglende viden. Til sidst så bør den løsning i lander på nok udsættes for en brugertest, giver det mening for brugeren at placere en skift virksomhedsknap her eller der og kan brugeren gennemskue, hvad forskellen er på det og at skifte NemLog-in identitet.

Et forslag
![Image 18](https://user-images.githubusercontent.com/44367338/56885402-af34dc00-6a6c-11e9-9950-6ce619377fb4.jpg)

Et andet forslag
![Group 1980](https://user-images.githubusercontent.com/44367338/56885411-b22fcc80-6a6c-11e9-9dd7-6b4f5a09c0d6.jpg)

Der kan være andre måder at gøre det på ved brug af de 5 bånd i headeren https://detfaellesdesignsystem.github.io/dkfds-docs/komigang/tildesignere/sideopbygning/#header 

Jeg håber at det kan hjælpe dig videre.

Mvh
Sune
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Sune,
Tak for gode inputs :-)
Det blev til denne løsning:
![image](https://user-images.githubusercontent.com/48348000/57133483-2f2bb080-6da3-11e9-8cc9-2c390b46e454.png)

vh.
Farzana
