### ISSUE TITLE
Overflow menu is not responsive

### ISSUE THREAD

**Issue by nc-jhof** [detfaellesdesignsystem/dkfds-components#33]
The overflow menu presented [here](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/overflowmenu/) is not responsive, as it can be seen [here](https://user-images.githubusercontent.com/47861405/56889978-6125d580-6a78-11e9-8c48-094669a9f0fc.png). When I test this component in Firefox, on an iPhone 6, menu items pop up outside the visible screen.

I expect that the menu, that pops up, adapts to the screen size and changes its size or position on the screen, when the screen is too small to show the menu on the left or the right side of the overflow menu.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 2.0.12

**Smartphone - udfyld venligst følgende (please complete the following information):**
 - Device: iPhone6

**Comment by detfaellesdesignsystem** [comment]
Hi @nc-jhof,

Thank you for contacting us!

We have created an issue in our backlog and will get back to you as soon as we have had someone look at it.

Best regards,
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hi @nc-jhof 

A fix has been implemented and will be available in the next release.

Best regards,
Kristina Jensen
Det Fælles Designsystem
