### ISSUE TITLE
unødvendige styles

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#34]
Hej dk-fds,
Vi har 2 små forslag til opdatering af nedenstående styles:

1. drop-down menupunkt sætter en border-top på:
![image](https://user-images.githubusercontent.com/48348000/57136562-83d42900-6dad-11e9-894d-4e47eee04178.png)

2. Nogle unødvendige styles bliver sat på kontakt-linket, se venligst her:
![image](https://user-images.githubusercontent.com/48348000/57136657-bed65c80-6dad-11e9-99bb-6a57ae332c1a.png)
 
Håber ovenstående giver mening :-)

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for henvendelsen!

Vi vil da lige kigge på det, og vende tilbage.

Med venlig hilsen
Kristina Jensen

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp ,

De to issues er nu blevet løst og kommer med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
