### ISSUE TITLE
Print - Firefox browser

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#35]
**Firefox kan ikke udskrive hele indholdet** 
Firefox printer kun det indhold som kan vises på 1 stk. side, og resten af indholdet bliver derfor slet ikke udskrevet. Dette giver især uhensigtsmæssigheder ved udskrivning af tabeller med mange rækker. 

**I kan selv teste efter på disse to dkfds eksempel sider:** 
https://detfaellesdesignsystem.github.io/dkfds-docs/pages/eksempler/aktindsigt/aktindsigt-2/
https://detfaellesdesignsystem.github.io/dkfds-docs/pages/eksempler/strategiske-virksomhedsalliancer/virksomhedsalliancer-1/

**Firefox og flexbox**
Firefox supportere umildbart ikke flexbox som grid i print view. 
Har dkfds mulighed for at tilføjet et style fix på print media, således at al display 'flex' erstattes med display 'block/inline-block' ?

Relateret link: https://support.mozilla.org/da/questions/1198054

Med venlig hilsen 
Laura Beck 
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin ,

Tak for din henvendelse.

Vi har allerede en sag i backloggen om at vi skal kigge på print css, så jeg smider denne del med i samme omgang.

Vi vender tilbage, når vi har kigget på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Har I fået kigget på denne fejl? Den er meldt ind som kritisk fejl hos os - da vi snart(slut juli) går i luften med "Se feriepenge" selvbetjening på borger.dk - og målgruppen for den løsning forventes at udskrive ferieoversigten ret tit -  og det skal man kunne i alle browsere :-/

vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Den ligger stadig i backloggen. Vi vil prioritere den og forhåbentlig vil den nå at blive testet inden release i løbet af denne uge, så den kan nå at komme med.

Jeg sørger lige for at holde dig opdateret her i tråden.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Fornemt - tak for det Kristina.

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp og @laclogin,

Vi har nu indført et fiks, som vil være med i næste release, som kommer ud i dag eller i morgen.

Bemærk at vi har tilføjet minimal CSS til print. Man kan tilpasse sin print side yderligere ved at bruge klassen `d-print-block` på elementer, hvor det viser sig nødvendigt. Man kan ligeledes skjule elementer med klassen `d-print-none`. Se mere her: [https://designsystem.dk/komigang/tiludviklere/utilities/#display](https://designsystem.dk/komigang/tiludviklere/utilities/#display)

Noget andet I bør være opmærksomme på, er at Firefox ikke kan håndtere fieldset, som indeholder lange formularer (så det fylder mere end én side) i print. Vi har på nuværende tidspunkt ikke kunne finde frem til et CSS fiks for det - fejlen ser umiddelbart ud til at være over 10 år gammel på Firefox' side, så vi regner ikke med et fiks inden for nærmeste fremtid.

Det I KAN gøre for at løse det, er ved at bruge `div` element med visse attributter i stedet for `fieldset` elementet. Skærmlæsere vil forstå sammenhængen mellem elementerne på samme måde som med `fieldset`.
Se nedenstående eksempel:
<pre>
&lt;div role="group" aria-describedby="id-of-heading"&gt;
	&lt;h2 id="id-of-heading"&gt;Min legend overskrift&lt;/h2&gt;
	&lt;div class="form-group"&gt;
		// label og felt her
	&lt;/div>
	&lt;div class="form-group"&gt;
		// label og felt her
	&lt;/div>
	&lt;div class="form-group"&gt;
		// label og felt her
	&lt;/div&gt;
&lt;/div&gt;
</pre>

Eksempel kan ses her **efter release**: [https://designsystem.dk/pages/eksempler/aktindsigt/aktindsigt-2/](https://designsystem.dk/pages/eksempler/aktindsigt/aktindsigt-2/)

Sig endelig til, hvis I har spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Version 4.3 er nu tilgængelig.

Jeg lukker sagen her.
