### ISSUE TITLE
Mangler eksempel med venstremenu/Trinindikatorer

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#36]
Hej dk-fds,
Vi er i gang med at opgradere en løsning på borger.dk ( med [venstremenu](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/sidenav/)) og en på virk.dk(med [trinindikatorer](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/trinindikatorer/).

Det ville være lækkert med et par eksempler, hvor de to komponenter bliver brugt (ikke i samme løsning). Det vil spare os tid, og svare på vores spørgsmål omkring burger-menu og mobilvisning osv.

m.v.h.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp ,

Tak for din henvendelse!

Vi har et par eksempler på sidemenu og trinindikator (overflow menu):

Sidemenu: 
- https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/?s=borgerdk
- https://detfaellesdesignsystem.github.io/dkfds-docs/komigang/tildesignere/sideopbygning/?s=borgerdk

Trinindikator:
- https://detfaellesdesignsystem.github.io/dkfds-docs/pages/eksempler/aktindsigt/aktindsigt-2/?s=virkdk
- https://detfaellesdesignsystem.github.io/dkfds-docs/pages/eksempler/AES-erstatningssag/aes-9/?s=virkdk

Jeg opretter en sag på at vi skal have et eksempel, hvor vi også gør brug af nogle af de andre trinindikatorer.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Bemærk at eksemplet på sidemenuen er selve FDS dokumentationssitet, og ikke selve indholdsteksten på siderne.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Hvor smart :-D havde ikke lige tænkt at bruge sitet som eksempel :-)

men jo, vi ville blive glade for at se et eksempel med "Trinindikator med information" :-)

M.v.h.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana

Det er noteret. Eksemplerne bør altid afspejle best practise, hvorfor vi også kommer til at ændre i eksemplerne og tilføje til dem. Vi er dog ikke nået til eksemplerne endnu i backloggen. Og så lige den sædvanlige :) Er i sikre på at i behøver en trinindikator? https://design-patterns.cloudapps.digital/#progress-indicators 

Mvh
Sune
FDS

**Comment by FNA-atp** [comment]
Hej Sune,
Super, tak for det :-)

Lige i denne løsning er det nødvendigt med en trinindikator (Trinindikator med information). Løsningen er meget kompleks og trinene er dynamiske.

Du får lige et billede af den: 
![image](https://user-images.githubusercontent.com/48348000/57769578-8c622300-770e-11e9-9da5-d5eacf4efac5.png)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Vi har rettet nogle eksempelsider til, så trinindikatoren vises på andre måder. Ændringen vil komme med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
