### ISSUE TITLE
Top og bottom padding på mobil-menu

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#39]
Hej dk-fds,
Vi arbejder pt. på en selvbetjeningløsning med venstremenu (bruger topnavigation til at vise mobil-menuen)- og i den forbindelse har vi lagt mærke til at padding på mobil-menuen er ikke ens:

Mobilmenu fra jeres site:
![image](https://user-images.githubusercontent.com/48348000/58864818-b4adc380-86b5-11e9-9602-e96bd2a039fa.png)

Mobilmenu fra en af eksemplerne:
![image](https://user-images.githubusercontent.com/48348000/58864876-d1e29200-86b5-11e9-8c77-a5b143e3fc6f.png)

Kunne man ikke beholde farve-markering(rød, blå) af den aktive side? det vil give genkendelighed på tværs af alle str. enheder? 

mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
@FNA-atp Tak. Det bliver fikset med det samme. 

Mvh
Sune
Team FDS

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Denne er blevet fikset i tidligere release, så jeg vil lukke sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
