### ISSUE TITLE
Multiselect dropdown does not handle optgroups correctly

### ISSUE THREAD

**Issue by atoftegaard** [detfaellesdesignsystem/dkfds-components#4]
Each optiongroup gets an unclickable checkbox in the left of the dropdown. It looks like a styling issue, see the attached screenshot.

![image](https://user-images.githubusercontent.com/6214674/51910837-97e44500-23d0-11e9-99ed-3daf4f2b0b06.png)

**Comment by KJNC** [comment]
Hi atoftegaard,

Thank you for contacting us regarding this issue!

We've fixed the bug and a new version of dkfds-plugins has been released. Please update to the newest version.

Best regards,
Kristina Jensen
Det Fælles Designsystem
