### ISSUE TITLE
Der er ikke plads til store specialtegn i inputfelt (Chrome)

### ISSUE THREAD

**Issue by postergaard** [detfaellesdesignsystem/dkfds-components#40]
**Bekskriv fejlen (Describe the bug)**
Når man skriver store special tegn (Á É Ä Õ etc) og Å bliver det øverste skåret væk i inputfelterne i Chrome

**Genskab fejlen (To Reproduce)**
Sådan genskabes fejlen (Steps to reproduce the behavior):
1. Skriv special tegn (Á É Ä Õ) og Å i et input felt
2. Se at det øverste ikke bliver vist

**Indsæt link (Add a URL)**
https://designsystem.dk/komponenter/form-controls/ 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/47414075/59417222-1c0af800-8dc7-11e9-9004-3d9ce4842c21.PNG)

**Sådan burde det fungere (Expected behavior)**
Input felt burde have en større height

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by postergaard** [comment]
Har I en status på denne sag?

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Vi har oprettet en sag på det, og vil vende tilbage.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Der er lavet et fiks, som vil være med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Mange tak

**Comment by postergaard** [comment]
Hej @detfaellesdesignsystem / Kristina

Problemet er løst med at 'bollen' på Å nu vises, men hvis man markerer teksten i alle browsere, bliver 'bollen' stadig ikke markeret med (se screenshots)


![Overstreget_bolle_kommer_ikke_med](https://user-images.githubusercontent.com/47414075/63686558-7c280c80-c802-11e9-83b4-5c6dfa7f560e.PNG)

Med venlig hilsen Pernille

**Comment by detfaellesdesignsystem** [comment]
Det er fikset fra Version 4.3.0, 04-07-2019 https://designsystem.dk/omdesignsystemet/releases/. Så jeg lukker dette issue. Tak for hjælpen.

Mvh
Sune
Det Fælles Designsystem

**Comment by postergaard** [comment]
Hej @detfaellesdesignsystem / Sune

Jeg tror du misforstår. Fejlen fremkommer nu, når man <b>markerer</b> teksten i inputfeltet, som vist på eksempel i forrige kommentar. 

Billederne er fra jeres hjemmeside, så I kan selv teste det af:
https://designsystem.dk/komponenter/form-controls/#felter 

Med venlig hilsen
Pernille

**Comment by detfaellesdesignsystem** [comment]
@postergaard beklager, det er mig der har været for hurtig på aftrækkeren. Jeg smider det i backloggen som et nyt issue og genåbner issuet.

Mvh
Sune
Det Fælles Designsystem

**Comment by postergaard** [comment]
Mange tak.

Med venlig hilsen
Pernille

**Comment by postergaard** [comment]
Hvad status på denne sag?

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Der er en fejl med fonten IBM Plex Sans, som ikke kan løses herfra. Vi er derfor nødt til at indsende fejlen til udviklerne af fonten. Vi vender lige tilbage, når vi ved mere.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi har endelig fået svar på vores henvendelse til folkene bag IBM Plex, og de har lavet en ny version, der løser dette issue.

Den nye version vil derfor komme med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
