### ISSUE TITLE
card-action og card-footer

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#42]
Hej DKFDS, 

Vi benytter flere cards med fuld højde klassen `card-align-height`.  Vi ønsker derfor at, kunne aligne card-actions til bunden af alle cards, præcis ligesom bootstrap anvender i deres cards med `card-footer`.  https://getbootstrap.com/docs/4.3/components/card/#card-groups

Er det noget som I har overvejet at implementere i dkfds card ? 

Med venlig hilsen 
Laura Beck 
ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Vi har den med i nuværende sprint, så det vil være med i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Jeg lukker denne sag for nu.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Hej Kristina, 

Det er fornemt. Mange tak for hjælpen. 

Med venlig hilsen 
Laura Beck 
ATP
