### ISSUE TITLE
mangler border-style på last of type <th> 

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#44]
Hej dk-fds,
`<th>` på table mangler border (eller korrekt farve)- fejlen ses kun, når man har vertikal header.

![image](https://user-images.githubusercontent.com/48348000/60433102-46044d00-9c04-11e9-87ab-4ecc8a07b6f4.png)

fejlen kan ses her: https://designsystem.dk/komponenter/tables/#standard 

vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for din henvendelse!

Vi har oprettet en sag på dette, og vil kigge nærmere på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp ,

Det er nu fikset og vil være med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
