### ISSUE TITLE
udvidelse af table--responsive-headers

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#45]
Hej dk-fds,
I vores selvbetjeningløsninger arbejder vi med komplekse tabeller med mange kolonner- og ønsker friheden til at kunne vælge breakpointet for responsive headers i tabeller. 

Har I mulighed for at udvide klasserne?

**Forslag:**
```
table--sm--responsive-headers
table--md--responsive-headers
table--lg--responsive-headers
table--xl--responsive-headers
```

vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for din henvendelse!

Vi har oprettet en sag på dette, og vil kigge nærmere på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Klasserne vil være tilgængelige i næste release.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
