### ISSUE TITLE
Modal printes 2 gange 

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#46]
Hej dk-fds,
Ved print (ctrl+p) udskrives en modal 2 gange. 
Det kan testes her: https://designsystem.dk/pages/eksempler/aktindsigt/aktindsigt-1/ 
![image](https://user-images.githubusercontent.com/48348000/60496382-f7fa5280-9cb2-11e9-88b7-b2b7b2b747d4.png)

Har I mulighed for at se på denne fejl? :-)

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Tak for din henvendelse!

Vi har oprettet en sag på dette, og vil kigge nærmere på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej igen,
Når man printer modalen ud på IE - 
Side 1: Modalens tekst ligger  oven i den tekst, der ligger under modalen, hvilket gør teksten helt ulæselig. 
Side 2: Udprintet er pænt og læsbart. 

**Side 1:** 
![image](https://user-images.githubusercontent.com/48348000/60515858-da41e300-9cdc-11e9-8299-adbbd38bdeca.png)


**Side 2:** 
![image](https://user-images.githubusercontent.com/48348000/60515885-ea59c280-9cdc-11e9-9e76-c30919fc3e2b.png)

Har I mulighed for at ekskludere side 1 på IE?

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Vi har nu implementeret en løsning, som vil komme med i næste release.

Sidens indhold bliver kort sagt helt skjult, når en modal vises, så man undgår dette issue med flere sider og dermed duplikater af modalen.

Sig endelig til, hvis du har spørgsmål.

Jeg lukker dog sagen her - men du er velkommen til at genåbne den.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Det lyder godt - Tak for det :-)
Mvh.
Farzana

**Comment by FNA-atp** [comment]
Hej igen,
Det ser ud til at fejlen stadig er der, selvom vi har opdateret til 4.4.0. Modalen udskrives de antal gange/sider, som siden i baggrunden har. 

Skal vi gøre andet end at opdatere versionen for, at release-ændringer bliver slået igennem?

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Måden det bla. er blevet løst på, er at der bliver sat en klasse på body `modal-active`. Denne klasse gør at alt på siden - på nær modal, bliver skjult ved print, og siden derfor ikke fylder mere end nødvendigt.

Er du sikker på, at I henter 4.4.0 versionen af dkfds.js ind i projektet?

Evt. tjek at klassen bliver sat, når jeres modal er aktiv.

I hvilken forbindelse er jeres modal sat ind på siden?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by clpatp** [comment]
Når jeg lige tester så bliver der sat modal-open på body - ikke modal-active ?

**Comment by detfaellesdesignsystem** [comment]
Hej @clpatp ,

`modal-open` er ikke en klasse der kommer fra vores løsning. Det er dog den klasse bootstrap sætter på body, når deres modal er åben. Jeg vil anbefale, at du kigger løsningen igennem.

Om det lige er bootstrap der gør sig gældende her, skal jeg ikke kunne sige. Men det er i hvert fald noget lignende de gør.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by clpatp** [comment]
Hej Kristina

vi kigger på tingene igen og vender tilbage hvis det bliver nødvendigt :)

**Comment by FNA-atp** [comment]
Hej Kristina,
Vi har nu kigget på denne igen. Den løsning(vha. javascript), som I har lavet, fungerer ikke hos os, fordi vi arbejder kun med Typescript og angular.

Er det muligt for jer at lave en anden løsning? eller skal vi lave en workaround hos os?

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp ,

Hvad er det der gør at den ikke virker hos jer?

Jeg sidder faktisk lige nu og er ved at tilpasse modal komponenten. Så hvis jeg ved nærmere, hvad det er der gør, at I ikke kan bruge den nuværende, så kan jeg måske gøre noget ved det nu her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Hvis vi kun indsætter classe= "modal-active" ind på <body>, så skjules alt andet indhold på siden ved print. 
![image](https://user-images.githubusercontent.com/48348000/64422756-1ad72780-d0a5-11e9-9abc-607257294eea.png)
![image](https://user-images.githubusercontent.com/48348000/64422885-6ab5ee80-d0a5-11e9-8d2f-acc6e2800b71.png)


Når modallen er åben:
![image](https://user-images.githubusercontent.com/48348000/64422958-95a04280-d0a5-11e9-8ada-3bef4aee563e.png)

Her skjules alt andet indhold på siden, som den skal:

![image](https://user-images.githubusercontent.com/48348000/64423059-e152ec00-d0a5-11e9-9f48-10889238882e.png)


Her har vi ikke sat "modal-active" ind på <body>: 
![image](https://user-images.githubusercontent.com/48348000/64423205-3bec4800-d0a6-11e9-8d82-1582753aad31.png)
![image](https://user-images.githubusercontent.com/48348000/64423224-4575b000-d0a6-11e9-92b0-6fb1bfee5053.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp ,

Jeg må indrømme, at jeg ikke forstår dit svar.

I forbindelse med dit svar: "Den løsning(vha. javascript), som I har lavet, fungerer ikke hos os, fordi vi arbejder kun med Typescript og angular." spørger jeg ind til, hvad det helt præcist er der ikke fungerer hos jer?

`modal-active` sættes på body elementet, når en modal er aktiv. Dette for at skjule det bagvedliggende indhold på siden og derved undgå at der printes unødigt ekstra sider samt at modalen ikke printes oven på andet tekst.

Sig endelig til, hvis noget af det jeg skriver ikke giver mening.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej igen :-)
Den logik, som I har lavet med javascript(jquery), hvor "modal-active" sættes på, når en modal er åben og tages ned  igen, når den ikke er aktiv/åben.  Det virker ikke hos os - fordi vi arbejder/bruger ikke jeres javascript. Vi bruger kun html-styling fra DFS.

Hvis vi skal få "modal-active" til at virke hos os, skal vi selv lave logikken hos os og lave en workaround, hver gang vi bruger en modal i en løsning. Medmindre I kan løse problemet vha. CSS/Sass.

Håber ovenstående giver mening :-)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Javascripten i FDS er en vigtig del af at det hele virker. Vi kan ikke tage højde for projekter, som kun vælger af bruge halvdelen af dkfds desværre.

Jeg har dog lagt en sag i backloggen om at vi bør kigge på, hvordan vi kan gøre javascripten tilgængelig for typescript/angular projekter. Hvis du har en idé her, så hold dig endelig ikke tilbage.

Da I ikke bruger dkfds javasvcripten, så skal I selv sørge for at replikere samme opførsel i jeres eget projekt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Kristina,
Det er ikke kun i et projekt , men alle vores løsninger/projekter i ATP er bygget sådan, desværre :-/  Det kunne være fedt, hvis I kunne tage det med i jeres overvejelser, når nogle issues skal løses vha. javascripten. 

Håber, I kan finde en løsning på, hvordan vi kan bruge javascripten i vores projekter.  Jeg skal melde tilbage, hvis vi støder på en løsning :-)

Vh.
Farzana
