### ISSUE TITLE
Funktion til Expandable row

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#48]
Hej dkfds, 

Vi har på flere løsninger behov for en knap/knapper som kan udvide og sammenfolde samtlige rækker i en table med 'Expandable rows'. 

https://designsystem.dk/preview-components/datatables--expandable-row

Vi har ofte tabeller med mange rækker, derfor har det været nødvendigt at have fold ind/fold ud knapper, både i toppen og bunden af tabellen. 

Har I en anbefaling for hvad vi skal bruge som dkfds standard ? 

Med venlig hilsen 
Laura Beck 
ATP

*Indtil videre har vi anvendt en sekundær knap "Se alle detaljer/Luk se detaljer".
![dkfds](https://user-images.githubusercontent.com/25169794/61862394-1c220b80-aece-11e9-93fc-24f85b578149.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Tak for din henvendelse. Vi har oprettet sagen, og vil vende tilbage med et svar.

Med venlig hilsen
Det Fælles Designsystem
Kristina Jensen

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin 

Det er en god ide at anvende en sekundærknap som i har gjort. Jeg har forsøgt at finde nogle standarder/konventioner for sådan funktionalitet, men har ikke fundet noget endnu. Hvis du har fundet eller finder noget, må du gerne sende det til os. Vi fortsætter, men indtil vi finder en standard, virker dit forslag fornuftigt. Sig til hvis i brugertester tabellen og om brugerne kunne finde ud af det. Jeg lukker ikke storien endnu, men ville lige give dig en opdatering.

Mvh
Sune
Det Fælles Designsystem

**Comment by TinaLinneOlsen** [comment]
Hej FDS, 

Laura er ikke længere ansat i ATP, så hende hører i nok ikke mere fra ;) Men det er bestemt stadig et relevant område. Vi hører meget gerne, hvis i finder andre måder at gøre det på.

Ville nedenstående også være acceptabelt? Altså hvor man på label linjen kan folde ind og ud ved at bruge plus (+) og minus (-) ikon? 
![image](https://user-images.githubusercontent.com/49032957/65303473-7235c700-db7e-11e9-97c1-43ff653f06e8.png)

Lidt i samme logik får vi også brug for at kunne markere samtlige tjekbokse i en tabel. Vil nedenstående her være acceptabelt? 
![image](https://user-images.githubusercontent.com/49032957/65304031-defd9100-db7f-11e9-949e-c9caa4c49c06.png)

**Comment by TinaLinneOlsen** [comment]
Lige for at præcisere min forgående besked, så går mit spørgsmål på, om det generelt vil være okay at bruge labelrækken til at påvirke samtlige rækker i tabellen (som alternativ til den knap som oprindeligt blev forslået i den her tråd)? Det kan så både være i tilfældet med at folde samtlige rækker ind/ud eller check/uncheck samtlige tjekbokse. 

![image](https://user-images.githubusercontent.com/49032957/65307127-63074700-db87-11e9-8d4b-a136706fcdff.png)

![image](https://user-images.githubusercontent.com/49032957/65307236-a5308880-db87-11e9-902f-bf15eab3cb31.png)

**Comment by detfaellesdesignsystem** [comment]
Hej Tina @TinaLinneOlsen 

GovUK gør noget forskelligt på deres moderside og USWDS har ikke noget om det, og derudover har vi ikke kunnet finde en konvention eller defacto standard for dette mønster. 

Vi tænker at vi kører med din model med en teritiærknap med et plus og et minus ikon i - vi tror ikonet vil højne forståelsen af sammenhæng til tabellen. 

[ + Vis alle detaljer ]
[ - Skjul detaljer ]

Det vil være fint at bruge logikken til checkbokses også.

Vi er meget interesserede i at høre om dette mønster virker for brugerne, hvis i tester det? 

Mvh
Sune

**Comment by TinaLinneOlsen** [comment]
Vi har brugt checkbox logikken i den tidligere løsning, og der forstår brugerne det godt. Plus (+) og minus (-) logikken har vi ikke brugt før, men det skal helst sikkert testes.
