### ISSUE TITLE
Multiselect dropdown does not handle long options

### ISSUE THREAD

**Issue by atoftegaard** [detfaellesdesignsystem/dkfds-components#5]
Options with long names are not handled correctly, see attached screenshot.

We would prefer a cross-browser "ellipsis"-truncation, or at least a white-space word wrapping.

![image](https://user-images.githubusercontent.com/6214674/51910937-d843c300-23d0-11e9-8f41-4e54c3b179b4.png)

**Comment by KJNC** [comment]
Hi atoftegaard,

Thank you for contacting us regarding this issue!

We've fixed the bug and a new version of dkfds-plugins has been released. Please update to the newest version.

Best regards,
Kristina Jensen
Det Fælles Designsystem
