### ISSUE TITLE
Problematisk brug af ARIA-attribut på solution-heading

### ISSUE THREAD

**Issue by martinhoegh** [detfaellesdesignsystem/dkfds-components#50]
**Beskrivelse af fejlen**
Denne kode i headeren:
```
    <a href="#" title="Hjem" aria-label="logo link" class="alert-leave2">
                    Ansøg om indsigt
    </a>
```
medfører, at skærmlæsere læser "logo link" op fremfor "Ansøg om indsigt". Det kan næppe være hensigten.

**Eksempel**
Fx her: https://designsystem.dk/pages/eksempler/aktindsigt/aktindsigt-1/

**Sådan burde det fungere (Expected behavior)**
Aria-label bør fjernes.

**Desktop - udfyld venligst følgende (please complete the following information):**
 - OS: Win10
 - Alle
 - NVDA

**Comment by detfaellesdesignsystem** [comment]
@martinhoegh jeg har oprettet det i backloggen og vi kigger på det hurtigst muligt.

Mvh
Sune

**Comment by detfaellesdesignsystem** [comment]
Hej @martinhoegh,

Tak for din henvendelse. Den er fikset nu.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
