### ISSUE TITLE
Design for sidestillede knapper 

### ISSUE THREAD

**Issue by KirstenTo** [detfaellesdesignsystem/dkfds-components#51]
Hej 

Jeg er i gang med at designe en løsning, hvor der skal være to ligestillede knapper ved siden af hinanden. 

Jeg har fået oplyst, at jeg skal bruge de primære knapper og tog oprindeligt udgangspunkt i temaet for Borger.dk med grønne knapper som default og sorte som active.

Men efter diskussion i teamet er der enighed om, at det er svært at se, hvilken knap der er klikket på, når den ene er sort og den anden grøn. Pt. er løsningen lavet med neutralt design i stedet for.

Har du nogle anbefalinger til valg af design ved ligestillede knapper?

På forhånd tak for hjælpen :)
Kirsten

**Comment by detfaellesdesignsystem** [comment]
Hej @KirstenTo 

Tak for din henvendelse!

Vi har oprettet en sag og vil vende tilbage til dig.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Kirsten

Tak fordi du inddrager os i Jeres overvejelser. Jeg skal forsøge at hjælpe Jer videre så godt jeg kan, med forbehold for at jeg ikke kender løsningen. Et billedeksempel på det I arbejder på ville gøre det nemmere. Jeg tegner nogle eksempler nederst og beskriver overvejelserne bag, men det er med et kæmpe forbehold, da jeg ikke præcist ved hvad det er jeg giver anbefalinger omkring, hvorfor de bliver generelle.

Når du nævner grønne og sorte knapper, så vil jeg gætte på at i taler om knapperne fra HTML-guiden (https://htmlguide.borger.dk/layout-buttons.html) og ikke fra det Fælles Designsystem (FDS) (https://designsystem.dk/komponenter/buttons/?s=borgerdk), men så nævner du neutraltemaet, hvilket får mig til at tænke at i blander farver fra temaerne i FDS, hvilket absolut ikke er meningen. Uanset så er her en måde i kan løse det på med FDS. 

Vi anbefaler på det kraftigste, at man kun anvender en "primærknap" pr. trin eller side i en løsning og at "primærknappen" er udtryk for den næste, givne eller mest oplagte handling for brugeren, samt at primærknappen altid er venstrestillet. Derudover anbefaler vi gerne at primærknappen forsøges holdt for sig selv ved at distribuere andre knapper i trinnet/på siden om end dette ikke altid lader sig gøre, hvilket jeg antager det ikke gør i Jeres tilfælde.
Skal man have flere valgmuligheder, hvor ingen af dem er den primære (givne) for brugeren, vil de derfor begge være "sekundære" knapper. [Anvender I HTML-guiden er den grønne knap den primære og basisknapper sekundære]. 

Primærknap i FDS
https://designsystem.dk/komponenter/buttons/?s=borgerdk#prim%C3%A6rknap
Sekundærknap i FDS
https://designsystem.dk/komponenter/buttons/?s=borgerdk#sekund%C3%A6rknapper

Eksempel på sidestillet primær og sekundærknap
![image](https://user-images.githubusercontent.com/44367338/63268246-07018800-c294-11e9-9675-0220c84f0d1f.png)

Eksempel på to "ligeværdige" valgmuligheder (vi ville være forsigtige med ligeværdig muligheder side om side)
![image](https://user-images.githubusercontent.com/44367338/63268651-f1409280-c294-11e9-916c-a6a5ef314fff.png)

Jeg håber at dette kan hjælpe Jer videre og ellers er I velkomne til at skrive igen og evt. vedhæfte et billede af siden I arbejder på.

Mvh
Sune
Det Fælles Designsystem

**Comment by KirstenTo** [comment]
Hej Sune

Mange tak for din mail, den kan fint hjælpe mig/os videre.

Og bare for en god ordens skyld, så er jeg med på ikke at blande de to temaer, jeg har åbenbart bare fået formuleret mig lidt kluntet.

Hav en god dag 😊

Venlig hilsen
Kirsten Tønnesen
[Adobe Systems]
Digitaliseringskonsulent  ·  Digital Udvikling
Direkte nummer 48 31 24 89  ·  Mobil 29 72 60 05
E-mail kt@atp.dk<mailto:kt@atp.dk>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP Koncernen på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem <notifications@github.com>
Sendt: 19. august 2019 15:42
Til: detfaellesdesignsystem/dkfds-components <dkfds-components@noreply.github.com>
Cc: Kirsten Tønnesen - KT <KT@atp.dk>; Mention <mention@noreply.github.com>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Design for sidestillede knapper (#51)


Hej Kirsten

Tak fordi du inddrager os i Jeres overvejelser. Jeg skal forsøge at hjælpe Jer videre så godt jeg kan, med forbehold for at jeg ikke kender løsningen. Et billedeksempel på det I arbejder på ville gøre det nemmere. Jeg tegner nogle eksempler nederst og beskriver overvejelserne bag, men det er med et kæmpe forbehold, da jeg ikke præcist ved hvad det er jeg giver anbefalinger omkring, hvorfor de bliver generelle.

Når du nævner grønne og sorte knapper, så vil jeg gætte på at i taler om knapperne fra HTML-guiden (https://htmlguide.borger.dk/layout-buttons.html) og ikke fra det Fælles Designsystem (FDS) (https://designsystem.dk/komponenter/buttons/?s=borgerdk), men så nævner du neutraltemaet, hvilket får mig til at tænke at i blander farver fra temaerne i FDS, hvilket absolut ikke er meningen. Uanset så er her en måde i kan løse det på med FDS.

Vi anbefaler på det kraftigste, at man kun anvender en "primærknap" pr. trin eller side i en løsning og at "primærknappen" er udtryk for den næste, givne eller mest oplagte handling for brugeren, samt at primærknappen altid er venstrestillet. Derudover anbefaler vi gerne at primærknappen forsøges holdt for sig selv ved at distribuere andre knapper i trinnet/på siden om end dette ikke altid lader sig gøre, hvilket jeg antager det ikke gør i Jeres tilfælde.
Skal man have flere valgmuligheder, hvor ingen af dem er den primære (givne) for brugeren, vil de derfor begge være "sekundære" knapper. [Anvender I HTML-guiden er den grønne knap den primære og basisknapper sekundære].

Primærknap i FDS
https://designsystem.dk/komponenter/buttons/?s=borgerdk#prim%C3%A6rknap
Sekundærknap i FDS
https://designsystem.dk/komponenter/buttons/?s=borgerdk#sekund%C3%A6rknapper

Eksempel på sidestillet primær og sekundærknap
[image]<https://user-images.githubusercontent.com/44367338/63268246-07018800-c294-11e9-9675-0220c84f0d1f.png>

Eksempel på to "ligeværdige" valgmuligheder (vi ville være forsigtige med ligeværdig muligheder side om side)
[image]<https://user-images.githubusercontent.com/44367338/63268651-f1409280-c294-11e9-916c-a6a5ef314fff.png>

Jeg håber at dette kan hjælpe Jer videre og ellers er I velkomne til at skrive igen og evt. vedhæfte et billede af siden I arbejder på.

Mvh
Sune
Det Fælles Designsystem

**Comment by TinaLinneOlsen** [comment]
Hej Sune,

I ATP har vi nogle løsninger, hvor man skal vælge mellem to ligestillede muligheder (se nedenstående billeder). Vil i i den situation så anbefale, at man skal bruge den sekundæreknap 'Default' til at starte med, og den sekundæreknap 'Active' når man har valgt en af mulighederne? 

![image](https://user-images.githubusercontent.com/49032957/63425940-f2e39500-c411-11e9-9d6e-8ee6a2eae4bf.png)

![image](https://user-images.githubusercontent.com/49032957/63425958-fd9e2a00-c411-11e9-9090-b43b8908f3f3.png)

![image](https://user-images.githubusercontent.com/49032957/63426045-34744000-c412-11e9-94e3-a4e6b6a9aef3.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @TinaLinneOlsen Tak for dit spørgsmål. Vi vil ikke anbefale at anvende almindelige knapper til en radioknapfunktionalitet, hvor vil vil anbefale at anvende radioknapper (https://designsystem.dk/komponenter/form-controls/#radioknap). Så vores model ville se således ud, hvilket også vil være mit forslag til jer.
![image](https://user-images.githubusercontent.com/44367338/63684101-6283c680-c7fc-11e9-8f37-437d6bb6209a.png)
Håber det kan bruges. 
Mvh
Sune
Det Fælles Designsystem

**Comment by TinaLinneOlsen** [comment]
Hej Sune. Det giver god mening. Det er godt at vide at det er anbefalingen fra FDS, hvis nogle af vores eksisterende løsninger skal laves om til FDS design.

**Comment by detfaellesdesignsystem** [comment]
Tak for Jeres spørgsmål, jeg er glad for at jeg kunne hjælpe. Jeg lukker issuet.

Mvh
Sune
Det Fælles Designsystem
