### ISSUE TITLE
Firefox: td .table.table--borderless giver gaps mellem <td>

### ISSUE THREAD

**Issue by NCJasper** [detfaellesdesignsystem/dkfds-components#52]
**Beskrivelse:**
Styling for `td .table.table--borderless` har en transparent left og right border, som gør at der opstår et pixel gap imellem de enkelte `<td>`. Det er en minimal fejl, men den springer i øje når man har tables med større dataset.
Umildbart virker det som om at det er border right som kan ses, men fejlen ses kun på border top.

**Screenshots**
Selve fejlen kan ses her:
![image](https://user-images.githubusercontent.com/45785931/63326997-aa52ab80-c32d-11e9-9e58-394dc443a28b.png)

Styling classes kan ses her
![image](https://user-images.githubusercontent.com/45785931/63327232-19300480-c32e-11e9-9151-dc80eef075a9.png)

**Sådan burde det fungere (Expected behavior)**
Der bør ikke være gaps i mellem td'er

**Desktop:**
 - OS: Win10
 - Browser Firefox (Fejlen kan kun ses i FF, har tjekket IE11 og Chrome 76.0.3809.100)
 - Version 68.0.1

**Comment by detfaellesdesignsystem** [comment]
@NCJasper. Jeg opretter det i backloggen til snarlig fix. Tak fordi du gør os opmærksomme på det.

Mvh
Sune
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @NCJasper,

Den er fikset, og vil være med i næste release.

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
