### ISSUE TITLE
hjælp til slet knap

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#54]
Hej DFS,
Vi er igang med at opgradere en af vores selvbetjeningløsninger til DFS (nedestående billede), og i den forbindelse mangler vi en rød slet knap.
Vi synes ikke at det fungerer med jeres foreslag ["ikon som knap"](https://designsystem.dk/komponenter/buttons/?s=styleguide), se nedenstående skærmbillede:
 
![image](https://user-images.githubusercontent.com/54143827/63497463-10713700-c4c4-11e9-8f79-7407c67457ac.png)

mvh. 
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp. Tak for spørgsmålet. 

Jeg skal svare efter bedste evne og i forhold til mit ringe kendskab til løsningen. 

Pt. har vi ikke farvede knapper til specifikt kommunikative formål, men vi har en del variationer over knapper, fx "Knap med ikon" 
![image](https://user-images.githubusercontent.com/44367338/63686419-1fc4ed00-c802-11e9-872b-dc7f3a012417.png)
Vi har også funktionslinks, der kan anvendes
![image](https://user-images.githubusercontent.com/44367338/63686928-7aab1400-c803-11e9-9de1-c657173962a6.png)
De vil kunne anvendes for sig selv, men de er ikke specificeret i røde farver. Det kunne se således ud:
![image](https://user-images.githubusercontent.com/44367338/63687085-ed1bf400-c803-11e9-843c-7b3a3b592370.png)
eller
![image](https://user-images.githubusercontent.com/44367338/63687111-ff962d80-c803-11e9-9833-ed5dd5617a36.png)

Derudover indeholder FDS komponenten "beskeder (alerts)" til kommunikative formål. Hvis jeg kobler knap med ikon og en besked kan jeg få et resultat som fx dette
![image](https://user-images.githubusercontent.com/44367338/63686455-366b4400-c802-11e9-8f2b-c6f7452c404c.png)
eller ved at anvende en "besked (alert)" med en teritærknap i, så således
![image](https://user-images.githubusercontent.com/44367338/63686519-631f5b80-c802-11e9-8114-0ecef394e76c.png)

Hvis der er behov for særligt kommunikativt farvede knapper vil det være oplagt at tage med på Samarbejdsforum (https://designsystem.dk/omdesignsystemet/samarbejdsforum/) næste gang. 

Jeg håber det kan hjælpe og ellers så tag fat i mig igen.

Mvh
Sune
Det Fælles Designsystem

**Comment by JAU-atp** [comment]
Hej Sune,
Tak for dit svar, jeg vil gøre brug af dit forslag med knap og ikon

Venlig hilsen
Josephine Frederikke August Nielsen
[Adobe Systems]
Udvikler  ·  Frontend
IT  ·  Allerød
Direkte nummer xx
E-mail jau@atp.dk<mailto:jau@atp.dk>

Besøgsadresse  ·  Sortemosevej 2 · 3450 Allerød
Postadresse  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP Koncernen på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem <notifications@github.com>
Sendt: 26. august 2019 13:23
Til: detfaellesdesignsystem/dkfds-components <dkfds-components@noreply.github.com>
Cc: Josephine August Nielsen - JAU <JAU@atp.dk>; Mention <mention@noreply.github.com>
Emne: Re: [detfaellesdesignsystem/dkfds-components] hjælp til slet knap (#54)


Hej @JAU-atp<https://github.com/JAU-atp>. Tak for spørgsmålet.

Jeg skal svare efter bedste evne og i forhold til mit ringe kendskab til løsningen.

Pt. har vi ikke farvede knapper til specifikt kommunikative formål, men vi har en del variationer over knapper, fx "Knap med ikon"
[image]<https://user-images.githubusercontent.com/44367338/63686419-1fc4ed00-c802-11e9-872b-dc7f3a012417.png>
Vi har også funktionslinks, der kan anvendes
[image]<https://user-images.githubusercontent.com/44367338/63686928-7aab1400-c803-11e9-9de1-c657173962a6.png>
De vil kunne anvendes for sig selv, men de er ikke specificeret i røde farver. Det kunne se således ud:
[image]<https://user-images.githubusercontent.com/44367338/63687085-ed1bf400-c803-11e9-843c-7b3a3b592370.png>
eller
[image]<https://user-images.githubusercontent.com/44367338/63687111-ff962d80-c803-11e9-9833-ed5dd5617a36.png>

Derudover indeholder FDS komponenten "beskeder (alerts)" til kommunikative formål. Hvis jeg kobler knap med ikon og en besked kan jeg få et resultat som fx dette
[image]<https://user-images.githubusercontent.com/44367338/63686455-366b4400-c802-11e9-8f2b-c6f7452c404c.png>
eller ved at anvende en "besked (alert)" med en teritærknap i, så således
[image]<https://user-images.githubusercontent.com/44367338/63686519-631f5b80-c802-11e9-8114-0ecef394e76c.png>

Hvis der er behov for særligt kommunikativt farvede knapper vil det være oplagt at tage med på Samarbejdsforum (https://designsystem.dk/omdesignsystemet/samarbejdsforum/) næste gang.

Jeg håber det kan hjælpe og ellers så tag fat i mig igen.

Mvh
Sune
Det Fælles Designsystem
