### ISSUE TITLE
udvidelse af Expandable table

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#55]
Hej dfs,
Næste alle vores (mest erhverv) løsninger indeholder tabeller i tabeller. Dem har vi ofte print og styling problemer med. 
pt. skal vi opgradere nedenstående tabel til DFS:
![image](https://user-images.githubusercontent.com/48348000/63520280-b9d02100-c4f4-11e9-8d9d-23014a8ed369.png)

Kan I hjælpe med at oprette et eksempel på ovenstående problem under "Avancerede tabeller" https://designsystem.dk/udvidelser/datatables/

mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
@FNA-atp. Tak. Det skal vi få kigget på. Jeg opretter en sag i backloggen.

Mvh
Sune
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Sune,
Vi har lavet nedenstående forslag/udkast. 
![image](https://user-images.githubusercontent.com/48348000/64265562-74b7e000-cf33-11e9-8417-df7f1f7109bf.png)

Er det en No-go? :-)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
@FNA-atp din besked har jeg overset. I har dog ændret lidt i det i forhold til Jeres oprindelige forespørgsel, da i nu placerer en tabel i en accordion. Derfor opretter jeg nu i backloggen at vi også skal have et eksempel på tabeller i accordions :) Det vil nok komme til at ligne det I har tegnet, dog kan det være at plusserne inde i accordionen vil blive rykket ind, så man visuelt kan se et hierarki i plusserne, hvad åbner inde i hvad. Det skal dog tegnes og undersøges først.

For at svare på Jeres oprindelige forespørgsel, så vil vi i et kommende eksempel foreslå at man aligner tabeller i tabeller således:
![image](https://user-images.githubusercontent.com/44367338/68119845-15128c80-ff04-11e9-9956-2639c0669ff9.png)
