### ISSUE TITLE
Skal primærknappen være disabled eller aktiv, når der er påkrævede felter i en <form>?

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#56]
Hej dk-fds,
Har I nogle klar retningslinjer for, hvornår primærknappen skal være aktiv og deaktiveret på en `<form>`, når der er required felter med valideringtekst i formularen. 
Jeg kunne finde dette eksempel: https://designsystem.dk/pages/eksempler/vedhaeft-fil/fil-1/ og på eksemplet ser det ud til at knappen er deaktiveret, før alle obligatoriske felter er udfyldt. 

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp. Som udgangspunkt skal primærknapper ikke være deaktiveret, brugeren skal have en fejlmeddelelse på felter med fejl og der kan evt. sættes fokus på fejlen ved tryk på primærknappen i tilfælde at brugeren ikke kan komme videre. Vi retter eksemplet så det afspejler dette. Tak fordi du skrev. 
Mvh
Sune
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Hej Sune,
Super, tak for det hurtige svar :-)

mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Det var så lidt. Vi fikser det i næste sprint. Jeg lukker dette issue imens.

Mvh
Sune
Det Fælles Designsystem
