### ISSUE TITLE
Ugyldigt link

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#58]
Hej,
Ind på denne side https://designsystem.dk/udvidelser/selectwoo-multiselect/ er der et ugyldigt link. Kan I erstatte linket med et, der virker? :-)

![image](https://user-images.githubusercontent.com/48348000/63997579-2fdd1500-caff-11e9-921e-39ae6da4f436.png)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

Selvfølgelig. Ændringen kommer med i næste release.

Indtil videre kan du dog se, hvordan vi har gjort her: 
[https://github.com/detfaellesdesignsystem/dkfds-docs/blob/master/examples/plugins/selectwoo/js/dkfds-selectwoo-example.js](https://github.com/detfaellesdesignsystem/dkfds-docs/blob/master/examples/plugins/selectwoo/js/dkfds-selectwoo-example.js)

Jeg lukker sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
