### ISSUE TITLE
Udfald ved 'Log af', tryk på logo og inaktivitet

### ISSUE THREAD

**Issue by TinaLinneOlsen** [detfaellesdesignsystem/dkfds-components#59]
Hej FDS,

I ATP har vi talt om, at det kunne være rart med nogle fælles retningslinjer for, hvordan selvbetjeningsløsningerne i forbindelse med at logge af og trykke på logoet fungerer.

Når man trykker enten 'Log af' eller på logoet i øverste venstre hjørne, så får man nedenstående visning (som variere lidt i udseende fra browser til browser). Hvis jeg trykker ok, hvor er det så tænkt man skal lande? Forsiden af virk.dk/borger.dk? Er man logget helt ud af virk.dk/borger.dk eller kun selvbetjeningsløsningen?
![image](https://user-images.githubusercontent.com/49032957/64327970-eabc5580-cfcc-11e9-9690-956c50447a66.png)

Hvad er grunden til at man får vist en modal fra browseren og ikke en modal i FDS design? Fx noget ala nedenstående. 
![image](https://user-images.githubusercontent.com/49032957/64328355-9796d280-cfcd-11e9-9185-202025d13147.png)

I ATP har vi desuden en del løsninger som logger brugerne af efter et tidsrum med inaktivitet. Desuden adviseres de 5 minutter inden log af faktisk finder sted, så de kan forblive logget på. Det ser typisk ud i stil med nedenstående. Er det noget i har en holdning til? 
![image](https://user-images.githubusercontent.com/49032957/64328546-ecd2e400-cfcd-11e9-9d49-c3e40fc93c13.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @TinaLinneOlsen tak for issuet. Vi har allerede "session timeouts" i backloggen, men jeg vil nu smide "system advarslen" i også og så vender vi tilbage.
Mvh
Sune
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej Tina @TinaLinneOlsen 

Vi er stadig i proces med denne. Komponenten er ikke klar endnu, da vi mangler at have retningslinjer på plads for den.

Her er vores nuværende forslag til en session timeout: https://xd.adobe.com/view/22e36b88-3bf1-4145-7489-69aa1e0b9225-54d2/grid/ (se bort fra de sidste XD sider).

Browseradvarslen, kan sættes op i samme struktur som en session timeout. Det kigger vi også på.

"Når man trykker enten 'Log af' eller på logoet i øverste venstre hjørne, så får man nedenstående visning (som variere lidt i udseende fra browser til browser). Hvis jeg trykker ok, hvor er det så tænkt man skal lande? Forsiden af virk.dk/borger.dk? Er man logget helt ud af virk.dk/borger.dk eller kun selvbetjeningsløsningen?" 

Når man trykker på potal-logoet bør man havne på forsiden af portalen (uden at logge af), hvorfor beskeden også bør tilpasses dette - fx hvis løsningen auto-gemmer løbende, så bør dette fortælles og hvor man evt genoptager eller sletter det man lige har lavet - eller hvis brugeren mister al data ved at gå til forsiden af portalen, så bør der stå det. Men altså uden at logge af. 

Når man trykker på "log af" logger man af NemLog-in (SSO) dvs alle steder. 

Når man logger af vil det være god stil at brugeren havner der, hvor selvbetjeningsløsningen blev påbegyndt (full circle) - fx på den tilhørende intro-/startside afhængigt af portalen.

Vi har foranlediget af dette issue oprettet i backloggen, at vi skal ændre ordlyden på "kvitteringssiden", således at advarslen ikke nævner noget med at "miste data", da brugeren jo er igennem selvbetjeningen og derfor ikke mister data. Advarslens tekst bør i det hele taget tilpasses og afspejle præcist det som sker. 

Det kan også foreslås at man indsætter et link på kvitteringssiden som siger "Luk kvittering og gå til [portal] uden at logge af", således at brugeren kan fortsætte på Virk eller borger.dk uden at logge af, hvis såfremt brugerrejsen fordrer dette. I langt de fleste tilfælde skal brugerne dog typisk kun en ting (pt. - det kan ændre sig med sammenhængende brugerrejser), hvorfor det ikke vil være relevant mange steder.

Som altid er vi interesserede i at høre mere, hvis i brugertester mønstret.

Mvh
Sune
FDS

**Comment by detfaellesdesignsystem** [comment]
Der vil komme patterns til "session udløb" samt "forlad side" scenarie i v8.0.0.

Lukker derfor sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
