### ISSUE TITLE
Multiselect dropdown does not work correctly with remote datasources

### ISSUE THREAD

**Issue by atoftegaard** [detfaellesdesignsystem/dkfds-components#6]
When attaching a remote datascource, several errors happen:

- An unselectable option named "Loading more results..." is fixed at bottom. It should only display when actually loading. See screenshot 1.
- The dropdown is not filtered according to the search term. See screenshot 1, "Option 1" should not be visible.
- When selecting an option, any search term will still be visible in the searchbox. See screenshot 2.

It seems that SelectWoo and/or the Styleguide does not really support basic Select2-features (other than the most basic with only default settings of course).

![image](https://user-images.githubusercontent.com/6214674/51912725-3ffc0d00-23d5-11e9-840c-61e698298134.png)

![image](https://user-images.githubusercontent.com/6214674/51912679-28bd1f80-23d5-11e9-8a74-98fb27699a83.png)

**Comment by KJNC** [comment]
Hi atoftegaard,

Thank you for contacting us regarding this.

I have tested the theme with the configuration you showed me.
It seems your issues are with the configuration of the SelectWoo instance in your javascript.

Please have a look at the [select2 documentation](https://select2.org/data-sources/ajax) to see the correct configuration for an ajax solution with pagination. Remember to use a datasource with more than 2 results when using pagination. Also, for the search to work when using pagination, remember to provide the search term with the ajax call.

Hope this helps.

Best regards,
Kristina Jensen
Det Fælles Designsystem
