### ISSUE TITLE
Eksterne links i en footer - med eller uden ikon?

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#60]
Hej,
Når der linkes til eksterne sider/links, andvender vi dette ikon: 
![image](https://user-images.githubusercontent.com/48348000/64589813-5411df00-d3a6-11e9-9028-2c22583740f2.png)

Men hvad med eksterne links i en footer -skal vi have ikonet på hvert eneste link (Alle vores sider ligger eksternt - enten på borger.dk / virk.dk)?
https://designsystem.dk/komponenter/footers/

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Vi har oprettet sagen, og vil vende tilbage.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Tak for spørgsmålet.

Ja i bør indikere over for brugeren, at det er et eksternt link også selvom i har flere. Forlader brugeren løsningen, hvis der trykkes på linket, bør i også advare brugeren, så denne ikke forlader selvbetjeningsløsningen ved en fejl. 

Jeg opretter en sag på det, så vi får det vist i footer-eksemplerne. 

Mvh
Sune
Det Fælles Designsystem
