### ISSUE TITLE
Print af alm. tabel vs. visning af tabel på mobileenheder

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#61]
Hej dfs,
Mange af vores løsninger med tabeller kræver at blive udskrevet pænt for at kunne fx. bruges som dokumentation til arbejdsgiver og offentlige myndigheder. 

Vi bruger ofte classen: "table--responsive-headers" for at give brugeren en bedre oplevelse på de små skærme- og vi bruger classen sammen med de andre classer fx. dataTable table--zebra table--compact.

Problem opstår, når tabellen skal udskrives, så vil vi ikke have at den mobile visning (table--responsive-headers) bliver udskrevet. Men det man kan se på den store skærm, skal udskrives.

Har en løsning til ovenstående problem? :-)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana,

Det har vi. Se under Responsiv tabel på siden https://designsystem.dk/design/print/.

Ved at tilføje klassen `d-print-table` på tabellen, fortæller man, at den gerne må ligne en tabel ved print.

Denne løsning er dog ikke testet sammen med Datatables, da de generelt overskriver alt alligevel. Sig endelig til, hvis I oplever udfordringer med den blanding.

Jeg lukker sagen her - du er dog som altid velkommen til at åbne den igen, hvis du har flere spørgsmål.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by FNA-atp** [comment]
Super - tusind tak for hjælpen :)

ha' en god aften :-)
