### ISSUE TITLE
Brødkrummesti

### ISSUE THREAD

**Issue by TinaLinneOlsen** [detfaellesdesignsystem/dkfds-components#62]
Hej FDS, 

Jeg er ved at lave en selvbetjeningløsning som er lidt mere avanceret end flere af de eksempler i har, som primært mest er formularer. I den her selvbetjeningløsning skal man have en oversigt over de sager man har, hvorfra man skal kunne navigere til en detaljeside for en enkelt sag, og herfra skal man gå ind på yderligere sider med detaljer på sagen. Jeg har indsat nedenstående billeder for at prøve at illustrere forløbet. 

Sagsoversigt (1. led): Brugeren vises en oversigt deres sager, hvor de kan vælge den sag de vil se detaljer for. 
![image](https://user-images.githubusercontent.com/49032957/64859759-681a4280-d62b-11e9-8a32-aa9e69b90ee5.png)

Sagsindhold (2. led): Brugeren kan se oversigt over detaljer for en konkret sag.
![image](https://user-images.githubusercontent.com/49032957/64860237-d6abd000-d62c-11e9-8652-9077cb3734d9.png)

Sagsdetalje (3. led): Brugeren kan se konkrete detaljer på en sag.
![image](https://user-images.githubusercontent.com/49032957/64859987-0ad2c100-d62c-11e9-8bc5-c5478025a1e5.png)

Så vidt jeg kan se er der i FDS ingen anbefaling om at benytte brødkrummesti, men i ovenstående eksempel er der brug for at brugeren kan navigere tilbage til de forskellige led på en overskuelig måde. Vil det være okay at bruge brødkrummesti, eller har i en anden anbefaling? 

På mobil vil det ved brødkrummesti jo så blive noget i nedenstående stil.
![image](https://user-images.githubusercontent.com/49032957/64860207-bc71f200-d62c-11e9-973b-996cbe3099ff.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @TinaLinneOlsen 

Jeg opretter det i backloggen. Det skal dog vendes med borger.dk og Virk da hverken HTML-guiden eller Virks Designmanual rummede brødkrummer med overlæg, da selvbetjeningsløsninger ideelt set er trinbasserede og derfor bør gøre brug af tringuides. Jeg tager dit eksempel med videre.

Mvh
Sune 
Det Fælles Designsystem

**Comment by TinaLinneOlsen** [comment]
Hej Sune,

Tak for det. Det skal ikke nødvendigvis være en brødkrummesti, men fordi den her selvbetjeningsløsning ikke er ét flow man kan dele op i trin, så er der brug for noget som giver brugeren mulighed for at navigere frem og tilbage på en overskuelig måde (specielt på mobilen). På hver sag vil der desuden også løbende være spørgeskemaer som brugeren skal svare på, og her skal der selvfølgelig gøres brug af trinindikator. Den her selvbetjeningen skal bruges som et "univers", hvor brugeren indsender nødvendige oplysninger, men samtidigt også kan orienterer sig i fremgang, afgørelser, dokumenter og involverede parter i deres sag (og nogen gange flere sager).    

Jeg kan også komme ind til jer en dag, hvis vi skal prøve at gennemgå, hvilke behov den her selvbetjening har.

**Comment by detfaellesdesignsystem** [comment]
Hej Tina @TinaLinneOlsen 

Denne er endnu ikke afklaret af portalerne.

Men komponenten og retningslinjer findes på GDS: https://design-system.service.gov.uk/components/breadcrumbs/ og skulle komponenten blive godkendt til optagelse i FDS følger vi denne.

Jeg håber at i kan komme godt videre og beklager at det ikke altid går så hurtigt.

Mvh
Sune
FDS

**Comment by detfaellesdesignsystem** [comment]
Brødkrumme komponent er tilgængelig fra version 6.1.0
