### ISSUE TITLE
alternativ for modal og accordions?

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#63]
Hej dfs,
Vi er i gang med at implementere en "ferieplanlægger" selvbetjeningløsning. 

Vi har brug for at vise noget information på siden, samtidig med at brugeren skal forholde sig til beregningerne på siden - og vi er kommet frem til nedenstående løsning, hvor sidens indhold skubbes ned (se billedet). 

Har I et bedre forslag til nedenstående løsning, eller er det okay? Vi synes ikke "accordions" passer ind i løsningen, da den vil blive for kompakt.

![image](https://user-images.githubusercontent.com/54143827/64861706-ee855300-d630-11e9-9379-2361b9b7d6e2.png)
![image](https://user-images.githubusercontent.com/54143827/64862059-e11c9880-d631-11e9-9d1a-1df113f7fa95.png)

mvh. 
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
@JAU-atp 

Tak for spørgsmålet.

Det du efterspørger er den komponent som i GDS hedder "Details" 
https://design-system.service.gov.uk/components/details/

Jeg opretter "detalje" komponenten i backloggen. I mellemtiden bør i følge anvisningerne fra GDS, da det er den vi i så fald vil lade os inspirere af.

Mvh
Sune
Det Fælles Designsystem

**Comment by JAU-atp** [comment]
Hej Sune
Tak for svar, vi vil gøre brug af detaljekomponenten.
Når I kommer dertil og selv kigger på en ligene komponent, vil I så tænke en mulighed for luk-knap (i bunden) med ind i løsningen til mobile enheder?

Venlig hilsen
Josephine Frederikke August Nielsen
[Adobe Systems]
Udvikler  ·  Frontend
IT  ·  Allerød
Direkte nummer xx
E-mail jau@atp.dk<mailto:jau@atp.dk>

Besøgsadresse  ·  Sortemosevej 2 · 3450 Allerød
Postadresse  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP Koncernen på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem <notifications@github.com>
Sendt: 19. september 2019 22:18
Til: detfaellesdesignsystem/dkfds-components <dkfds-components@noreply.github.com>
Cc: Josephine August Nielsen - JAU <JAU@atp.dk>; Mention <mention@noreply.github.com>
Emne: Re: [detfaellesdesignsystem/dkfds-components] alternativ for modal og accordions? (#63)


@JAU-atp<https://github.com/JAU-atp>

Tak for spørgsmålet.

Det du efterspørger er den komponent som i GDS hedder "Details"
https://design-system.service.gov.uk/components/details/

Jeg opretter "detalje" komponenten i backloggen. I mellemtiden bør i følge anvisningerne fra GDS, da det er den vi i så fald vil lade os inspirere af.

Mvh
Sune
Det Fælles Designsystem
