### ISSUE TITLE
stor tekst + sortering brugt i tabel

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#64]
Hej fds,
Vi har gjort brug af jeres display tekst for at fremhæve resultatet af et resterende antal feriedage, som brugeren har tilbage.
Vi vil gerne høre jer ad, om vi må bruge den i en tabel? 

Ydermere har vi lavet en sorteringfunktion til en kolonne, da vi har ikke brugt "Datatable" (se nedestående billede). Er vores løsning til sortering god nok?

![image](https://user-images.githubusercontent.com/54143827/64862420-bed74a80-d632-11e9-9368-4728d7d3ca13.png)

![image](https://user-images.githubusercontent.com/54143827/64862681-6d7b8b00-d633-11e9-9266-65a7a68e0dfc.png)

mvh. 
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 

Tak for spørgsmålet. 
I må gerne bruge "stor tekst" til resultatet som i har gjort. 
I skal anvende sorteringsikonet fra material design til sortering, så der er konsistens i dette på tværs af alle selvbetjeningsløsninger.
![image](https://user-images.githubusercontent.com/44367338/65277206-b34fbc00-db29-11e9-8c35-a49bc3b44624.png)
således at det ikke ligner et menu/dropdown ikon
![image](https://user-images.githubusercontent.com/44367338/65277241-c498c880-db29-11e9-98c7-db4f90fa1632.png)

Mvh
Sune
Det Fælles Designsystem
