### ISSUE TITLE
Pop-up besked

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#65]
Hej fds,
På "ferieplanlæggeren" har vi enkelte tilfælde, hvor at brugeren skal gøres opmærksom på nogle oplysninger, ligeså snart der regnes på feriedage. 
Vi har løst det ved at der vises en pop-up (alert besked styling) under rækken. Der kan opstå situationer, hvor det bliver nødvendigt at vise en pop-up for hver række i tabellen.  - (se billedet herunder)

hvordan løser vi dette bedst muligt?

![image](https://user-images.githubusercontent.com/54143827/64863735-dbc14d00-d635-11e9-9263-e2abd829ab50.png)

mvh. 
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 

Jeg opretter dit spørgsmål i backloggen, så undersøger vi nogle muligheder. 

Mvh
Sune
Det Fælles Designsystem

**Comment by JAU-atp** [comment]
Hej Sune,
Tak for svar. Vi har en deadline som hedder d. 01/10-19 så det ville være rart at kende til mulighederne inden der. Ellers må vi imellem tiden gå med overstående forslag 😊

Venlig hilsen
Josephine Frederikke August Nielsen
[cid:image002.png@01D5721E.8A9B5A40]
Udvikler  ·  Frontend
IT  ·  Allerød
Direkte nummer xx
E-mail jau@atp.dk<mailto:jau@atp.dk>

Besøgsadresse  ·  Sortemosevej 2 · 3450 Allerød
Postadresse  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP Koncernen på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem <notifications@github.com>
Sendt: 19. september 2019 22:02
Til: detfaellesdesignsystem/dkfds-components <dkfds-components@noreply.github.com>
Cc: Josephine August Nielsen - JAU <JAU@atp.dk>; Mention <mention@noreply.github.com>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Pop-up besked (#65)


Hej @JAU-atp<https://github.com/JAU-atp>

Jeg opretter dit spørgsmål i backloggen, så undersøger vi nogle muligheder.

Mvh
Sune
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej JAU-atp

Beklager det meget sene svar. Det hjælper jer nok ikke meget i forbindelse med den nævnte release, men ikke desto mindre har vi overvejet en løsning, som I kan bruge, hvis I skulle løbe ind i lignende udfordringer.

Vi anbefaler ikke at bruge komponenten Beskeder i dette tilfælde, da disse ikke placeres løbende på siden men derimod altid øverst til generel information. I tilfælde af, at flere tabelrækker leder til informationen vil det formentlig også blive uoverskueligt med så mange lange tekster på siden på én gang. 

Vi vil derfor i stedet anbefale en mere kompakt variant med brug af et funktionslink, der åbner en modal med mere information. Det vil se nogenlunde sådan ud:

![Screenshot 2021-11-30 at 17 05 33](https://user-images.githubusercontent.com/44367338/144083479-2790f4b3-0729-4f08-a8be-dbbe3f92e1c8.png)

Og med åben modal:

![Screenshot 2021-11-30 at 17 05 42](https://user-images.githubusercontent.com/44367338/144083509-2a92c79a-b6e4-4b18-a56a-823b70169ae5.png)

Jeg lukker tråden, da den er så gammel, men åbn den gerne igen, hvis I har spørgsmål eller kommentarer.

Med venlig hilsen
Mette Boldt
Det Fælles Designsystem
