### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#66]
Hej fds,
Vi kan ikke finde dokumentation for, hvordan vi skal gøre brugeren opmærksom på, om et inputfelt er required. 
I alle vores løsninger gør vi brug af en rød * i required fields, (som billedet nedenunder illustrerer) da vi går ud fra, at dette er korrekt?

![image](https://user-images.githubusercontent.com/54143827/65045209-b0ed3680-d95e-11e9-8668-6096aebcde8b.png)

mvh.
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp der er sket et paradigmeskifte i forhold til den røde asterisk. Da langt hovedparten af felter i langt de fleste selvbetjeningsløsninger er obligatoriske bliver den røde stjerne overkommunikerende, hvorfor vi nu skriver (frivilligt) ud for de felter som ikke er obligatoriske. 
![image](https://user-images.githubusercontent.com/44367338/65128187-4806cc80-d9f9-11e9-8443-83e64bb1c4d3.png)
https://designsystem.dk/komponenter/form-controls/ 
Dette gør vi i tråd med det som Gov.uk og USWDS anbefaler:
https://govuk-elements.herokuapp.com/form-elements/#form-optional-fields
https://designsystem.digital.gov/components/form-templates/

Mvh
Sune
Det Fælles Designsystem
