### ISSUE TITLE
Modal: Print fra mobil fejler 

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#67]
Hej dk-fds,
Der udskrives en blank side fra mobile-enheder (testet på iphones), når "Modal-active" er sat på <body>.
Det kan testes her: https://designsystem.dk/pages/eksempler/aktindsigt/aktindsigt-1/ 
![image](https://user-images.githubusercontent.com/48348000/65307210-98139980-db87-11e9-81d1-fc0e6c36594e.png)

Mvh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp 

Jeg har oprettet fejlen i backloggen. Vi vender tilbage snarest.

Mvh
Sune
FDS

**Comment by clpatp** [comment]
Er der noget nyt vedrørende denne? Vi har en del henvendelser omkring print der ikke virker for modaler. Og det skal bruges til dokumentation ifht fagforeninger/a-kasser.

**Comment by detfaellesdesignsystem** [comment]
Hej @clpatp,

Denne ligger fortsat i backlog. Jeg giver lige besked, når den er med i et sprint.

Dette issue gælder dog kun print fra iPhone, så hvis du oplever problemer på andre enheder, må du meget gerne lige sige til.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by clpatp** [comment]
Hej

Tak - og vi skal nok give besked hvis vi oplever problemer på andre enheder også.

**Comment by detfaellesdesignsystem** [comment]
Hej igen,

Det har endelig lykkedes mig at finde en måde at teste dette på. Vil forsøge at få den prioriteret i næste sprint.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by clpatp** [comment]
Fedt - tak!

**Comment by detfaellesdesignsystem** [comment]
Hej @clpatp,

Fejlen er fikset, og vil være med i næste release. Regner med at næste release kommer ud en af de nærmeste dage.

Jeg lukker derfor sagen her. Du er dog velkommen til at åbne den igen, hvis du finder, at der fortsat er problemer.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
