### ISSUE TITLE
Modal virker ikke når den benyttes i en Angular komponent

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#68]
Jeg har forsøgt med FDS modal som en del af en Angular komponent. Den renderer ok, men funktionaliteten ved klik på knapper virker ikke. Jeg har benyttet funktionaliteten fra https://designsystem.dk/komponenter/ i uændret form.

Det virker uden problemer så snart jeg flytter html'en udenfor <app-root></app-root> i min applikations index.html så både (s)css og js er inkluderet korrekt.

Any thoughts?

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Vi har et udestående med javascript i DKFDS, hvor alle events bliver sat ved pageload. Så det er et timing issue du har, hvor javascript bliver loaded før HTMLen for din komponent eksisterer. 

Vi har løst det i næste release, hvor du har adgang til dkfds javascript funktioner og dermed kan initiere nye komponenter der gør brug af javascript efter pageload.

Men indtil næste release kommer ud, er du desværre nødt til selv at håndtere javascript for de komponenter, der bliver tilføjet efter pageload.

Modal komponenten er bygget med micromodal.js, som er et tredjeparts bibliotek. Du kan hente det ind, og selv initiere modalen i javascript.

Se hvordan vi har brugt Micromodal i DKFDS:
https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/src/js/components/modal.js

Micromodal.js (Den findes også på npm):
https://github.com/detfaellesdesignsystem/dkfds-components/blob/master/src/vendor/micromodal.js

Du må endelig lige sige til, hvis du har spørgsmål til ovenstående. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
> Vi har løst det i næste release...

Som kommer hvornår?

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Nuværende sprint slutter onsdag i næste uge, så umiddelbart derefter regner vi med at lave release 5.0.0.

Jeg kan dog afsløre at [micromodal.js](https://micromodal.now.sh/) bliver trukket ud af kernen da det er et tredjeparts bibliotek og derfor bliver lagt ind som en [udvidelse](https://designsystem.dk/udvidelser/) i stedet. Der vil være et tema til det, så det matcher designsystemets design. 

Vi har dog i backloggen, at vi skal have modalvinduer ind i kernen, som ikke er afhængig af tredjepart. Hvornår dette sker ved jeg dog ikke på nuværende tidspunkt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Version 5.0.0 ligger nu klar, men bemærk at modal komponenten er pillet ud af kernen. Man skal derfor hente [micromodal.js](https://micromodal.now.sh/) ind i sit projekt selv. Vi leverer dog et tema til micromodals, som du kan læse mere om her https://designsystem.dk/udvidelser/micromodal/

Jeg lukker sagen her, men du er velkommen til at genåbne eller oprette en ny sag.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
