### ISSUE TITLE
Trinindikator

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#69]
Hej FDS

Vi er igang med at opgradere en selvbetjeningløsning på Virk, og vi er blevet i tvivl om, hvornår vi skal benytte os af en låst eller interaktiv trinindikator?
Ydermere har vi undret os over de mange forskellige trinindikatorer, der er at vælge imellem, og hvornår vi bør gøre brug af de forskellige?

Billedet nedenfor illustrerer løsningen, som vi er igang med at opgradere. Vi forventer at der kommer til at være 11 trins i alt. Dog vil mængden af trins variere alt efter brugerens forud valgte steps. Har I en holdning til, hvordan vi bedst repræsenterer trinindikatoren i sådan et tilfælde? Vi tænker selv følgende valgmuligheder:
1) Alle 11 trins er repræsenteret, hvoraf nogle af dem er disabled (og løbende bliver enabled hvis brugeren opfylder betingelserne).
2) Der bliver automatisk tilføjet nye trins i trinindikatoren, hvis brugeren opfylder betingelserne.

![image](https://user-images.githubusercontent.com/54143827/65885421-ecdebd80-e39a-11e9-8dba-fb74531c51c6.png)

På forhånd tak for hjælpen.
Mvh. 
Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 

Som altid kommer jeg lige med en lille disclaimer: jeg kender ikke Jeres brugeres behov, Jeres forretning eller de rammer inden for hvilke i har fået til opgave at løse udfordringen, derfor kan jeg kun svare på spørgsmålet på en overordnet og generisk måde, og mit svar skal tages som sådan. Mit svar godkender eller afviser heller ingenting, den endelige godkendelse ligger i Virk regi, da de tjekker løsningen igennem i forhold til alle de fælles krav og ikke kun i forhold til dette 13. og sidste krav (som er FDS). Med det sagt, så skal jeg gerne give mit besyv med om trinindikatorer : )

Hvilken type trinindikator i skal bruge afhænger af hvilken form for interaktion i vil tillade brugeren i trinindikatoren. I skal låse trinene hvis det er nødvendigt for brugeren at afslutte trinene fortløbende rækkefølge. I nogle løsninger kan brugeren udfylde i vilkårlig rækkefølge, hvorfor trinene ikke er låst i disse. Det kommer helt an på jeres behov.

I forhold til Jeres undring, så skal I skal bruge den trinindikator, der løser Jeres brugeres behov. De mange variationer er opstået, da i som myndigheder (og af og til inden for selv samme myndighed) har mange forskellige behov på Jeres brugeres vegne. Jeg ville hellere end gerne simplificere trinindikatorer-afsnittet og fx følge govUKs anvisninger vedr. tringuides (som set her under afsnittet "Using progress indicators" https://design-system.service.gov.uk/patterns/question-pages/), men det mandat har FDS ikke, derfor er der mange valgmuligheder, når det kommer til trinindikatorer. Jeg vil anbefale Jer at i brugertester Jer frem til den bedste trinindikator for Jeres brugere. 

Jeg har før set den model for trinindikator du opridser, men jeg har det personligt svært på brugernes vegne med trinindikatorer, der varierer i antallet af trin, da pointen med en trinindikator vel netop er at vise brugeren, hvad denne skal igennem. Jeg er ikke overbevist om at varierende trinindikatorer er en god ide - ligesom fx trinindikatorer med skjulte trin i min bog er et slags (mildt) "dark pattern". Når man ikke kan vise brugeren, hvilke trin denne præcist skal igennem, kan det muligvis være at den bedste løsning, er at lade være med at have en trinindikator, eller alternativt en overflow trinindikator, der "forstyrrer" minimalt. Jeg ville, hvis jeg var Jer, vælge at brugerteste om brugerne bruger en varierende trinindikator til noget, om de forstår den, eller om de evt. ville være bedre stillet uden og derfra udlede hvilken form for trinindikator, der evt. stiller brugeren bedst - gør denne mest effektiv, mindst forvirret. Nærmere kan jeg vidst ikke komme det. 

Hvis i brugertester forskellige trinindikatorer og slet ingen, er jeg meget interesseret i at høre hvad i kommer frem til.

Jeg håber at mit svar, hvor uspecifikt det end er, kan hjælpe Jer videre.

Mvh
Sune
FDS
