### ISSUE TITLE
Tooltip på svg virker ikke i IE11

### ISSUE THREAD

**Issue by christianlandbo** [detfaellesdesignsystem/dkfds-components#7]
`<svg class="icon-svg js-tooltip" data-tippy-placement="right" data-tippy="" data-original-title="Tooltip hjælpetekst"><use href="#help-circle-outline"></use></svg>`

Giver javascriptfejlen: Object doesn't support property or method 'contains'

i IE11.

Det er denne fejl: https://github.com/FezVrasta/popper.js/issues/515

Fikset med polyfill fungerer. 

I kunne overveje om det skulle bages ind i DFS.

**Comment by detfaellesdesignsystem** [comment]
Hej @christianlandbo,

Tak for din henvendelse og løsningsforslag.

Vi anbefaler, at man sætter tooltip på et a element, således at tooltip kan oplæses af en skærmlæser og derved opfylder tilgængelighedskrav. Du kan se vores eksempel på følgende side: [https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tooltip/](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/tooltip/)

Hvis du følger eksemplet bør du ikke opleve problemer.

Med venlig hilsen
Kristina Jensen
Det fælles Designsystem

**Comment by christianlandbo** [comment]
Smukt! Tak :-)
