### ISSUE TITLE
Mangler en beskrivelse af events på jeres Accordion komponent

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#70]
Jeg savner en beskrivelse af de events der MÅ være på jeres accordion komponent. Hvordan fanger jeg at en sektion lukkes og en anden åbnes?

Er komponenten baseret på (yet another) standard jQuery plugin? I givet fald hvilken?

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Der er pt. ingen events på accordions, som du kan koble dig på. Dette er dog lavet i næste release, hvor der ligeledes vil være en beskrivelse af disse events ved hver komponent, hvor det er relevant.

Vi har ikke jQuery i dkfds. Kun ved tredjeparts biblioteker i udvidelser kan man risikere, at der gøres brug af jQuery. Accordion komponenten er dog er skrevet fra bunden med plain js, så vi ikke er afhængige af tredjeparts biblioteker i kernen af dkfds.

Vi arbejder hårdt på at få næste release (5.0.0) ud forhåbentlig i denne uge og senest i næste uge.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Det er nu mulighed med version 5.0.0 at koble sig på fds.accordion.open og fds.accordion.close events, som bliver triggered på accordion knappen.

Hvis du har brug for flere/andre events, så er du mere end velkommen til at oprette en ny sag med beskrivelse heraf.

Jeg lukker denne sag her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
