### ISSUE TITLE
Skal "Kvittering" vises som trin i trinindikatoren?

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#71]
Hej dk-fds,
Skal man vise eller ikke vise "Kvittering" i trinindikatoren? se nedenstående billede :-)

![image](https://user-images.githubusercontent.com/48348000/66459622-b3cadb00-ea75-11e9-9859-c9a58dfc211b.png)

Vh.
Farzana

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana (@FNA-atp) 
Kvittering skal ikke vises i tringuiden, da brugeren, når denne får kvitteringen, som sådan ikke er i indberetningen længere. 
Mvh
Sune
FDS

**Comment by FNA-atp** [comment]
Hej Sune,
I skriver her: https://designsystem.dk/komponenter/trinindikatorer/ at "Kvittering" burde være det sidste trin i trinindikatoren. Er det noget nyt, I er kommet frem til? :-)

![image](https://user-images.githubusercontent.com/48348000/70794778-beb82980-1d9e-11ea-8bb2-685e14256fae.png)

**Comment by detfaellesdesignsystem** [comment]
Hej Farzana @FNA-atp 

Tak fordi du melder det ind. Det er en fejl. Der skal stå "Sidste trin skal være en opsummeringsside" og "Når indberetningen er afsluttet skal brugeren have en kvittering".

Mvh
Sune
FDS
