### ISSUE TITLE
Problemer med standard komponenter i en Angular-CLI app

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#72]
Hej FDS

Jeg er nu rendt ind i den tredje komponent jeg ikke kan få til at virke i Angular... jeg har importeret både css og js som beskrevet på https://designsystem.dk/komigang/tiludviklere/eksempler-implementering.

Det jeg oplever er, at tooltip, overflow menu og modal vinduer IKKE virker i mine Angular komponenter. Så snart jeg placerer dem udenfor min root komponent virker de fint. Hvis jeg fx i min index.html kopierer jeres kode til tooltip knappen og indsætter den her:

```
  <div id="page-content">
    <app-root></app-root>

    <html til tooltip knap...>

  </div>
```

så virker det fint, men så snart jeg sætter det ind et eller andet sted i en af mine komponenter, så får jeg kun vist min title attribut på den måde browseren definerer.

Any thoughts?

Er det en race condition igen? Hvornår kommer I med den næste version?

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Alt js i tidligere versioner bliver kørt ved dom ready. Angular køres ligeledes ved dom ready på den første side. Så det er et timingspørgsmål. Elementerne på din side eksisterer simpelthen ikke når dkfds js bliver kørt.

Jeg sidder lige nu og gør release 5.0.0 klar til at komme ud senere i dag. I morgen burde du have de værktøj der skal til for at initere dkfds js på rette tidspunkt i dit projekt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Jeg er desværre nødt til at melde at jeg udsætter release til på mandag. 
Har lige nogle udeståender med Internet Explorer der skal fikses først. :)

God weekend

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
Argh... det tror jeg min F5 bliver glad for at høre :-)

God weekend til dig også :-)

**Comment by detfaellesdesignsystem** [comment]
Hej cjessing,

Så ligger der en version 5.0.0 klar til dig.

Beklager ventetiden. :)

Jeg lukker sagen her - du er dog selvfølgelig velkommen til at genåbne den eller oprette en ny.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
