### ISSUE TITLE
JavaScript ændringer i version 5.0.0

### ISSUE THREAD

**Issue by detfaellesdesignsystem** [detfaellesdesignsystem/dkfds-components#74]
Der er sket en del JavaScript ændringer i version 5.0.0.

- JavaScript i dkfds skal nu initieres i projektet med funktionen `DKFDS.init();`
Funktionen håndterer alle komponenter, hvor javascript er relevant.
Man kan køre funktionen ved pageload eller hvor nu passer bedst i den opsætning man har i projektet.
Dette løser timingudfordringen, som flere projekter har lidt under - herunder særligt de projekter, der kører Angular.
- Man kan initere komponenter enkeltvis med bestemte klasser. Et eksempel er `new DKFDS.Accordion(document.getElementByID('myNewAccordion));`
For mere info, se under implementeringsafsnittet på komponenterne på [https://designsystem.dk/komponenter/](https://designsystem.dk/komponenter/).

For  mere info om implementering af DKFDS se [https://designsystem.dk/komigang/tiludviklere/](https://designsystem.dk/komigang/tiludviklere/).

Hvis du har spørgsmål til ændringen, så er du velkommen til at stille dem i denne tråd eller oprette et nyt issue på Github.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
Jeg har stadig problemer med timingen...

Hvis jeg indsætter følgende i min Angular app's index.html:

```
<body>
  ...
<script>
    document.addEventListener('DOMContentLoaded', () => {
        console.log('DKFDS Initialized', DKFDS);
        DKFDS.init();
    });
</script>
</body>
```
så får jeg fint kaldt DKFDS.init() men **INDEN** Angular er initialiseret.

Den eneste måde jeg kan få det til at virke på er ved at kalde DKFDS.init() vha jQuery i min app.component.ts:

```
  ngOnInit() {
    $(() => {
      console.log('DKFDS Initialized', DKFDS);
      DKFDS.init();
    });
   }
```

Det er i sagens natur ikke en holdbar løsning, at det er nødvendigt at have jQuery inkluderet i sit Angular projekt, blot for at kunne initialisere DKFDS. Jeg har også forsøgt mig med ngAfterViewInit() uden held.

_**Derfor:** Hvor anbefaler I at man indsætter kaldet til DKFDS.init() i en ren Angular applikation?_

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for din henvendelse :)

I testen, der blev udført før release, fungerede det fint, hvis man kaldte `DKFDS.init()` i `ngOnInit` - uden brug af jQuery - både på component og app niveau.

Testen blev udført i en tilpasset version af Angulars Tour of Heros eksempelprojekt.

DKFDS.init() kører events på alle komponenter, som gør brug af javascript i FDS. Det er en form for "Do everything" funktion. Alt efter, hvordan ens projekt er bygget op, så kan det være relevant at gøre brug af de enkelte komponenters classes til initiering af deres javascript, hvis man har timing udfordringer (som ofte opstår i angular). Alternativt kan man køre DKFDS.init() af flere omgange - men det er næppe performance-mæssigt anbefalet.

Vi er på ingen måde Angular eksperter, så jeg kan ikke sige dig, hvad løsningen er på din udfordring, da det også afhænger af projektopbygningen.

Eksemplet med plain js, som vi viser på siden https://designsystem.dk/komigang/tiludviklere/, er som beskrevet et eksempel, og at man kan køre DKFDS.init() "ved dom ready, eller hvornår det nu end passer i dit projekt."

Hvis du finder en god best practice løsning, så må du meget gerne melde tilbage. Det kan være eksemplet på implementering af DKFDS i angular i så fald kan opdateres på designsystem.dk :)

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
Er du så ikke rar at fotælle mig hvad jeg gør galt i den her Stackblitz:

https://stackblitz.com/edit/angular-ubsvkt
