### ISSUE TITLE
Pil hopper ved :hover i navigation

### ISSUE THREAD

**Issue by hjemmesidekongen** [detfaellesdesignsystem/dkfds-components#75]
Fejl kan ses på https://designsystem.dk/components/headers/full/. 

**Fejlen genskabes således:**
1. gå til følgende URL: https://designsystem.dk/components/headers/full/.
2. Fjern CSS klassen "current" på `<button>` på "Femte menupunkt"
3. Pil hopper nu ved :hover.

Jeg formoder at `.current` kun skal være tilføjet hvis én af menupunkterne i dropdownen er aktive således at "Femte menupunkt" vil være i active-trail.

Fejlen sker formentlig når der bliver tilføjet en border-bottom ved :hover.

**Comment by detfaellesdesignsystem** [comment]
Hej @hjemmesidekongen ,

Tak for henvendelsen!

Vi har oprettet fejlen i backloggen. 

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @hjemmesidekongen ,

Vi har fikset fejlen, og den vil komme med i næste release om en 2 ugers tid.

Jeg lukker derfor sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
