### ISSUE TITLE
Luk virker ikke i alerts

### ISSUE THREAD

**Issue by hjemmesidekongen** [detfaellesdesignsystem/dkfds-components#76]
**Sådan genskabes fejlen:**
1. Gå til https://designsystem.dk/komponenter/beskeder/
2. Gå til sektionen "Beskeder med lukknap"
3. Klik på "Luk" i én af de viste alert.

Er testet på 5.0.0 releaset lokalt og i dokumentationen.

**Forventet:** 
At alerten lukker ved klik på knappen.

**Comment by detfaellesdesignsystem** [comment]
Hej @hjemmesidekongen,

Tak for din henvendelse.

DKFDS leverer på nuværende tidspunkt ikke funktionaliteten til luk knappen i en besked (Alert). Det er udelukkende styling og HTML.

Jeg har oprettet en sag i vores backlog, om at det er et ønske, at funktionalitet bliver leveret med.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Ovenstående funktionalitet kommer med i den kommende v8.0.0

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
