### ISSUE TITLE
Sorterring i tabeller

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#77]
Hej FDS,

Vi er igang med at opgradere et af vores projekter, som indeholder en tabel over indberetningsfejl. Vi har brug for sorterring på tabellen, og vi lader os derfor inspirere af datatabels, som I henviser til på jeres side under avanceret tabeller (se nedestående billede).
![image](https://user-images.githubusercontent.com/54143827/67389855-c1b34c80-f59b-11e9-840f-d1fc159d4a86.png)
Vi er dog i tvivl om, hvordan det skal se ud på mobile enheder. På vores nuværende løsning har vi en dropdown, der indeholder de forskellige sorterringsmuligheder (se nedestående billede).

![image](https://user-images.githubusercontent.com/54143827/67389871-c841c400-f59b-11e9-8080-659739c8693e.png)

Er dette en godkendt løsning eller har i nogle andre forslag til, hvordan vi skal bære os ad med dette?

Mvh. Josephine fra ATP

**Comment by JAU-atp** [comment]
Er der en status på dette?

mvh. Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Jeg har oprettet en sag på den og lagt den i næste sprint. Forhåbentlig vil en af vores UX'ere kunne nå at kigge på den.

Vi vender lige tilbage. Beklager ventetiden.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 
Beklager at det har taget så længe at få svaret. Jeg har nu undersøgt om vi kunne sige noget fornuftigt om det mønster, men pt har vi ikke fundet en best practise og der er ikke nogen fast konvention for det. Vi har oprettet en sag på at kigge på filtrering og sortering på mobil. 
Som altid kigger vi til govUK, https://www.gov.uk/search/all?keywords=taxes&order=relevance, der også gør brug af en drop down, så i kører bare, så håber jeg vi en dag kan komme med gode eksempler på filtrering og sortering. 
Mvh
Sune
FDS

**Comment by JAU-atp** [comment]
Det lyder rigtig godt, tak for hjælpen :)
mvh. Josephine
