### ISSUE TITLE
Overflow menu virker ikke i Angular :-(

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#78]
Indsætter man jeres eksempelkode for en overflow menu i en Angular component virker den ikke. Flytter man den udenfor <app-root> virker den fint...

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for din henvendelse.

Kører du `DKFDS.init()` når din component vises? eller initierer `new DKFDS.Dropdown(document.getElementByID('OVERFLOW-BUTTON-ID'));` på den pågældende overflow menu, når den først er tilstedet i DOM?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
Okay det virker hvis jeg i min app.component.ts kalder init vha jQuery:

    $(() => {
      DKFDS.init();
    });

Men ikke hvis jeg bare indsætter 

    document.addEventListener('DOMContentLoaded', () => {
      DKFDS.init();
    });
