### ISSUE TITLE
Multiselect til singleselect

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#79]
Hej FDS
Vi har nogle projekter, hvor at brugeren skal have mulighed for at vælge ét land i en dropdown.

Vi vil gerne gøre bug af funktionaliteten fra select2 (med mulighed for at søge på en værdi), som i henviser til på jeres side:
https://designsystem.dk/udvidelser/selectwoo-multiselect/

Dog er vi kun interesseret i at brugeren skal vælge en enkelt værdi, og vi har derfor sat multiselect til at være false, og stylet formen så den passer nogenlunde til jeres design (se billederne nedenfor).
(closed)
![image](https://user-images.githubusercontent.com/54143827/67764309-f61a8300-fa49-11e9-9e8a-c75291dc1d70.png)
(open)
![image](https://user-images.githubusercontent.com/54143827/67764319-fdda2780-fa49-11e9-95b4-248e6825979d.png)

Har i mulighed for at lægge stylingen til en singleselect ind i jeres stylesheet?

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Tak for din henvendelse.

Jeg har oprettet en sag på det i backloggen, men jeg kan ikke lige på nuværende tidspunkt sige, hvornår det kan kommet med i et sprint.

Jeg opdaterer sagen her, når der er nyt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by JAU-atp** [comment]
Tak for det
mvh. Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Som du ved fra sidste samarbejdsforum fjerner vi support af plugins fra FDS' side, og vil derfor ikke komme med flere opdateringer til dkfds-plugins.

Det betyder dog ikke, at I ikke fortsat kan gøre brug af plugins - blot at I selv står for at vedligeholde dem. Det vil derfor også gælde i dette tilfælde.

Jeg lukker derfor denne sag.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
