### ISSUE TITLE
Read-only input felt

### ISSUE THREAD

**Issue by postergaard** [detfaellesdesignsystem/dkfds-components#8]
[Brug denne type issues, når der ikke er tale om fejl, men om opdateringer og forbedringer af eksisterende kode/beskrivelser/eksempelvisninger. (Use this issue type for updates and improvements to the code/descriptions/examples that are not bugs.)] 

**Navn i designsystemet (Feature name in the design system)**
Formular-elementer --> Felter

**Link til det der skal opdateres (URL to what needs to be updated)**
https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Vi har brug for at kunne sende en værdi fra input feltet med i en formular, men uden brugeren kan ændre det. Fx: CPR nummer

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Er det muligt at udvide input felterne med et read-only inputfelt. Muligvis stylet som disable

**Beskriv de alternativer du har overvejet. (Describe alternatives you've considered)**
At style det til at ligne disablet. Eller at kunne tilføje en class der fjerne focus elementet (Firkanten rundt om)

**Supplerende bemærkninger (Additional context)**
Har ingen

**Comment by detfaellesdesignsystem** [comment]
Hej @postergaard,

Tak for din henvendelse.

Vi har tilføjet styling til readonly inputfelt med typen text - ændringen vil være med i næste release.

Vi har valgt at vise feltet som værende ren tekst - dvs. uden baggrund og kant, da brugeren kan blive forvirret over at få vist et inputfelt, som de ikke kan rette i. På grund af tilgængelighed forbliver border ved fokus på elementet, da det er et element der kan vælges og stadig læses op af en skærmlæser.

Ændringen er allerede tilføjet vores dokumentationssite, så du kan se det her: [https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter](https://detfaellesdesignsystem.github.io/dkfds-docs/komponenter/form-controls/#felter)

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by postergaard** [comment]
Mange tak for hjælp
