### ISSUE TITLE
Implementering af DKFDS js i Angular

### ISSUE THREAD

**Issue by detfaellesdesignsystem** [detfaellesdesignsystem/dkfds-components#80]
Er du så ikke rar at fotælle mig hvad jeg gør galt i den her Stackblitz:

https://stackblitz.com/edit/angular-ubsvkt

_Originally posted by @cjessing in https://github.com/detfaellesdesignsystem/dkfds-components/issues/74#issuecomment-547830968_

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Det skal blot simplificeres lidt i forhold til den måde vi testede det til release 5.0.0.

```
import { Component, OnInit } from '@angular/core';
import * as DKFDS from 'dkfds';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})

export class AppComponent implements OnInit {
  name = 'Angular';

    ngOnInit() {
        DKFDS.init();
  }

}
```

Bemærk at den kun vil håndtere komponenter, der eksisterer i HTML på det tidspunkt, hvor DKFDS.init() bliver kaldt. Components i angular som bliver loaded efterfølgende vil derfor ikke være dækket.

For yderligere support vil jeg anbefale, at du får fat i en angular ekspert, da vi kun kan supportere FDS og ikke de teknologier som diverse projekter gør brug af.

Jeg er derfor nødt til at lukke sagen her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
Just for the record: Ovenstående vil udelukkende have effekt for de DKFDS komponenter, der ligger i app.component.html. IKKE på underliggende komponenter.
