### ISSUE TITLE
Ønskes: Diskussionsforum til brugerne af DKFDS

### ISSUE THREAD

**Issue by cjessing** [detfaellesdesignsystem/dkfds-components#82]
Da DKFDS jo tidligere har gjort det klart, at I ikke ønsker at bistå med assistance, når det kommer til anvendelsen af Designsystemet ifm med opbygningen af en Angular-applikation, vil jeg foreslå at der - et eller andet sted - bliver oprettet et diskussionforum/community til brugerne af DKFDS. Derved kan vi - brugerne - forsøge at hjælpe hinanden inden vi belaster DKFDS med mere eller mindre relevante spørgsmål.

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Tak for din henvendelse!

Et diskussionsforum eller blot en kanal, hvor brugerne kunne tage kontakt indbyrdes blev faktisk taget op ved sidste [samarbejdsforum](https://designsystem.dk/omdesignsystemet/samarbejdsforum/). Der var dog ikke den store interesse for det på daværende tidspunkt, men vi har haft det i baghovedet siden,

Vi vil fortsat overveje muligheden for sådan en kanal og vil melde ud, hvis det bliver en realitet.

For nu har jeg lagt en sag i vores backlog om at udvide [eksempler på implementering af DKFDS](https://designsystem.dk/komigang/tiludviklere/eksempler-implementering/) i Angular, således at der også er et eksempel på implementering af javascript delen.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by cjessing** [comment]
On Wed, Nov 13, 2019 at 7:57 AM detfaellesdesignsystem <
notifications@github.com> wrote:

> Der var dog ikke den store interesse for det på daværende tidspunkt
>

Eh... har I da spurgt brugerne?

> ᐧ

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing,

Som beskrevet på [https://designsystem.dk/omdesignsystemet/samarbejdsforum/](https://designsystem.dk/omdesignsystemet/samarbejdsforum/) er samarbejdsforum netop et møde med brugerne. Alle kan deltage og du er mere end velkommen til at deltage i det næste. Der skulle gerne komme en dato ud for næste samarbejdsforum i denne uge.

Men som skrevet før overvejer vi stadig muligheden, og hvis du har flere input til, hvordan det kunne strikkes sammen tager vi gerne imod det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @cjessing 

Jeg tillader mig lige at følge op. 

På sidste Samarbejdsforum foreslog vi, at vi oprettede en kanal (fx Slack) som netværket kunne kommunikere igennem, men dette blev ikke ubetinget positivt mødt, da nogle mødedeltagere (brugere af FDS) mente, at der var kanaler nok at orientere sig i, og det kan der meget vel være noget om, så vi besluttede at skrinlægge det i hvert tilfælde for en periode. Vi tager det gerne op igen, da vi lever af brugerinvolvering. Så hvis det giver mening for vores brugere, opretter vi en netværkskanal. Det vil blive taget op på næste Samarbejdsforum igen. 

Vi vil gerne assistere, men det kan være yderst tidskrævende at fjernassistere, da problemløsning ofte kræver kontekst, og vi ikke kender det system vi skal supportere. Oftere end ikke, er der også tale om ting som FDS som sådan ikke håndterer. Vi har derfor også en stående invitation til alle myndigheder og deres leverandører, at I kan komme og arbejde sammen med os her i Erhvervsstyrelsen. Fx kunne de ting du gerne vil assisteres i meget vel danne grundlag for at gøre siden om Angular-integration bedre. https://designsystem.dk/komigang/tiludviklere/eksempler-implementering/ Du skal være velkommen her i Styrelsen.

Lad mig vide om det har interesse og ellers så ses vi måske til Samarbejdsforum.

Mvh
Sune
Det Fælles Designsystem

**Comment by cjessing** [comment]
Jeg har måske også nok lidt svært ved at se Slack som en vej frem. Jeg er
måske "old school", men jeg havde tænkt et ganske almindelig stykke
community software sat op (phpBB, vBulletin eller lignende) og så med et
forum for hvert af de "store" js frameworks (React, AngularJS, VueJS, Ember
and wot not). Og så måske et par mere (forslag, off topic og den slags).

*Claus Jessing*
---------------------------------------------
M: +45 6061 0101
E: claus@jessing.dk

ᐧ

**Comment by detfaellesdesignsystem** [comment]
Hej Claus 

Tak for dit forslag. Vi tager det op i Samarbejdsforum. 

Mvh
Sune
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi følger op på behovet for nye kanaler, fx et forum til diskussion og indbyrdes hjælp i det nye år. Indtil da opretter vi issues med label "diskussionsforum" som vi ikke lukker, hvor vi opfordrer til at man byder ind på hinandens forespørgsler.
