### ISSUE TITLE
Skip link

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#83]
Hej FDS

Vi er igang med et projekt, som vi har opgraderet fra version 5.0.0 til 5.1.0.
I beskriver i jeres release notes at der er blevet tilføjet fokuskant på #main-content ved fokus fra skip link.
Vi oplever nu at fokuskanten opstår på alt i main-delen af html, da denne har id=”main-content” som beskrevet i implementeringen https://designsystem.dk/design/typography/#skip-link. 
Denne fokuskant fremkommer når brugeren trykker et hvilket som helst sted i main. Er dette en fejl eller er det jeres hensigt?

![image](https://user-images.githubusercontent.com/54143827/69429658-5d1f1500-0d34-11ea-8f94-7c88445ac4ec.png)

mvh Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Tak for din henvendelse! :)

Der har ikke været muligt for mig at genskabe dette - kan du fortælle lidt mere om fejlen du oplever? Evt. også gerne oplysninger om browsere I oplever dette i.

Med venlig hilsen
Kristina Jensen

**Comment by ALT-ATP** [comment]
Hej Kristina

Vi har testet det i Chrome og Brave. Vi har lavet implementeringen af skiplinket som beskrevet:
```
<body>
  <app-root id="main-content"></app-root>
</body>
<a class="skipnav" href="#main-content">Gå til sidens indhold</a>
```
Vi oplever, at siden bliver genindlæst, når der trykkes på skiplinket. Derudover peger css'en på main-content, så der bliver altid sat focus på `<app-root>` ved klik et hvilket som helst sted på siden. Vi har prøvet at aktivere java-scripten, men det løser ikke problemet.

Vi bruger Angular 7, hvis det kan have noget med det at gøre.

Mvh
Asger fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @ALT-ATP,

Tak for din henvendelse :)

Skip link funktionaliteten er faktisk rent standard i browseren - så vi bruger ikke javascript til komponenten. Det er et helt simpelt anchor link, som flytter fokus på siden til det id, der er refereres til i href attributten. 

Jeg kender ikke så meget til Angular, men jeg tænker måske at anchor link er deaktiveret som standard, og at I skal gøre noget aktivt for at få denne funktionalitet til at spille med Angular.

Jeg søgte lige hurtigt og fandt noget i forbindelse med Router i Angular, hvor man har en option, der hedder anchorScrolling, måske dette vil kunne hjælpe jer.
Link til referencen: https://angular.io/api/router/ExtraOptions

Vi har som sagt ikke særlig erfaring med Angular i FDS, og har derfor udfordringer med at kunne supportere, når det kommer til dybere Angular spørgsmål, men jeg håber ovenstående reference kan hjælpe jer et stykke på vej.

Det kan selvfølgelig også være, der er en bedre måde at opnå samme funktionalitet, ved at bruge en anden metode i Angular, og der er I selvfølgelig velkomne til at bruge den metode, som passer bedst i jeres teknologi. Husk tilgængelighed, hvis I vælger en anden metode.

Hvis I finder en løsning, må I meget gerne melde tilbage, så andre, der måske har samme udfordring kan finde svaret her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by ALT-ATP** [comment]
Hej Kristina

Tak for svaret. Jeg får lige set på det ved lejlighed og vender tilbage.

Venlig hilsen
Asger Laurits Schultz
[Adobe Systems]
Studentermedhjælper  ·  Application Development - Solutions
Direkte nummer 50661014
E-mail alt@atp.dk<mailto:alt@atp.dk>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP Koncernen på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: detfaellesdesignsystem <notifications@github.com>
Sendt: 5. december 2019 11:15
Til: detfaellesdesignsystem/dkfds-components <dkfds-components@noreply.github.com>
Cc: Asger Laurits Schultz - ALT <ALT@atp.dk>; Mention <mention@noreply.github.com>
Emne: Re: [detfaellesdesignsystem/dkfds-components] Skip link (#83)


Hej @ALT-ATP<https://github.com/ALT-ATP>,

Tak for din henvendelse :)

Skip link funktionaliteten er faktisk rent standard i browseren - så vi bruger ikke javascript til komponenten. Det er et helt simpelt anchor link, som flytter fokus på siden til det id, der er refereres til i href attributten.

Jeg kender ikke så meget til Angular, men jeg tænker måske at anchor link er deaktiveret som standard, og at I skal gøre noget aktivt for at få denne funktionalitet til at spille med Angular.

Jeg søgte lige hurtigt og fandt noget i forbindelse med Router i Angular, hvor man har en option, der hedder anchorScrolling, måske dette vil kunne hjælpe jer.
Link til referencen: https://angular.io/api/router/ExtraOptions

Vi har som sagt ikke særlig erfaring med Angular i FDS, og har derfor udfordringer med at kunne supportere, når det kommer til dybere Angular spørgsmål, men jeg håber ovenstående reference kan hjælpe jer et stykke på vej.

Det kan selvfølgelig også være, der er en bedre måde at opnå samme funktionalitet, ved at bruge en anden metode i Angular, og der er I selvfølgelig velkomne til at bruge den metode, som passer bedst i jeres teknologi. Husk tilgængelighed, hvis I vælger en anden metode.

Hvis I finder en løsning, må I meget gerne melde tilbage, så andre, der måske har samme udfordring kan finde svaret her.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Som nævnt på samarbejdsforum i går, har du så mulighed for at oplyse om den browser og evt. browserversion hvori I oplever denne opførelse, hvor der er fokuskant om indholdet, selv når man ikke har brugt skiplink?

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by JAU-atp** [comment]
Vi har testet det i Chrome, men jeg er usikker på versionen.  Jeg kan vende tilbage med dette når jeg har fået oplysningerne fra udviklerne 

mvh. Josephine

**Comment by ALT-ATP** [comment]
Hej @detfaellesdesignsystem 

Vi har fundet en løsning, så jeg skriver den lige her til fremtidig reference. Fejlen kommer af, at [Angular ændrer anchor-taggets opførsel](http://markleblog.com/tl-dr/), så der udsendes et router-event ved den almindelige implementering. Løsningen er programmatisk at styre id'et på `<main>`, så det kun er "main-content", når der faktisk skal sættes fokus på det. Så i sin template har man
```
<a class="skipnav" (click)="onSkipLinkNav()" href="javascript:void(0)">Gå til sidens indhold</a>
...
<main class="container page-container" [id]="mainId" tabindex="-1">...</main>
```
og i komponenten
```
mainId: "main-content" | "main-content-no-outline" = "main-content-no-outline";
constructor(private router: Router) {
    this.router.events.subscribe(event => { this.mainId = "main-content-no-outline"; });
}
onSkipLinkNav() {
    // Sætter fokus på <main> og sætter id, så der kommer outline på
    this.mainId = "main-content";
    setTimeout(() => document.getElementById("main-content").focus(), 0);
  }
```
I css'en skal der være defineret
```
#main-content-no-outline {
    outline: none;
}
```
