### ISSUE TITLE
logo på print

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#85]
Hej FDS

Vi er igang med et projekt og forretningen har et ønske om, 
at ordningens logo kommer med på print.
Vi er i tvivl om, hvor i headeren vi skal placere dette, eller hvorvidt det er en del  
af designstandarderne hos FDS? 

Mvh Josephine fra ATP

**Comment by DKFDSdevelop** [comment]
Hej Josephine @JAU-atp 

Vi har det i backloggen og fikser det i det nye år.

Mvh
Sune
FDS

**Comment by detfaellesdesignsystem** [comment]
Hej Josephine @JAU-atp 

Vi har det i backloggen og fikser det først i det nye år.

Mvh
Sune
FDS
