### ISSUE TITLE
Tilgængelighed (heading) i accordians

### ISSUE THREAD

**Issue by FNA-atp** [detfaellesdesignsystem/dkfds-components#88]
Hej dk-fds,
Har I tænkt headings-hieraki i accordians - og i forhold til skærmlæsere? Vores in-house wcag-tester anbefaler, at accordians skal have headings-hieraki. 

![image](https://user-images.githubusercontent.com/48348000/71083160-ae36f300-2192-11ea-838c-e878c2527196.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Rigtig godt fanget. Og godt I gør opmærksom på det!

Jeg stublede faktisk over det for et par uger siden, så den ligger i backloggen at vi skal kigge på det. Mener den ligger ganske højt, så den bliver nok taget med i januar/februar.

Men jo, så vidt jeg husker, så er WCAGs anbefaling at det bør være en semantisk heading, og ikke blot en button. Hvorvidt det kan løses med den button-løsning vi har nu, så det stadig er valid HTML er nok det jeg skal undersøge nærmere, når vi tager sagen ind i sprint.

Jeg melder lige tilbage efter nytår, med hvornår vi kan tage den ind.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @FNA-atp,

Mulighed for at bruge overskrifter i forbindelse med accordionknapper er implementeret i version 7.2.0.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
