### ISSUE TITLE
Question:  dkfds-plugin (Udvidelser: Avancerede tabeller)

### ISSUE THREAD

**Issue by laclogin** [detfaellesdesignsystem/dkfds-components#9]
Lille spørgsmål: 

Der er tilføjet tool elementer (se billede) i dkfds-plugin, som ikke findes i det grundlæggende https://datatables.net/ ? 

![image](https://user-images.githubusercontent.com/25169794/52475155-e943bf80-2b9a-11e9-8f95-e7485366b494.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @laclogin,

Tak for din henvendelse.

Det er dummyknapper, som er blevet prepended med JavaScript.

Jeg kan forstå det er forvirrende, og vil se, hvad vi kan gøre for at vise de ikke er en del af datatables.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by laclogin** [comment]
Tusind tak for jeres hurtige tilbagemelding. 

Det ville være rigtig fint, hvis I kunne tilføje en lille informationstekst i [docs](https://detfaellesdesignsystem.github.io/dkfds-docs/udvidelser/datatables/#datatables) om hvilke FDS elementer der bliver prepended i datatables. 

Med venlig hilsen 
Laura Beck
ATP
