### ISSUE TITLE
Faneblade opfører sig som accordions

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#90]
Hej FDS,
Vi er i gang med at opgradere en af vores selvbetjeningsløsninger fra dk-fds version 4.4.0 til 5.3.0. Det giver os nogle udfordringer i forbindelse med faneblade.

På version 4.4.0 ser løsningen således ud:
![image](https://user-images.githubusercontent.com/54143827/72074712-b518d780-32f2-11ea-8aea-7595151a4568.png)

Ved at klikke på linket "Se detaljer" bliver følgende modal åbnet:
![image](https://user-images.githubusercontent.com/54143827/72074730-bcd87c00-32f2-11ea-9a2f-6c406331f48a.png)

I version 5.3.0 begynder fanebladene at opføre sig som accordions (på trods af at vi ikke benytter os af accordions i denne løsning)
![image](https://user-images.githubusercontent.com/54143827/72074970-25bff400-32f3-11ea-990e-e31f18985c03.png)

Som det kan ses på overstående billede, så viser den ikke længere hele tabellen og det kræver at man klikker på fanebladet før at den folder sig ud. Alle links (Se detaljer) får tildelt styling fra accordions og reagerer ikke længere ved at der klikkes.

Hvordan skal vi løse dette problem?
Mvh. Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Fanebladskomponenten var før version 5.0.0 ufærdig i mangel af bedre ord - der var mange ting, som ikke var taget stilling til, og det var i princippet blot en kopi af menuen i headeren.

På billede 3 ligner det, at faneblade er vist i en modal, er dette korrekt? Jeg er ikke sikker på at micromodals understøtter ændringer i indholds-mængden, så den tilpasser højden på den måde.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Fra version 6.0.0 blev faneblad optimeret, så dette ikke længere er et issue.

Jeg lukker derfor sagen.
