### ISSUE TITLE
Filtrering af Tabel med input felter

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#91]
Hej FDS,
Vi er igang med at udvikle en løsning med filtrerings mulighed på CPR-nr. og medarbejder nr. som det kan ses på nedestående billede. 
![image](https://user-images.githubusercontent.com/54143827/72992671-74da4e80-3df4-11ea-9b40-bbfb9e619452.png)

Som løsningen fungerer nu, så begynder den at filtrerer med det samme man taster noget ind i input felterne. Tabellen viser hermed de muligheder som matcher søgningen. Vi er usikre på om dette lever op til design standarderne, eller om der skal være en søg knap, sådan at den først begynder at filtrerer ved klik af denne?

Mvh. Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Som vi snakkede om i går, så er vores anbefaling, at I tilføjer en knap. Jeg har ikke testet det, men kunne forestille mig at det ville være en udfordring rent tilgængelighedsmæssigt at gøre opmærksom på tabellen, der opdaterer efter hvert tegn indtastet i filtreringsfelterne. Det ville blive løst nemt med en simpel knap.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Der har ikke været aktivitet på dette issue i noget tid, så derfor lukkes den nu.

Hvis det skal tages op igen, så er man velkommen til at genåbne eller oprette et nyt issue.
