### ISSUE TITLE
Tabnav styling issue

### ISSUE THREAD

**Issue by VictorWinberg** [detfaellesdesignsystem/dkfds-components#92]
[Only one bug per issue and make sure to check if the issue already exists]

**Describe the bug**
There is a styling issue when inserting other styled elements inside of a tabnav class.

**To Reproduce**
E.g. by inserting a tabel inside a tabnav.

**Screenshots**
Looks like this:
![image](https://user-images.githubusercontent.com/9520959/73440162-14499500-4351-11ea-91c8-9aafbdce3442.png)
But should look like this:
![image](https://user-images.githubusercontent.com/9520959/73440197-21ff1a80-4351-11ea-8503-33fef2f469d8.png)

**Comment by detfaellesdesignsystem** [comment]
Hi @VictorWinberg,

Thank you for contacting us - and thanks for the fix!

We'll look into it and include the fix in the next release.

Best regards,
Kristina Jensen
Det Fælles Designsystem
