### ISSUE TITLE
Centrér Dropdown Menu Options

### ISSUE THREAD

**Issue by Polsenols** [detfaellesdesignsystem/dkfds-components#95]
**Navn i designsystemet (Feature name in the design system)**
Dropdown-menu

**Link til det der skal opdateres (URL to what needs to be updated)**
https://designsystem.dk/komponenter/form-controls/#dropdown-menu

**Skyldes dit forslag et problem? Beskriv venligst. (Is your update request related to a problem? Please describe.)**
Problemet er at dropdown menu mulighederne ikke er centreret vertikalt, men i stedet er aligned (eller slet ikke aligned) til toppen af hver option. Det ser bare ikke så godt ud, og følger heller ikke standarden hvis man kigger på UK og US design systemerne, hvor at de er centreret.

**Beskriv det du gerne ser ske. (Describe the solution you'd like)**
Centrér menu options så de ikke er i toppen.

**Supplerende bemærkninger (Additional context)**
![image](https://user-images.githubusercontent.com/14940475/73831611-ecea4080-4806-11ea-8c01-8b522f0bc655.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @Polsenols,

Tak for din henvendelse.

Vi er klar over udeståendet - det er desværre et issue vi har med skrifttypen. Den sætter sig anderledes i lineheight end andre skrifttyper. Desværre er det begrænset, hvor meget man kan style en select, så vi har indtil videre ikke fundet en hurtig løsning.

Vi har den i backloggen, og vil vende tilbage når vi ved mere.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Vi har endelig fået svar fra folkene bag IBM Plex, som har lavet et ny version, der fikser dette issue.

Den nye version af fonten vil komme med i næste release.

Jeg lukker derfor sagen her.
