### ISSUE TITLE
Sidste tabel i nestede tabeller mangler styling

### ISSUE THREAD

**Issue by ALT-ATP** [detfaellesdesignsystem/dkfds-components#96]
Hej DKFDS

Ved brug af tabeller i tabeller som vist [her](https://designsystem.dk/udvidelser/datatables/#expandable-table) opstår der stylingproblemer i sidste nestede tabel, i og med at de vandrette streger forsvinder som vist på billedet.

Mvh Asger

![image](https://user-images.githubusercontent.com/58464994/73848578-aa396000-4828-11ea-867d-d17eafb6a0cf.png)

**Comment by detfaellesdesignsystem** [comment]
Hej @ALT-ATP,

Jeg har oprettet en sag på det i backloggen.

Vender lige tilbage, når vi har haft mulighed for at kigge på det.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @ALT-ATP ,

Vi har lavet et fix, og det vil komme med i næste release.

Vi regner med at næste release sker i start marts.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem
