### ISSUE TITLE
Alert farver i cards

### ISSUE THREAD

**Issue by JAU-atp** [detfaellesdesignsystem/dkfds-components#97]
hej FDS

På vores selvbetjeningsløsning "se feriepenge"  er det muligt at et beløb bliver vist enten før eller efter skat. Vi har gjort brug af en alert(warning) for at gøre brugeren opmærksom på når pengene er før skat. 

Vi vil gerne skabe en tydelig sammenhæng mellem alert beskederne (som er der når det er før skat) og de cards som viser beløbet før skat.

Må vi bruge alert farven i carded som vist på billedet nedenfor istedet for datavisualiseringsfarverne ?
 
![image](https://user-images.githubusercontent.com/54143827/74522293-33345380-4f1b-11ea-9363-c489130d9383.png)

![image](https://user-images.githubusercontent.com/54143827/74522273-2e6f9f80-4f1b-11ea-955d-3f946ac8e963.png)

mvh. Josephine fra ATP

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp,

Tak for dit spørgsmål!

Sune er på sagen og vil vende tilbage hurtigst muligt.

Med venlig hilsen
Kristina Jensen
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment]
Hej @JAU-atp 

Jeg ville være i tvivl om farven alene kan skabe den ønskede kobling. Hvad med at have alert'en inde i card'et, så er der ingen tvivl om, hvad der hænger sammen med hvad? Så holdes god skik og brug for alert'en og brugeren skal ikke bruge kognitive ressourcer på at koble betydningen af farver forskellige steder på skærmen.

Nu vi er ved det vil jeg slå et slag for venstrestilling af indholdet. Centreret tekst er i sig selv ikke læsevenligt, og i det viste eksempel hjælper det heller ikke til skimbarhed. Et yderligere tilsigtet gode ved venstrestilling er, at de responsive ændringer fra små til store skærme bliver næsten ingen ting. 

Jeg har  lavet tre versioner, der forhåbentligt illustrerer forslagene ovenfor - og det skal tages med forbehold for, at jeg slet ikke er bekendt med tekniske begrænsninger eller foretningsspecificiteter for jeres løsning.

"lille" mobil
![lille mobil](https://user-images.githubusercontent.com/44367338/74774375-dbd41180-5293-11ea-970b-88fef47ce48e.jpg)

"normal" mobil
![normal mobil](https://user-images.githubusercontent.com/44367338/74774584-5735c300-5294-11ea-8a68-1dea7e2b3d57.jpg)

desktop
![desktop](https://user-images.githubusercontent.com/44367338/74774596-5a30b380-5294-11ea-8f04-bc3c2a957f0e.jpg)

Mvh
Sune
FDS

**Comment by JAU-atp** [comment]
Hej Sune, tak for dit input. 
Jeg har taget dit forslag med videre til ux'erne, som har besluttet sig for at gå med din version.
mvh Josephine - ATP
